### PR TITLE
EZP-24310: Refactor field type search integration tests to better support custom fields

### PR DESCRIPTION
**Pull request by pspanja**
This resolves https://jira.ez.no/browse/EZP-24310

Field type Field criterion and sort clause search integration tests are here refactored to make testing of additionally indexed fields (aka custom fields, accessed through `CustomFieldInterface`) easier.

Data for testing these fields is now provided through a separate method `getAdditionallyIndexedFieldData()`, for each additionally indexed field. For example:

```php
array(
    array(
        'file_size',
        1024,
        4096
    ),
	...
)
```

Values must be taken from the values of the created test fields. This is kept separate from providing test data for the default field, in order to keep test implementation for default fields as simple as possible.

### CODE REVIEW

**Comment by pspanja** [comment]
Ready for review, ping @andrerom, @yannickroger, @bdunogier, @glye, @lolautruche

**Comment by glye** [comment]
What about the failing tests, have these been discussed already? Seems essential given the subject matter :)

**Comment by pspanja** [comment]
@glye Fix coming up shortly, I had some ridiculous issues with Elasticsearch :)

**Comment by pspanja** [comment]
Now fixed the tests, they were only missing some skips for Location search on Elasticsearch and BinaryFile on Legacy. Travis will take its time this time of day though...

**Comment by glye** [comment]
+1 if Travis is happy.

**Comment by lolautruche** [comment]
+1 FWIW

**Comment by andrerom** [comment]
@pspanja this PR seems to have added 490 more skipped tests *(up from 1307 to 1797)*, as far as @bdunogier could see it is caused by exception that image field type can not be indexed.

**Comment by pspanja** [comment]
Previously, Location Search was not tested with modified field. There are total 7 additional fields (2 BinaryFile, 3 Image and 2 Media), for each there are 34 tests executed. Each set of tests is executed for filtering and querying Query. Total that is 2 * 7 * 34 = 476. Sort is also tested with Location Search, in ascending and descending order, which is total 2 * 7 = 14. That gives grand total of 490 :)

If you look at Solr and Elasticsearch tests, the output of field type search tests is completely clean, so all of that is caused by Legacy search engine not being able to search additional (custom, modified) fields.

**Comment by bdunogier** [comment]
> so all of that is caused by Legacy search engine not being able to search additional (custom, modified) fields

It makes sense. But we now have a bunchzilla (that's a big bug) of skipped tests in at least the Image API integration tests. It skips `testContentCreate`, thus skipping almost everything else. Are the search capabilities supposed to be that invasive ?

**Comment by pspanja** [comment]
`testCreateTestContent` serves only to prepare the database fixture, and to return the context (Repository and Content) for each test to run. So it is basically an entry point for search set of tests, first checking if the field type is searchable with the search engine. I did it that way to avoid reinitialization of the database for each and every test, otherwise the number of tests I added would take forever to complete. Particularly with Solr and Elasticsearch, which also have to reindex everything.

Note that `testCreateTestContent` being skipped does not affect other (not search related) tests.

**Pull request merged**
