### PR TITLE
Fix EZP-24422: Country type doesn't allow default selection

### PR DESCRIPTION
**Pull request by glye**
https://jira.ez.no/browse/EZP-24422

which is blocking https://jira.ez.no/browse/EZP-24389
https://github.com/ezsystems/repository-forms/pull/18

### CODE REVIEW

**Comment by lolautruche** [comment]
+1, but tests need to be updated :wink:

**Comment by glye** [comment]
Yep, added now. Too much meetings today to keep on top of PRs..

**Comment by andrerom** [comment]
+1 if travis agrees :)

**Comment by glye** [comment]
Haha, fooled you :-P
This isn't needed.

**Pull request closed without merging**
