### PR TITLE
Installer - create database if it does not exist

### PR DESCRIPTION
**Pull request by Plopix**
we need a database to `ezplatform:install`

### CODE REVIEW

**Comment by Plopix** [comment]
I think the current state of the installation process is bad and newcomers might give up because following the *simple steps* (in this welcome text - not in the documentation) is not working.

@alongosz: I agree `ezplatform:install` could be more interactive. but we need to fix the issue and the doc (IMHO) right now.

@andrerom I have added the option

**Comment by andrerom** [comment]
@Plopix Define "not working", install instructions specifically mentions you should have database created before starting => Do you see this as a common issue?

**Comment by Plopix** [comment]
"not working" might be strong. But still that should be easy.
```
composer create
ezplatform install
```

Because `ezplatform install` does not call `doctrine:database:create` then we need to say it.

To me it is not enough to put it in the doc that we need a database.
That does not hurt to put it in the WelcomeText.

I agree it should be run in the `ezplatform install` but right now (waiting for that change) I would add the `database:create`.

I am thinking about people who knows symfony, they would not expect a database error when you run a command (provided by the composer create).

Also why letting the user create his own DB alone, he/she could do it using the wrong charset etc. `database:create` symplifies that.

Make sense?

**Comment by andrerom** [comment]
@Plopix You are in luck, installer already have abstraction for running other commands.
So it is actually very easy to add the call you propose here in it before inserting data:

see index command call here: https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php#L169-L175

Only extra bit to handle is to check exit code for errors I guess _(haven't checked code of the doctrine command, just assuming it might have some)_.

**Comment by Plopix** [comment]
So much in luck ;) 
Hope the code reduction will please you @andrerom @alongosz 🍻 ⛵️

**Comment by andrerom** [comment]
It does, to me this looks like a step in the right direction. @alongosz Anything missing from your side for intermediate step here?

**Pull request merged**
