### PR TITLE
EZP-30229: Track original state of Location::$hidden

### PR DESCRIPTION
**Pull request by Nattfarinn**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-30229](https://jira.ez.no/browse/EZP-30229) (Alternative approach)
| **Bug/Improvement**| yes
| **New feature**    | yes
| **Target version** | `master`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

**TODO**:
- [x] Implement feature / fix a bug.
- [x] ~Implement tests.~
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by andrerom** [comment]
+0.1, fixes the design issue caused by introduction of content->hidden which made "hidden" dubious, might now be similar issues other places as well.

**Comment by lserwatka** [comment]
@Nattfarinn can you make PR out of this draft? We can proceed with QA.

**Comment by pspanja** [comment]
TBH I find this naming a bit contrived. Also, I've always found the double negative check that Location is not hidden/invisible weird. It would be more natural to just check if the Location is visible.

So rather than doing this, you can take this chance to introduce `$visible` property indicating that Location can be displayed (is visible and has visible Content), and keep current `$hidden` and `$invisible` properties relating to the Location only. Since `$invisible` would then clash with new `$visible` property, it could be renamed (with BC) to more precise `$hiddenByAncestor` or similar.

**Comment by gggeek** [comment]
@pspanja I am generally a great fan of BC, but in this case you might have a point about renaming 'visible' properties, as so far they have been quite confusing.

I agree about `hiddenbyAncestor`: clear name for what it is.

What still bothers me is that we would end up with:
`hidden` = location has been hidden
`visible` = location is not visible because either it is hidden, hiddenByAncestor or hiddenByContent
but in my mind hidden and visible are still direct negations of each other. Which means that devs might code things like `if ! $hidden` when they mean `if $visible`.
Is there a better option?
We could f.e. make it even more clear that the 'hidden' states are 3, and give then names `hiddenBySelf`, `hiddenByAncestor` and `hiddenByContent`...

**Comment by Nattfarinn** [comment]
I agree naming is a bit awkward, even without latest changes, but for the sake of a BC we had to postpone such changes till 3.0. This PR is still just a Draft (serves as MVP and starting point for iterative improvement) and we're working on another solution to keep Location intact in a first place. But can't tell yet if better approach will be possible till LTS because of a potential BC breaks in content model.

For now we have to use `$hidden` flag as compound of Location and Content hidden state (it works out-of-the-box without BC), but we still need an original value of `Location::$hidden` for some other use cases hence the new flag.

> So rather than doing this, you can take this chance to introduce $visible property indicating that Location can be displayed

I am not sure we need a property for this. It looks like a candidate for a `LocationService::isVisible(Location $location): bool;` method for cases when API Location flags are not enough to determine if it actually is visible for end-user or not (idk. maybe because it is behind pay-wall or something).

**Comment by lserwatka** [comment]
@Nattfarinn can you write integration test for this one?

**Pull request merged**
