### PR TITLE
Added deprecation doc of already deprecated view actions

### PR DESCRIPTION
**Pull request by antoligy**
Fixing deprecation notices in `ViewController` as they are inconsistent.

### CODE REVIEW

**Comment by andrerom** [comment]
@emodric was this discussed on slack? WDYT?

**Comment by alongosz** [comment]
@andrerom AFAICS this is just follow-up on E_USER_DEPRECATED that is already triggered in the methods body.

**Comment by emodric** [comment]
Looks good! 👍

**Comment by antoligy** [comment]
Cheers guys! 😄

**Comment by andrerom** [comment]
Thanks @antoligy :)

**Pull request merged**
