### PR TITLE
EZP-29839: ReindexCommand should allow to use selected user

### PR DESCRIPTION
**Pull request by kmadejski**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-29839](https://jira.ez.no/browse/EZP-29839)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `6.7`/`6.13` / `7.2` / `7.3` / `master`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

This PR introduces a new command option for setting proper user for command execution. 

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by kmadejski** [comment]
@alongosz I agree but didn't want to introduce such a significant change since it goes to 6.7. We can do it as a follow-up in master I think.

**Comment by kmadejski** [comment]
JFYI: Force-pushed to restart the AppVeyor build. No code changes.

**Comment by andrerom** [comment]
@kmadejski It hit me that this issue is pretty strange given we mostly use raw SQL and SPI handlers for indexing. As in there should be no permissions handling involved at all afaik.

So I'm starting to wonder if this is the wrong fix, it complicated the command both in regards to option and in regards to starting to use API.  If something is not indexed there is another bug somewhere.

**Comment by kmadejski** [comment]
@andrerom you are totally right, this is why I put this on hold for some time. I'm currently waiting for the more info from the customer on how exactly he experienced a problem.

**Comment by andrerom** [comment]
Ok, let's put on hold QA spending time on this then. Removing label, please also move issue back to dev or something.

**Comment by kmadejski** [comment]
The issue which is solved by this PR comes from the custom code, therefore we don't need that change and I'm closing this PR as well as JIRA ticket. 

@RemySMILE thanks for your contribution, but you have to dig into your code and try to fix it on your side.

**Pull request closed without merging**
