### PR TITLE
EZS-593: Editors can not create new or update existing content, due to lack of permissions

### PR DESCRIPTION
**Pull request by Nattfarinn**
**JIRA ticket related:** https://jira.ez.no/browse/EZS-593

New `Supervisor` role that gives user content read permissions created.

### CODE REVIEW

**Comment by andrerom** [comment]
Like on [demo](https://github.com/ezsystems/ezplatform-demo/pull/13):

Please just change name of Member to Supervisor and change from owner limitation to Section limitation on existing policy that you added on last PR.

**Comment by Nattfarinn** [comment]
@andrerom Done :)

**Comment by bdunogier** [comment]
The issue should be changed to an EZP one, should it not ?

**Comment by andrerom** [comment]
done: https://jira.ez.no/browse/EZP-25789

**Comment by bdunogier** [comment]
Thank you @andrerom.

**Pull request closed without merging**
