### PR TITLE
Fix EZP-24475: Move TwigLoaderString to LegacyBridge

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24475

Ref https://github.com/ezsystems/LegacyBridge/pull/29

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @bdunogier @yannickroger @pspanja @glye

**Comment by bdunogier** [comment]
+1

**Comment by andrerom** [comment]
Not moving the class?

for pr: +1

**Comment by lolautruche** [comment]
> Not moving the class?

Hum... /me was tired (or drunk) yesterday :blush:

**Comment by andrerom** [comment]
:)

**Comment by lolautruche** [comment]
Fixed. Thanks for the heads up!

**Comment by andrerom** [comment]
with travis: +1

**Pull request merged**
