### PR TITLE
Fix wrong example for Legacy DFS cluster config

### PR DESCRIPTION
**Pull request by lolautruche**
Quick doc fix :octocat:

### CODE REVIEW

**Comment by lolautruche** [comment]
Ping @bdunogier

**Comment by yannickroger** [comment]
+1
ref: https://doc.ez.no/display/EZP/Legacy+DFS+cluster

**Comment by crevillo** [comment]
+1

**Comment by andrerom** [comment]
+1 if it is right :P

**Comment by bdunogier** [comment]
+1 indeed

**Comment by lolautruche** [comment]
Thanks guys :-)

**Pull request merged**
