### PR TITLE
Fixed login form not showing on Unauthorized repository exception

### PR DESCRIPTION
**Pull request by bdunogier**
> Fixes https://jira.ez.no/browse/EZP-24975 
> Status: ready for review

For a detailled explanation of the issue and the solution, see https://jira.ez.no/browse/EZP-24975.

### CODE REVIEW

**Comment by bdunogier** [comment]
The errors in the REST behat tests might be interesting...

**Comment by bdunogier** [comment]
The remaining failure has been fixed.

**Comment by andrerom** [comment]
+1

**Comment by lolautruche** [comment]
+1

**Comment by bdunogier** [comment]
woot

**Pull request merged**
