### PR TITLE
Fixed SensioLabs Insight failures

### PR DESCRIPTION
**Pull request by bdunogier**
> My reply to #1152 

Fixes [Sensio Labs Insight issues](https://insight.sensiolabs.com/projects/0885c0ce-4b9f-4b89-aa9c-e8f9f7a315e0/analyses/122) attributed to me.

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by yannickroger** [comment]
+1
What about those that are not attributed to @bdunogier are we fixing them ?

**Comment by lolautruche** [comment]
+1

**Comment by andrerom** [comment]
> What about those that are not attributed to @bdunogier are we fixing them ?

you are free to go over list and take a few attributed to yourself and other low hanging fruits when you have some time ;)

**Comment by yannickroger** [comment]
@andrerom will do :)

**Pull request merged**
