### PR TITLE
EZP-30911: Added option to pass location-id parameter to URL alias regeneration Command

### PR DESCRIPTION
**Pull request by mateuszbieniek**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-30911](https://jira.ez.no/browse/EZP-30911)
| **Improvement**| yes
| **New feature**    | no
| **Target version** | `7.5` 
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | yes

This PR adds an option to pass array option `location-id` so regeneration of URL aliases can be done for only specific locations, like this:
`php bin/console ezplatform:urls:regenerate-aliases --location-id=1 --location-id=2 --location-id=100`

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by mateuszbieniek** [comment]
@andrerom not sure, as v1 and v2 commands for regenerations are quite different.

**Comment by alongosz** [comment]
> But this is probably also relevant for 1.13 right?

It's kind of a feature, so I'd recommend upgrading to 2.5 to be able to use it for specific Locations. Moreover v1 does not support strict types, so refactoring would be quite extensive for method parameters and return types.

**Comment by andrerom** [comment]
ok, if needed we can always cherry pick and backport 👍

**Comment by alongosz** [comment]
@mateuszbieniek could you merge up?

**Comment by mateuszbieniek** [comment]
@alongosz done in https://github.com/ezsystems/ezpublish-kernel/commit/f81af134da83c30a4f6dbd69170f911916532dc4

**Pull request merged**
