### PR TITLE
Implement EZP-24376: Implement language analysis for multicore Solr search engine implementation

### PR DESCRIPTION
**Pull request by paulborgermans**
Initial pull request for review

https://jira.ez.no/browse/EZP-24376

### CODE REVIEW

**Comment by pspanja** [comment]
Looks good so far, +1 on the approach and placement.

**Comment by andrerom** [comment]
looks good so far, I assume by @pspanja comment this is work in progress.
If so please add short [task list](https://github.com/blog/1825-task-lists-in-all-markdown-documents) in description as it will make it clear everywhere that it is work in progress, the less review useful alternative convention is to add `[WIP] ` in the PR title.

**Comment by andrerom** [comment]
Given we are not planning to do any new ezfind releases, does it make sense to move this work to SolrBundle?

**Comment by paulborgermans** [comment]
@andrerom: I dont see the relation with eZ Find releases, it is pretty generic to configure the Solr backend and the schema in a (several) language specific core(s)

**Comment by andrerom** [comment]
Sorry ignore that comment.

What I meant to say is rather:
- what remains on this functionally? (ref my comment june 11th)
- also we have moved solr code to [own bundle](https://github.com/ezsystems/ezplatform-solr-search-engine) now, so will need to generate diff from this and re apply it there*


\* On the plus side this makes it easier to work on Solr, all in one place now as opposed to spread around kernel like it was in the past.

**Pull request closed without merging**
