### PR TITLE
Migrate http cache configuration

### PR DESCRIPTION
**Pull request by bdunogier**
Makes it possible to disable any `ConfigParser` loaded by the `CoreExtension`. Used to allow ezsystems/ezplatform-http-cache to disable the `http_cache` semantic config.

The generic approach can be used for further extractions of features.

### TODO
- [ ] Consider targetting 6.13 instead

### CODE REVIEW

**Comment by andrerom** [comment]
Btw, to make sure we are aiming for similar thing, ok If I aim in #2013 to remove any dependency we have on FOSHttpCache in kernel 7.0 so all of that can more easily be handled purely in ezplatform-http-cache for v2.x? That will fit quite well here right? as the bundle will also with what you are working on there take case about adding the config section needed for http cache right?

**Comment by bdunogier** [comment]
> ok If I aim in #2013 to remove any dependency we have on FOSHttpCache in kernel 7.0 so all of that can more easily be handled purely in ezplatform-http-cache for v2.x? That will fit quite well here right?

Good catch. Yes, go ahead.

**Comment by alongosz** [comment]
@bdunogier We merged #2194 recently. Does this one still apply?

**Comment by andrerom** [comment]
I think this was skipped by @vidarl and @bdunogier in favor of changes done last fall here: https://github.com/ezsystems/ezplatform-http-cache/pulls?q=is%3Apr+is%3Aclosed+author%3Avidarl

**Comment by alongosz** [comment]
Ok, closing then.

**Pull request closed without merging**
