### PR TITLE
EZP-30585: Dropped unused translation methods from inner ContentService

### PR DESCRIPTION
**Pull request by mateuszbieniek**
More in JIRA issue: [EZP-30585](https://jira.ez.no/browse/EZP-30585)

### CODE REVIEW

**Comment by andrerom** [comment]
@mateuszbieniek Seems like you can remove more: https://github.com/ezsystems/ezpublish-kernel/commit/ccc80ae4a327c11c5ce0eac66a54d0bdc6bdd00f#diff-4321ba086690f6f89abef111ea256618

**Comment by mateuszbieniek** [comment]
@andrerom good we have CRs ;)

**Comment by andrerom** [comment]
@mateuszbieniek You can also deprecate the signals if they are not yet, so it's clear the can be removed in 8.0 (master) ;)

**Comment by alongosz** [comment]
Nothing to test here. Merging.

**Pull request merged**
