### PR TITLE
Fix EZP-23868: Move getLegacyKernel() helper from CoreBundle controller ...

### PR DESCRIPTION
**Pull request by lolautruche**
...to LegacyBundle

> https://jira.ez.no/browse/EZP-23868

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @bdunogier @yannickroger

**Comment by yannickroger** [comment]
+1

**Comment by andrerom** [comment]
+1
IMO we should also backport it somehow so function logs deprecation warning on 5.4 and so you can already start using new class there, but if we do so then this is actually deprecated in 5.4.2 and removed in 6.0.

**Comment by lolautruche** [comment]
@andrerom Updated.

**Comment by bdunogier** [comment]
+1

**Pull request merged**
