### PR TITLE
Fix EZP-25171: UTF8 Encoded ViewParameters are not matched

### PR DESCRIPTION
**Pull request by blankse**
JIRA: https://jira.ez.no/browse/EZP-25171

When I copy a URL with ViewParameters in Firefox. The Url will be UTF8 encoded. So the brackets are %28 and %29
E.g.: http://www.example.tld/site/(param)/value -> http://www.example.tld/site/%28param%29/value

The new stack can now not match the route and give it to the legacy. There it can be matched.

When I look in the code I see, that the rawurldecode function has been used only for the semanticPathinfo:
https://github.com/ezsystems/ezpublish-kernel/blob/2267c6e903c38b027b3b97e2901ccf0923bcbbad/eZ/Publish/Core/MVC/Symfony/Routing/UrlAliasRouter.php#L126

In legacy it works because of:
https://github.com/ezsystems/ezpublish-legacy/blob/e6c912113a8cee636070d2ac1fcbd308f713b97e/lib/ezutils/classes/ezuri.php#L224

### CODE REVIEW

**Comment by bdunogier** [comment]
Oh, nice. Will check, but it sounds like a good one. We might wanna add coverage though.

**Comment by blankse** [comment]
@bdunogier I added a test

**Comment by andrerom** [comment]
*Hmm, would have wished Symfony handled these things.*

Otherwise +1

**Comment by bdunogier** [comment]
+1

**Comment by andrerom** [comment]
Thanks @blankse, merging :)

**Pull request merged**
