### PR TITLE
Fix EZP-28789: Warning in LocationId Matcher if Content has no Location

### PR DESCRIPTION
**Pull request by blankse**
JIRA: https://jira.ez.no/browse/EZP-28789

### CODE REVIEW

**Comment by andrerom** [comment]
hmm, LocationValueView does not specify it may return null, would there be possible to skip using LocationValueView for this case? where does the object come form? (where is it created)

**Comment by blankse** [comment]
Here https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php#L83

**Comment by andrerom** [comment]
@bdunogier Should we introduce a `ContentViewLocationLess` or similar class for use with this? Having to check return value of interface looks like patch work.

**Comment by MarioBlazek** [comment]
Why would you want to display Content that hasn't got Location ? Location less Content is there either error or it was moved to trash.

**Comment by blankse** [comment]
I digging deeper. The Content has a location. But it is used a custom controller with call of ViewController::viewContent. There the location param is not set:
https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/MVC/Symfony/Controller/Content/ViewController.php#L308

**Comment by bdunogier** [comment]
`ViewController::viewContent()` is indeed deprecated, and shouldn't be used anymore. The reason for the deprecation is precisely content that doesn't have a location :)

@andrerom I understand the idea, but we actually already have a `LocationView` interface, implemented by `ContentView`... Adding a very specialized View class for this purpose sounds a bit off.

I had actually thought of that before, and we are a bit blocked by interfaces used that way, at this moment. I had been thinking of managing the various aspects of a View by adding a concept of, well `Aspect`. A View could be a collection of those Aspects, and a Location would be one of them.

In the meantime, maybe we could think of something simpler, like `LocationView::hasLocation()`, implemented in `ContentView` ? It kinda belongs in there, given the limitations and use-cases we are facing.

**Comment by andrerom** [comment]
Maybe ´ContentView::hasLocation()´ then? Or new interface for it that we get content view to implement. For me LocationView on it's own implies there is a location, but yeah...

**Comment by crevillo** [comment]
@MarioBlazek ez publish api allows you to create contents without locations. so i don't think is an error. probably you can't do that from the ui, but you can perfectly do that using the api. just pass an empty array as the `locationCreateStructs` param for the `createContent` method and you're done. 

something like
```php
class TestCommand extends ContainerAwareCommand
{
    protected function configure()
    {
        $this->setName('content:create:test');
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        $repository = $this->getContainer()->get( 'ezpublish.api.repository' );
        $repository->setCurrentUser( $repository->getUserService()->loadUser( 14 ) );
        $contentTypeService = $this->getContainer()->get('ezpublish.api.service.content_type');
        $contentService = $this->getContainer()->get('ezpublish.api.service.content');
        $contentType = $contentTypeService->loadContentTypeByIdentifier( 'folder' );
        $contentCreateStruct = $contentService->newContentCreateStruct( $contentType, 'eng-GB' );
        $contentCreateStruct->setField( 'name', 'hello folder' );

        $draft = $contentService->createContent($contentCreateStruct, []);
        $content = $contentService->publishVersion( $draft->versionInfo );
    }
}```

So, i don't see an error in creating content without locations. in fact, that can be used for adding content without generate urls you don't want to be seen :).

**Comment by andrerom** [comment]
> So, i don't see an error in creating content without locations. in fact, that can be used for adding content without generate urls you don't want to be seen :)

Afaik system will generate system url for this case, or at least it should, so there are probably better ways to deal with security ;) But besides that, you are absolutely right, it's API wise possible, and there are use cases for it. In legacy it was for instance used in some cases for relations.

**Pull request merged**
