### PR TITLE
Fixes for the issues causing PHP fatal errors during the static analysis

### PR DESCRIPTION
**Pull request by kmadejski**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | ---
| **Bug/Improvement**| ---
| **New feature**    | no
| **Target version** | `master`
| **BC breaks**      | no
| **Tests pass**     | ?
| **Doc needed**     | no

I wanted to run PHPStan against `ezpublish-kernel`, but during the static analysis, PHP interpreter complained about a few minor issues like incorrect namespaces or missing implementations of interfaces methods. This PR fixes all of them, therefore it's possible to finish PHPStan execution. 
There is a plan for another PRs in the future, regarding the issues found by the mentioned tool.

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by andrerom** [comment]
Can phpstan also detect these?
Would love if we can manage to have a travis job for this on all PR's, to avoid these kind of issues going in unnoticed, also on LTS branches btw.

**Comment by kmadejski** [comment]
@andrerom yes and no. The issues, like these fixed by this PR, cause PHP Fatal errors and stop analysis execution immediately. Therefore, the issue isn't collected by the tool but printed to the stderr instead.

screenshot 2018-11-04 at 10 13 44

> Would love if we can manage to have a travis job for this on all PR's

I'm playing with the proper configuration of the tool. As soon as I manage to configure it I'll prepare a separated PR which introduces the usage of it against the oldest LTS branch.

**Comment by mateuszbieniek** [comment]
Nice PR!

**Comment by andrerom** [comment]
@kmadejski so ready for merge here? :)

**Comment by kmadejski** [comment]
Yes, of course 🙂

**Comment by alongosz** [comment]
Changes are related to tests and REST client, so no QA needed, merging.

**Comment by alongosz** [comment]
Thank you @kmadejski!

**Pull request merged**
