### PR TITLE
EZP-26190: Stash cache not persisted after update to v0.6

### PR DESCRIPTION
**Pull request by andrerom**
issue: https://jira.ez.no/browse/EZP-26190
regression from #1729, Stahs 0.14 does not persist cache on calls to `set()` anymore, you'll need to manually call `save()`.

A cleaner fix would be to change all use of stash to also call `save()`, however with this fix at least our own use of Stash does not need to be adjusted for the time being.

wdyt @bdunogier ?

### CODE REVIEW

**Comment by andrerom** [comment]
As implied above I find it cleaner to rather use the stash lib as it should be so adjusted approach in 6dc98a6, for approach described above see 695288e.

**Comment by andrerom** [comment]
review ping @bdunogier2 @glye @alongosz

**Comment by glye** [comment]
Gotta catch'em all. If you did, +1
As long as the change is manageable I guess it's better to accept it than work around it.

...and remember:
Changes...

**Comment by bdunogier2** [comment]
Is it me, or the PR's description doesn't match the actual code changes ? It says that we wouldn't change our use of stash to always call `save()`, while we _do_ add`save()` after every call.

Either way, I'm fine (+1) with the addition of `save()`, even though the way some long lines are formatted isn't very readable.

**Comment by andrerom** [comment]
@bdunogier2 its all in the comments ;)

ref:
> As implied above I find it cleaner to rather use the stash lib as it should be so adjusted approach in 6dc98a6, for approach described above see 695288e.

**Comment by andrerom** [comment]
Behold a Pokemon *Stash* jar... /cc @glye 

Pokemon Stash jar..

**Comment by emodric** [comment]
@andrerom Current dev-master throws the following error:

Whoops, looks like something went wrong.
FatalThrowableError in ContentHandler.php line 86:
Call to a member function save() on boolean

**Comment by andrerom** [comment]
@emodric this line?:

```php
$cache->set($contentInfo = $this->persistenceHandler->contentHandler()->loadContentInfo($contentId))->save();
```

Do you have the right updates? as in Stash Bundle 0.6.x and Stash 0.14 ?

**Comment by emodric** [comment]
> Do you have the right updates? as in Stash Bundle 0.6.x and Stash 0.14 ?

No, forgot about them :) Sorry for the false positive!

**Comment by andrerom** [comment]
> No, forgot about them :) Sorry for the false positive!

No problem :)

**Pull request merged**
