### PR TITLE
EZP-26186: Some signals are not correctly sent leaving Solr index out of sync

### PR DESCRIPTION
**Pull request by andrerom**
Issue: https://jira.ez.no/browse/EZP-26186

Todo:
- [x] Get existing tests to pass
- [x] CS
- ~~Add additional integration tests~~ Moved to https://jira.ez.no/browse/EZP-26219

### CODE REVIEW

**Comment by andrerom** [comment]
Ready for review @bdunogier2, @bdunogier, @alongosz 


Review notes:
- Some of the changes here is about making the logic a bit more robust in general, and a bit proactive on these kind of issues. So while there are no reports yet of Solr index being out of sync on UserService use, there will be one as soon as someone tries to use it from code, now knowing we for the most part just use ContentService since UserService is, well, somewhat broken by design.
- API Signature here changes, however as the method never returned anything before I don't think this is an issue. And the change provide value for many use cases, same goes for value object changes, these additions will simplify several edge cases for cache, search, (..).
- Elastic Search change is verbatim copy of query from `deleteLocation()` just below, afaik I think this is newer and more correct query which is probably why a trash test failed with the adjusted trash signal logic, before the ES commit.

**Comment by andrerom** [comment]
Ready for review @bdunogier, @alongosz

**Comment by alongosz** [comment]
+1

**Comment by bdunogier** [comment]
+1

**Pull request merged**
