### PR TITLE
Missing type in @property-read documentation

### PR DESCRIPTION
**Pull request by plozmun**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | -
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | master
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

Working with phpstan , i found this issue.

### CODE REVIEW

**Comment by lserwatka** [comment]
@plozmun thank you for your contribution. @alongosz could you check if older branches are affected?

**Comment by ViniTou** [comment]
Also, is this the only affected place? It would be really cool to have all those places solved, right?

**Comment by adamwojs** [comment]
Actually, @lserwatka is right: this PR should be targeted to 6.7 and merged up to master. Could you please @plozmun change target branch to `6.7` (also rebase might be needed)? 😉

**Comment by plozmun** [comment]
@adamwojs rebased . AppVeyor doesn't seem to work 🤔

**Comment by adamwojs** [comment]
Thank you for contribution @plozmun!

**Pull request merged**
