### PR TITLE
Changed usage of deprecated ezpublish.connection alias

### PR DESCRIPTION
**Pull request by bdunogier**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-29422](https://jira.ez.no/browse/EZP-29422) for the deprecation log fix
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | master
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

Removes the `deprecated` key from the definition, as it is not supported for aliases (will error out with Symfony 4.x).

Also changes usages of `ezpublish.connection` to `ezpublish.persistence.connection`.

### TODO
- [x] Wait for tests results.
- [ ] Ask for Code Review.

### CODE REVIEW

**Comment by andrerom** [comment]
Doesn't thins mean they now get DBAL connection instead? Might need to check if console commands pass now.

Otherwise the existing comment might have been wrong.

**Review by alongosz — CHANGES_REQUESTED** [review]
Indeed, AFAICS this will result in direct injection of `DBAL\Connection` which methods are not aligned with our old deprecated database handler. To inject that handler we rather use `@ezpublish.api.storage_engine.legacy.dbhandler`.

But I'm in favor of:
1) Rewriting commands to use `DBAL\Connection` :)
2) Making commands as Services and injecting that connection using DI, which solves the deprecation in getting a service from a PHP code. Ideally something aligned with [this code](https://github.com/ezsystems/ezpublish-kernel/pull/2388/commits/8692b6eab6c046920f311241bb868fae22b5f341#diff-6a914f2f26ca8bea820c97d4d3b7adba) so rebase won't be painful ;)

But if it is too much out of scope, then probably just changing injected service would suffice.

**Comment by bdunogier** [comment]
Is there a conclusion ? :)

Why would one get the handler of a specific storage engine, btw ? You have no certitude that what you get implements anything, do you ? The Legacy SE uses DBAL, but another engine may use something completely different.

It would make much sense that the database connection of an engine is identified by the engine it is for.

**Comment by andrerom** [comment]
@alongosz is off  for vacation now, but if I get him right minimal scope to accomplish:
> Scope reminder: All I want for the time being is to prevent the deprecation notice about deprecated ;)

.. is to instead of changing to `ezpublish.persistence.connection`, just swap it for `ezpublish.api.storage_engine.legacy.dbhandler`.

`ezpublish.persistence.connection` is a different service with pure DBAL instance which we recommend code is migrated to over time as opposed to the deprecated Zeta DB based decorator we have that beberlei introduced which was meant as a temprary step on our move towards using DBAL.


Also if possible move the deprecation over to `ezpublish.api.storage_engine.legacy.dbhandler`, as it's not an alias it should be "fine" or?

**Comment by bdunogier** [comment]
> Also if possible move the deprecation over to `ezpublish.api.storage_engine.legacy.dbhandler`, as it's not an alias it should be "fine" or?

`ezpublish.api.storage_engine.legacy.dbhandler` isn't deprecated, is it ? To my knowledge, what was deprecated was the alias.

**Comment by andrerom** [comment]
> ezpublish.api.storage_engine.legacy.dbhandler isn't deprecated, is it ? To my knowledge, what was deprecated was the alias.

it is, see the classes

>  It doesn't really answer the questions from above, about the persistence connection being dependent on the storage engine, though.

I skipped the question, it's a naming and/or look into history question.

**Comment by andrerom** [comment]
> Is that correct ?

unsure without looking into it, if getConnection() give you DBAL connection then maybe, make sure it's the same class.

**Comment by bdunogier** [comment]
I have checked, it is the same class.

**Comment by alongosz** [comment]
> But anyway, as far as I get it, we should replace in `eZ\Bundle\EzPublishCoreBundle\Command\TestInitDbCommand`

> ```
> $database = $this->getContainer()->get('ezpublish.api.storage_engine.legacy.dbhandler')->getConnection()->getParams();
> ```
> 
> with
> 
> ```
> $database = $this->getContainer()->get('ezpublish.persistence.connection')->getParams();
> ```
> 
> Is that correct ?

Yes. But in the other cases - it will fail, because `Connection` is not the same as `DatabaseHandler`.

> It would make a lot of sense that the database connection of an engine is identified by the engine it is for.

Uhm. Not sure if I understand. `\Doctrine\DBAL\Connection` is an abstract for every storage engine. It should be the only one that is used. But if there's no time to refactor, then minimal scope is indeed replacing service name with `ezpublish.api.storage_engine.legacy.dbhandler`

**Pull request closed without merging**
