### PR TITLE
EZP-30956: fix false positive view parameters detection

### PR DESCRIPTION
**Pull request by ITernovtsiy**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-30956](https://jira.ez.no/browse/EZP-30956)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `6.13 / 7.x`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

Replacement of https://github.com/ezsystems/ezpublish-kernel/pull/2771 

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by ITernovtsiy** [comment]
IMHO, it will be good to remove named parameters implementation starting from eZPlatform v3

**Comment by glye** [comment]
Good addition. Should perhaps be even more rigid? View parameters are defined as `/(param_name)/param_value`. With a regexp we can easily detect that both the name and the value are present. But I don't know if we have a clear definition of what characters are allowed in names and values...

**Comment by gggeek** [comment]
@glye iirc in ez-legacy the view parameters were in fact more flexible than that - even though this is the way they were used in 100% of the apps and extensions that I ever came across.
Not sure if that is important in the context of eZPlatform...

**Comment by ITernovtsiy** [comment]
> Good addition. Could perhaps be even more rigid? View parameters are defined as
> `/(param_name)/param_value`. With a regexp we can easily detect that both the name and the value are present. But I don't know if we have a clear definition of what characters are allowed in names and values...

Agree, the whole implementation of named parameters will look better with proper regexp.
But, this bug is 5 years old and named parameters might be removed in v3. 
So, I decided to just fix download file issue here, and keep named parameters work as they are now.

**Comment by ITernovtsiy** [comment]
Hi @glye, rebased to `6.13`, thanks.

**Pull request merged**
