### PR TITLE
[REST SPEC] Specified Location Search

### PR DESCRIPTION
**Pull request by bdunogier**
> Result from workshop meeting
> Status: WIP

### CODE REVIEW

**Comment by pspanja** [comment]
We have a small inconsistency (not necessarily) here. I discovered it while refactoring Solr engine after merging Content and Location search handlers, and finding out that I can't dispatch API Query conversion to Solr parameters by Query type. The reason for that is [`LocationQuery`](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/API/Repository/Values/Content/LocationQuery.php) extending [(Content)`Query`](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/API/Repository/Values/Content/Query.php). That also means that it is possible to pass `LocationQuery` to `SearchService::findContent()`.

From this specification POV the above means that we can't deduce search type on the server. That would be most problematic in future implementation of PHP REST client, where one would make a call to `SearchService::findContent()` with `LocationQuery` and receive Locations as a result.

But, rather that changing this specification I would change the API by removing `LocationQuery` extension of `Query`. Both can extend common abstract class, which we would not hint in `SearchService`. What do you think?

**Comment by andrerom** [comment]
@pspanja this is basically like specified here for REST, that a new ContentQuery is introduced.

**Comment by pspanja** [comment]
@andrerom Yes, exactly. For the moment in https://github.com/ezsystems/ezplatform-solr-search-engine/pull/7 I went with dispatching query conversion by called method, which also works fine.

**Comment by bdunogier** [comment]
Specification cherry-picked to #1364.

**Pull request closed without merging**
