### PR TITLE
Fix EZP-24397: Implement FieldDefinition form mapper for ezinteger

### PR DESCRIPTION
**Pull request by glye**
Default values must be null, not false. Required for https://github.com/ezsystems/repository-forms/pull/10
Thanks @lolautruche

https://jira.ez.no/browse/EZP-24397

### CODE REVIEW

**Comment by lolautruche** [comment]
+1

**Comment by glye** [comment]
Added fix for the same inconsistency in the type.

**Comment by glye** [comment]
Fixed the test which depends on this.

**Comment by pspanja** [comment]
+1

**Comment by lolautruche** [comment]
You're ready to merge now I guess :wink:

**Pull request merged**
