### PR TITLE
EZP-19123: Missing SQL to copy ezuser.login to login_normalized

### PR DESCRIPTION
**Pull request by andrerom**
Also better document the issues that can turn up as part of the schema change.

ping @crevillo @emodric

### CODE REVIEW

**Comment by emodric** [comment]
For MySQL, you could probably use `AFTER login` too.

I don't know PostgreSQL equivalent.

**Comment by emodric** [comment]
Otherwise +1

**Comment by crevillo** [comment]
a comment: as alter is done first (and it needs to be done first) you can get a ```ERROR 1062 (23000) at line 10: Duplicate entry '' for key 'ezuser_login'``` in a already existing installation because you will have at least two rows. Maybe we should add a note about it so users don't get in panic. 

otherwise +1

**Comment by andrerom** [comment]
@crevillo Not sure I follow, won't this happen on 3rd line when index is swapped?

**Comment by andrerom** [comment]
> For MySQL, you could probably use AFTER login too.

Thanks, added it.

> I don't know PostgreSQL equivalent.

There is none, so skipping it there.

**Comment by crevillo** [comment]
@andrerom forget it. you're right. this happened before doing the alter in table to set normalized values. Before this patch in other words.

**Comment by andrerom** [comment]
> @andrerom forget it. you're right. this happened before doing the alter in table to set normalized values. Before this patch in other words.

yes, this was indeed an issue before this :)

**Comment by andrerom** [comment]
thanks for the reviews @emodric and @crevillo

**Pull request merged**
