### PR TITLE
Fix EZP-24915: Solr Search Engine repository structure cleanup

### PR DESCRIPTION
**Pull request by pspanja**
#### This PR resolves https://jira.ez.no/browse/EZP-24915

Corresponding PRs:
* https://github.com/ezsystems/ezplatform-solr-search-engine/pull/24
* https://github.com/ezsystems/ezpublish-platform/pull/18
* https://github.com/ezsystems/ezplatform/pull/53
* https://github.com/ezsystems/ezpublish-community/pull/250

Only Travis configuration is updated here.

### CODE REVIEW

**Comment by pspanja** [comment]
Review ping @andrerom @bdunogier @lolautruche

**Comment by andrerom** [comment]
+1

**Comment by andrerom** [comment]
But we need to update meta repos for this as well.

**Comment by pspanja** [comment]
Yes indeed, I'll open missing PRs.

**Comment by pspanja** [comment]
> But we need to update meta repos for this as well.

Opened PRs:
* ezsystems/ezpublish-platform#18
* ezsystems/ezplatform#53
* ezsystems/ezpublish-community#250

**Comment by pspanja** [comment]
Fixed failure caused by XmlText -> RichText converted fixture in https://github.com/ezsystems/ezpublish-kernel/commit/9ce75b3d1eda17ba741efbcfa63456754d3832f8

**Pull request merged**
