### PR TITLE
EZP-24023: Add the DefaultSiteAccess URIElement on the fly

### PR DESCRIPTION
**Pull request by Plopix**
JIRA: https://jira.ez.no/browse/EZP-24023

Hi,
I'm not sure that is the best way to do that but I assumed that if we are on the URIElement only then we could add the DefaultSiteAccess on the fly.
Maybe we should manage for the Regex and the Port one.

=> More infos on JIRA.

++

### CODE REVIEW

**Comment by Plopix** [comment]
Maybe it's not the good way to do, there is a "double/slash" // with this solution.

Anyway it could help ;-)

Let me know

**Comment by andrerom** [comment]
The router is not supposed to have intimate knowledge about the specific matcher.
So think we need to get back to the issue here and define what functionality is needed here.

**Comment by lolautruche** [comment]
Yes, @andrerom is right. I can see the point and I think the issue is valid. The main reason for this issue is that there is no matcher for the default SiteAccess. Not sure how we can fix that (yet).

**Comment by lolautruche** [comment]
Sorry @Plopix but we can't accept this patch as is :-)

**Comment by Plopix** [comment]
Don't be sorry I get it and I agree it's a bit strange to hard instanciante the MapURIMatcher... but it was maybe a part of the solution.

Thanks for your feedback and I'll keep an eye on the JIRA issue.

**Pull request closed without merging**
