### PR TITLE
Fix EZP-26963: IO Url prefix not working with a host

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-26963

This patch makes it possible to define an `url_prefix` with a host
[as documented](https://doc.ez.no/display/EZP/Binary+files+URL+handling#BinaryfilesURLhandlingUsingastaticserverforimages).

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @bdunogier @yannickroger

**Comment by lolautruche** [comment]
@andrerom As long as it is backported to 5.4, I'm fine with it 😉 
Should I do it?

**Comment by andrerom** [comment]
> Should I do it?

pretty please :)

**Comment by lolautruche** [comment]
Done here

**Comment by lolautruche** [comment]
OK Should be fine now. You might need to restart Travis.

**Comment by yannickroger** [comment]
@lolautruche could you, if you have time, also base your branch on 6.7. QA now tests pull request before merging so it need an up to date and relevant branch.

If you don't have time, I'll just open another PR in order to have that.

**Comment by lolautruche** [comment]
@yannickroger Done

**Comment by bdunogier** [comment]
Well, except for the conflict of course... :)

**Pull request merged**
