### PR TITLE
Undefined index timestamp when using Adapter/AwsS3

### PR DESCRIPTION
**Pull request by ostark**
In some cases $info['timestamp'] is not defined, e.g if 'LastModified' is not set for an S3 object:
https://github.com/thephpleague/flysystem/blob/0.5.12/src/Adapter/AwsS3.php#L486

### TODO
- [ ] Rebase on top of latests master
- [ ] Fix CS
- [ ] Unit test coverage `eZ/Publish/Core/IO/Tests/IOMetadataHandler/FlysystemTest.php`
- [ ] Create JIRA issue. *Ideally Should include some info on reliable way to reproduce.*
- ~~Functional testing  *(thats more of a eZ responsibility, along with maintaining it once it is merged in)*~~
- ~~Update Flysystem *(Followup for someone else: [EZP-25676](https://jira.ez.no/browse/EZP-25676))*~~

### CODE REVIEW

**Comment by andrerom** [comment]
Can't see parent commits anymore on Github here, but I think you as missing 0ad413fe678387912e8891f6474064faf47f8793 and such from the branch to get it to properly running tests. So please rebase on top of latests master *(or rebase on top of 6.1 and reopen PR so we can backport)*, you can squash your commits while at it.

**Comment by andrerom** [comment]
Could you also take care about the remaining cs issues?

+1 from me with that, and until we have some doc on how to rebase (ping @yannickroger) we can manage to cherry pick to new branch for you and apply to 6.1/6.2/master  /wdt @bdunogier

**Comment by bdunogier** [comment]
Good one, thank you @ostark. If you could cover this case in `eZ/Publish/Core/IO/Tests/IOMetadataHandler/FlysystemTest.php`, it would be even better.

Once done, please squash all your commits, and we should be good.

> +1 from me with that, and until we have some doc on how to rebase (ping @yannickroger) we can manage to cherry pick to new branch for you and apply to 6.1/6.2/master /wdt @bdunogier

I'll take care of the rebase if needed, no problem. If you want to give it a try, @ostark, here's the very short version:
- from your branch, `git rebase --interactive --onto 6.1 master`
- close current PR
- push branch & open new PR with it

> Side: Ideally we should have

:arrow_right: jira.ez.no ? ;-)
But yes, we should.

**Comment by ostark** [comment]
Thanks for taking care, @bdunogier @andrerom 

Maybe my fix is not the best solution, since it fixes just the symptoms.
After some hours of debugging found out why it happens:

In eZ\Publish\Core\IO\IOMetadataHandler::load() you try to fetch the metadata for the recently uploaded file by calling League\Flysystem\Flysystem::getMetadata(). getMetadata() returns cached data if possible. And it is! This cached data has no Last-Modified 'timestamp', since it is the response of the PUT call. The normalizeObject of the response gets cached, at least in flysystem ^0.5. Flysystem ^1.0 looks completely different.

Cache put happens here: https://github.com/thephpleague/flysystem/blob/0.5.12/src/Filesystem.php#L154

See the difference of the S3 API response headers:

 * HEAD: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html#RESTObjectHEAD-responses-examples-sample-response-to-a-versioned-head-request

* PUT: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html#RESTObjectPUT-example1

**Comment by phalasz** [comment]
This fix would help me out a lot. So +1

**Comment by bdunogier** [comment]
I know that you're affected by it, @phalasz. A +1 would help much more if you could confirm that you have actually tested the patch, and that it worked for you.

**Comment by phalasz** [comment]
Yes you are right @bdunogier, that is what I should have done in the first place.

I have since applied the patch and it allows publishing content with images that are correctly uploaded to S3.

**Comment by andrerom** [comment]
But what about comment above that this just fixes the symptoms? Do we aim to use this for backports and update flysystem for master as means to fix it here?

**Comment by phalasz** [comment]
@andrerom I would prefer your suggestion of getting this fixed in current versions and update flysystem in future versions.

**Comment by sroze** [comment]
Guys, 28 days after the pull-request, this patch (for what I consider a critical issue for non-monolith architectures) is still not merged. What can we do to help you speed-up that process and going forward with this eZ Platform?

**Comment by ostark** [comment]
+1 @sroze thanks for pushing this topic

**Comment by andrerom** [comment]
> Guys, 28 days after the pull-request, this patch (for what I consider a critical issue for non-monolith architectures) is still not merged. What can we do to help you speed-up that process and going forward with this eZ Platform?

Take one of the open jobs at eZ so we have more folks to review, cleanup branches like these, and add test? :)

**Comment by andrerom** [comment]
ping @ostark will you be able to cleanup the patch?
ping @bdunogier anything to add here? :)

**Comment by bdunogier** [comment]
Not much to add no. 

I'll add the two remaining tasks to the issue for easier tracking.

**Comment by bdunogier** [comment]
I'm taking this over. Given that Flysystem itself has a condition where the `timestamp` key might not be set, not having a reproduction method is not a big issue. Will create the JIRA issue.

I'll fix the CS and add the unit test.

Thank you @ostark.

**Comment by ostark** [comment]
Thank YOU @bdunogier

**Pull request closed without merging**
