### PR TITLE
EZP-28243: Purge type using service id does not work

### PR DESCRIPTION
**Pull request by vidarl**
> Issue: https://jira.ez.no/browse/EZP-28243

1. Fixes so it is possible to use this setting as documented in semantic config help text.
2. Make it possible to add plugin system for ezplatform-http-cache in order to add Fasly support: https://github.com/ezsystems/ezplatform-http-cache/pull/19

### CODE REVIEW

**Comment by vidarl** [comment]
So, may I just remove the offended test which complains since we no longer throws exception on unknown purge_types ( this is instead done by ezplatform-http-cache)

**Comment by andrerom** [comment]
Do you need this on older releases as well? _(thinking cases where people don't use ezplatform-http-cache also)_, or do we aim to require ezplatform-http-cache? _(ok with me)_

**Comment by vidarl** [comment]
I basically need this in every version where we are going to support fastly.... Fastly support will require ezplatform-http-cache

**Comment by vidarl** [comment]
> If we go with this, then yes. But ideally we should somehow still throw for people not using ezplatform-http-cache

So, this is heading for 1.13.0 where ezplatform-http-cache is going to be enabled by default.
Should I still write a check if the ezplatform-http-cache bundle is installed?

**Comment by andrerom** [comment]
@vidarl If I read the code right here, assuming Fastly Bundle is registered before Core _(assuming that can even work)_, then setting purge type to a valid service like `ezplatform.http_cache.purge_client.fastly` would make it pass here right?

**Comment by andrerom** [comment]
> Update : we'll need this for 2.0.0 and 1.13.0

Actually v1.12.1 and up.

**Comment by alongosz** [comment]
We should merge #2123 so you can run `composer fix-cs` before pushing ;)

**Comment by vidarl** [comment]
hehe. I am not against #2123....

**Comment by vidarl** [comment]
Github won't have me review and approve this PR as I created it.
But I do approve...

My commits should be removed before merged though

**Comment by andrerom** [comment]
> My commits should be removed before merged though

we always squash now

**Pull request merged**
