### PR TITLE
EZP-28705: As a Maintainer I want PostgreSQL script to update existing sequences

### PR DESCRIPTION
**Pull request by alongosz**
| Question  | Answer
| ------------- | ---
| **JIRA issue** | [EZP-28705](https://jira.ez.no/browse/EZP-28705)
| **Bug fix** | yes
| **New feature**  | no
| **Target version** | 7.0
| **BC breaks**    | with Legacy <5.x software using the same DB |
| **Tests pass**   | yes

ezpublish-kernel 7.0 introduced new sequence naming `<table>_<column>_seq` for PostgreSQL schema, however the script updating old names was missing.

The change is required in order to use uniform logic to create schema using Doctrine Schema Tool.

**TODO**
- [x] Create PostgreSQL upgrade script updating sequence names.
- [x] Create PR with fix for ezpublish-legacy.
- [x] Request review when ready.
- [x] Fix file name after switching to `master`.

### CODE REVIEW

**Comment by andrerom** [comment]
Any dependencies for this (like legacy changes or something ;) )

**Comment by andrerom** [comment]
Is this ready for review?

**Comment by andrerom** [comment]
> @andrerom yes please :)

ok, it should go into master. And can we adapt it for 7.1 then? or if it does not make it 7.2.
into 7.1 implies we should adapt legacy for  a 18.03 release as mentioned on your legacy PR, 7.2 would rather imply a 18.06 release with this.

I think I prefer sooner rather then later as the inconsistencies will hit people upgrading with postgres.

**Comment by alongosz** [comment]
@andrerom the thing is that `7.0` introduces the change in sequence naming, that's why bugfix applies to `7.0`.

**Comment by wizhippo** [comment]
@alongosz The script ran fine.

**Comment by andrerom** [comment]
@alongosz The problem is that people look for db update scripts to run, and if they are already on v2 there is a chanche they will miss this as they are already on 7.0.x

So in sum: Target version needs to be a unreleased version, so alternative to 7.1.0 is 7.0.3, but unsure if we will make that release as then 7.1 will be out already.

**Comment by alongosz** [comment]
Ok, that's convincing point :)

**Pull request merged**
