### PR TITLE
implement getName method in FieldType\Selection\Type

### PR DESCRIPTION
**Pull request by Erilan**
https://jira.ez.no/browse/COM-19864

### CODE REVIEW

**Comment by SylvainGuittard** [comment]
Thanks @Erilan 
Jira issue moved to EZP project: https://jira.ez.no/browse/EZP-24861

**Comment by andrerom** [comment]
@pspanja pov?

**Comment by antoligy** [comment]
This doesn't match the legacy behaviour, wherein the value is set as the string value of the selected values.

**Comment by bdunogier** [comment]
Same than @antoligy :

**Comment by bdunogier** [comment]
Hi. After discussing this feature, we have decided to close the pull-request. A new epic has been created on JIRA, and it will be prioritized in the future.

The plan is to update the SPI to make it possible to use external content (for Relation) / field definition properties (for Selection) when returning the name.

**Pull request closed without merging**
