### PR TITLE
Fixed PHPDoc for better programming

### PR DESCRIPTION
**Pull request by kemoc**
Hi, it's my first PR i hope it is done correctly.
I have started from something simple and important for me. 
Like as title PHPDoc was outdated, it disturbed fast programming.
It's not all updates of PHPDoc. If this part will come out correct i will create next PR.

### CODE REVIEW

**Comment by andrerom** [comment]
Hi,

thanks for contributing!

some initial review notes, could you:
- omit the change from `mixed` to `string|int`, we might want to do that but it will then have to be all over the place so for sanity should be separate PR _(and to avoid conflicts you should do it after the remaining changes here gets it's final form)_
- rebase your PR against master so it will be for 1.10 if all goes well :)

**Comment by Nattfarinn** [comment]
I'm not a fan of `int|string` (not a fan of `mixed` either) in above use cases. PHP is dynamic, weakly typed language and variable type doesn't really matter. Assumed variable value type matters. If it's integer (regardless of form: `1`, `"1"`), it should be `int`. `int|string` suggests dual responsibility and intentional use of `string` in some cases.

**Comment by kemoc** [comment]
@Nattfarinn ok, i agree with you. On slack @bdunogier told me  that some storage engines be able to return '<integer>'. Please

**Comment by andrerom** [comment]
@Nattfarinn It's documented as mixed as it might change to uuid or similar in the future, hence string and not int, today it is for the most part int.

**Comment by kemoc** [comment]
I did rebase to master but probably in wrong place. I think this PR is to reject.

**Comment by andrerom** [comment]
@kemoc yes, two suggested ways to fix it:
- Use `git rebase -i master` and delete any line which is not your commit _(hit `d` in vim to do this)_
- Checkout _(clean)_ master, then create new branch based on that, and cherry pick the commits you want to take with you with `git cherry-pick <sha1> [...]`

Always verify what you have with `git diff master..` and `git log master..` before you push, in cases like this you should not end up with any merge commits for instance, and only your own commits. If you ever need to go back and try again then there is always `git reset --hard origin/<branch>`, even if you push you can still go back by reseting to right place in git's "reflog".

**Comment by alongosz** [comment]
Closing in favor of #1984

**Pull request closed without merging**
