### PR TITLE
Fix EZP-23967: Refactor Repository and its services for main Search Handler implementation

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-23967, a sub-task for https://jira.ez.no/browse/EZP-23940

The PR is based on #1156 and will be reopened against master when #1156 is merged.

Followup: https://jira.ez.no/browse/EZP-23968

Note:
* semantic configuration has its own issue: https://jira.ez.no/browse/EZP-23471
* dynamic storage dependencies will be implemented in a following sub-task
* BC notes will be added in a parent issue wrap-up

### CODE REVIEW

**Comment by lolautruche** [comment]
Why keeping `legacy` in search service names (e.g. `ezpublish.spi.search.legacy_elasticsearch`)? Are implementations still bound to legacy somehow?

Other than that, +1

**Comment by pspanja** [comment]
Yes, they still are. It will be fixed in one of the following sub-tasks.

**Comment by andrerom** [comment]
@lolautruche legacy SE.

**Comment by lolautruche** [comment]
@andrerom That's what I meant :wink:

**Comment by andrerom** [comment]
> Yes, they still are. It will be fixed in one of the following sub-tasks.

Cool, missing aliases or something to use? Maybe we should sync on the naming for those :)

**Comment by pspanja** [comment]
@andrerom 

Yes, my plan is to define them as services that use main storage handler (`ezpublish.api.persistence_handler`, aliased to Cache storage or a factory in MVC) as a factory, in a separate `shortcuts.yml`. The same can be done for Repository services, which now use a separate factory. I'll have a PR just for that, so maybe best to sync on it when it is up.

**Comment by andrerom** [comment]
> ezpublish.api.persistence_handler

This is exactly the reason to sync, cause we already have something like ezpublish.spi.persistence_handler and ezpublish.api.storage_engine.

This is domain language, as "storage engine" implies something more, namely the actual persistence storage as opposed to for instance cache. But the whole mixture of spi/api makes it messy.

**Comment by bdunogier** [comment]
> BC notes will be added in a parent issue wrap-up

That's a new one. Love it :-)

**Comment by bdunogier** [comment]
The domain language issue is fixed by the sub-tasks, right ?

**Comment by pspanja** [comment]
@bdunogier yes, it is fixed here: https://github.com/ezsystems/ezpublish-kernel/pull/1167

**Comment by pspanja** [comment]
Reopened against master, closing in favour of https://github.com/ezsystems/ezpublish-kernel/pull/1170.

**Pull request closed without merging**
