### PR TITLE
Fix EZP-26482: add ezdfsfile to MySQL schema.sql

### PR DESCRIPTION
**Pull request by bdunogier**
> [EZP-26482](https://jira.ez.no/browse/EZP-26482)

### TODO
- [x] Move to its own file ? `data/mysq/dfs_schema.sql` ?
- [x] Make sure installer installs the separate file

### CODE REVIEW

**Comment by bdunogier** [comment]
Ping @glye @andrerom.

Do we want to backport this ? If yes, do we want to add dbupdate files ? I'd say no, since those who wanted cluster should have it by now, and might not want a new table in their database.

**Comment by gggeek** [comment]
I vote -1 for having it in the same file as the ez db.

The idea is that the db connection for cluster and content have to be separate to insure transactions and rollbacks - at least it was so in legacy...
Having the table in the main schema makes it too easy for end users to reuse the same db connection for both...

**Comment by gggeek** [comment]
ps: btw: don't we have 2 tables for cluster now, not just one ?

**Comment by glye** [comment]
Valid points from @gggeek. I'm leaning towards "own schema file". Then it won't be installed by the install command which is good for those who don't clusterize, and also for those who do, if @gggeek is right about using a separate db.

Also, if separate schema file it's a little easier to install the tables on demand, in the case where a separate db has been configured but the tables are missing. Edge case, though.

No to dbupdate files.

**Comment by bdunogier** [comment]
> ps: btw: don't we have 2 tables for cluster now, not just one ?
Nope, it's only one with platform: the "cluster" doesn't have anything to do with cache (stash takes care of that, whee).

**Comment by gggeek** [comment]
whee :-D :-D

**Comment by bdunogier** [comment]
And here we go.

**Comment by andrerom** [comment]
Looks better, updated todo's ;)

**Comment by glye** [comment]
I thought the point was to *not* have the installer install this, since a) non-clusters don't need it, and b) clusters should install it in a separate db ..? If we're going to autoinstall it, it might as well go in the same file.

**Comment by andrerom** [comment]
> I thought the point was to not have the installer install this, since a) non-clusters don't need it, and b) clusters should install it in a separate db ..? If we're going to autoinstall it, it might as well go in the same file.


yes and no :) The original request from QA was to simplify install of cluster. and the ultimate way to do that is to automate it as part of installer making sure the table is always there for when it is needed.

And with separate file we can easily document how you may add the schema to another database _if you want for reason x, y ,z_ and reconfigure eZ Platform for it. But it would then be a _optional_ step, as opposed to a required one which won't really solve the original request.

Does that make sense?

**Comment by glye** [comment]
> simplify install of cluster

Ok, then it boils down to this: If we recommend using separate DBs, then auto-install is only simplifying the wrong setup. If single DB is OK in some cases, then I'm +1. So what is the current recommendation?

**Comment by bdunogier** [comment]
Single DB is okay for dev and testing. So I'd lean towards @andrerom's position: do both.

One option in a slightly different lane: we could warn when the repo & cluster databases are the same in prod env. What do you think ?

**Comment by glye** [comment]
Ok given the dev/testing case, provided this is well doc-ed, and a warning is given as you suggest.

**Comment by andrerom** [comment]
👍  But I would say the warning belongs in a separate tool that checks system up against recommended values, as was discussed back when we started making collectors in support tools as a possible `milestone <later>` for it.

**Comment by bdunogier** [comment]
Made the Platform CleanInstaller import the DFS schema in addition to the kernel one.

**Comment by bdunogier** [comment]
Good points, @andrerom. Ping @clash82 / @SylvainGuittard about the above.

**Comment by bdunogier** [comment]
@glye second approval ?

**Comment by bdunogier** [comment]
Sent to QA.

**Pull request merged**
