### PR TITLE
Upgrade http-cache-bundle to ~1.3

### PR DESCRIPTION
**Pull request by janit**
I get hit with this: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/238

@dbu closed this on Sep 30

### CODE REVIEW

**Comment by dbu** [comment]
so 239 is part of 1.3.4 so it should be fine, no? or are you saying that
it actually is not fixed?

**Comment by janit** [comment]
It should be fixed in 1.3.x, but my install with this was still using 1.2.x

**Comment by dbu** [comment]
ah sorry, i should have read the content of the pull request :-)
looks sane to me to upgrade.

**Comment by emodric** [comment]
@janit Why not just do `composer update friendsofsymfony/http-cache-bundle`?

Current `composer.json` with `~1.2` does not limit the lib to 1.2.x.

**Comment by bdunogier** [comment]
> @janit Why not just do composer update friendsofsymfony/http-cache-bundle?

My croatian friend is right. I vote for closing the PR (sorry @janit). We _support_, but don't _require_ it, no need to change it.

**Comment by andrerom** [comment]
Closing for now as we did 03374d5cb4e928de3e6a0b8c1605bb9acec7b3fffor the time being, once that has been solved we'll bump minor past version that has fix for it.

**Pull request closed without merging**
