### PR TITLE
Display real template names in debug output

### PR DESCRIPTION
**Pull request by emodric**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | No need?
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `6.x`/`7.x`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

When using eZ Design Engine, sometimes it is very hard to find which templates are exactly used to render the page, since only logical name is displayed in HTML output.

This changes the output to display the real path to the used template.

Before:

image

After:

image

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by emodric** [comment]
Ping @andrerom @alongosz

**Comment by emodric** [comment]
Don't see why not?

**Comment by alongosz** [comment]
> Don't see why not?

This rather looks like a feature. 6.7 is now maintained for bugfixes only. But as I've said, this is small change affecting developer experience in a good way, so we might (we've made exceptions in the past anyway).

**Comment by emodric** [comment]
Ah, okay. I thought you meant technically.

**Pull request merged**
