### PR TITLE
Feature/easy override view builder, content view, block view

### PR DESCRIPTION
**Pull request by kemoc**
Block view, content view builders have been make easy to override. Content view, block view classes names have been move to YML. Kept backward compatibility.

### CODE REVIEW

**Comment by kemoc** [comment]
On my PC works well:P
I have looked at the travis details and it's look like you have wrong configuration / missing class? in test with SOLR, other builds are OK.

**Comment by kemoc** [comment]
@bdunogier 
hi, please check this PR, something wrong is in Travis build with PHP7 and SOLR 6.4

**Comment by andrerom** [comment]
> hi, please check this PR, something wrong is in Travis build with PHP7 and SOLR 6.4

this is irrelevant to this PR, nothing to see there _(and it has already been fixed)_.

Reason why I added @bdunogier as reviewer is for him to extract use case, secondly perhaps give input on how that should be solved, as this might not be the way.

So maybe you can expand a bit on the use case for this @kemoc? Aka why do you need this? What does it solve? did you consider alternative ways to solve what the user is asking you to do with the system? Also, expand on what the user ask you do to so we know the context.

**Comment by andrerom** [comment]
Closing, but if you see this @kemoc, please share use case with us so we can see how we can make something like this possible. Is your logic for instance tied to content type or something else?

**Pull request closed without merging**
