### PR TITLE
Fix EZP-20786: Update content via Public API modify publication and modification date

### PR DESCRIPTION
**Pull request by dspe**
Jira open here: https://jira.ez.no/browse/EZP-20786

### CODE REVIEW

**Comment by tharkun** [comment]
This feature needs to be solved. As more and more legacy website will migrate to full stack, we'll have to deal with this issue.
Because of it, any update of an object results in the loss of the creation date. It may be a problem when dealing with creation date of users, because we won't know any more when the user signed out...

**Comment by andrerom** [comment]
yes, well what needs to be done is quite clear now:
- not introduce new logic which uses VersionInfo->creationDate
- change to use optional struct instead of int, like:
```php
class ContentPublishStruct extends ValueObject
{
    /**
     * If set this value overrides the publication date of the content, otherwise current time during publishing.
     *
     * @var \DateTime|null
     */
    public $publishedDate;

    /**
     * If set this value overrides the modification date of the content, otherwise current time during publishing.
     *
     * @var \DateTime|null
     */
    public $modificationDate;
}
```

**Comment by lolautruche** [comment]
Can this be merged or closed?

**Comment by andrerom** [comment]
Yes the issue was fixed by Edi in https://github.com/ezsystems/ezpublish-kernel/commit/812dc9fe70e5b40a5cfd62aea9516093360178c3

But being able to set publishing time is still interesting for a few other use cases, so opened new issue for that: https://jira.ez.no/browse/EZP-26064

**Pull request closed without merging**
