### PR TITLE
[WIP] Possibility to specify 'query' param name

### PR DESCRIPTION
**Pull request by andrerom**
To be able to do several queries per view (menu, side bars, ..).
In this shape you'll need custom QueryController to be able to do it.

Does it make sense to make this configurable @bdunogier ?

### CODE REVIEW

**Comment by bdunogier** [comment]
I had something like that in mind: use sub-blocks below "query" one, where each block's name would be used as the `assign_results_to` option:

```
full:
  blog:
    controller: "ez_query:locationQueryAction"
    template: "content/view/full/blog.html.twig"
      match:
        Identifier\ContentType: "blog"
        params:
          children:
            query_type: 'LocationChildren'
          related_items:
            query_type: 'RelatedItems'
```

This would run two queries, and assign the results to `children` and `related_items`.

What bothers me overall is that this encourages "real fetches", and mixing up of items. It would be fairly easy to run a sub-request, maybe with another view type, and have a dedicated, cachable, block for each of those.

What do you think ?

**Comment by andrerom** [comment]
> and have a dedicated, cachable, block for each of those.

not following, what did you think of here?

**Comment by bdunogier** [comment]
> It would be fairly easy to run a sub-request, maybe with another view type, and have a dedicated, cachable, block for each of those.

Rephrasing.

Instead of assigning `related_items` and `children` to variables, using a query, the alternative would be to do two render calls in the template:

```twig
{{ render_esi( controller( 'ez_content:viewAction', {'contentId': content.id, 'viewType': 'children'} )) }}
...
{{ render_esi( controller( 'ez_content:viewAction', {'contentId': content.id, 'viewType': 'related_items'} )) }}
```

It adds two view configuration blocks (one for `children`, one for `related_items`), but it allows for thiner caching, and makes each configuration block simpler than the one above.

**Comment by andrerom** [comment]
Closing as approach above would much easier allow for reuse of logic, and won't end up having to much query logic in config tied to logic depending on it in templates.

**Pull request closed without merging**
