### PR TITLE
Update Type.php

### PR DESCRIPTION
**Pull request by akorti**
implement getName method returning value

### CODE REVIEW

**Comment by andrerom** [comment]
I guess we should accept this and #1421 as temporary workarounds to avoid the exceptions, unless we get around to change the api.

**Comment by bdunogier** [comment]
We won't be able to improve this right now, afaict. This approach removes the exception, it is a step forward.

**Comment by bdunogier** [comment]
Given that #1605 is open, do we still want to merge this as a temporary improvement, @andrerom

**Comment by andrerom** [comment]
> Given that #1605 is open, do we still want to merge this as a temporary improvement, @andrerom ?

we could *(and if so preferably also for selection and relationlist)*, but it is breaking tests

**Comment by bdunogier** [comment]
Closing as `getName()` support is added in the 1.3 release.

**Pull request closed without merging**
