### PR TITLE
EZP-24047: Allow skipping count query when using SearchService against db

### PR DESCRIPTION
**Pull request by andrerom**
https://jira.ez.no/browse/EZP-24047
see: http://share.ez.no/forums/ez-publish-5-platform/about-searchservice-and-count-queries

Test ping @crevillo, using  ~~$fieldFilters['perform_extra_count'] = false~~ `$query->performCount = false`

### CODE REVIEW

**Comment by crevillo** [comment]
Thanks @andrerom! :)
some comments:
 * It seems this will work perfectly for ```findContent```, but what about ```findLocations```? Actually it seems that function doesn't have the $fieldFilters params that findContent has. 
* Also, i guess there is no other way go and that this will indeed save some queries to the database, but as you said in the post, in Solr and ElasticSearch, count and elements will be obtained in a only query. So, even if passing 'perform_extra_count' as false, it will be useless, right? 
Or well, we can even return count null in those cases too...

**Comment by andrerom** [comment]
findLocations is missing so far in this PR, as I didn't want to change the API just yet.
Is it findLocations you mainly need this for?

**Comment by crevillo** [comment]
I can live without it. Just curious about :).

**Comment by bchoquet-heliopsis** [comment]
Just asking, what about some kind of proxying instead of an additional parameter ? As @crevillo points out, it will be irrelevant with a non sql engine.

**Comment by andrerom** [comment]
proxying?

**Comment by crevillo** [comment]
i was gonna ask the same thing...

**Comment by andrerom** [comment]
most likely your referring to making the value object fat allowing it to lazy load the parameter, we don't do that currently, we let value objects stay value objects.

**Comment by crevillo** [comment]
as said, for non sql engines even if the query will return the total count we could just return count = null in the valueObject if doCount is passed as false... 
looks a bit dirty, but i cannot find another way to pass that param if we need to do it from the searchService...

**Comment by andrerom** [comment]
> looks a bit dirty

workarounds are dirty, this is one of them

**Comment by crevillo** [comment]
so, +1 to what has been done on my side, but i wil back here to take care of the findLocations too.

**Comment by bchoquet-heliopsis** [comment]
I was indeed refering to lazy loading but I hoped a more elaborate answer than "because we don't" ;)
I would have guessed that if you plan to make SQL non-default, you'd prefer to place the dirty bits there rather than bloating the whole API with parameters, I'm sure this is a thought out decision and I was curious about the reasons behind it.

**Comment by andrerom** [comment]
Being able to var dump, debug, serialize, cache the value objects are the main reasons, moist vivid DDD practitioners would probably add more arguments to the list.

**Comment by bchoquet-heliopsis** [comment]
Well if you put it like this :)

**Comment by andrerom** [comment]
;)

**Comment by andrerom** [comment]
@pspanja Discussed with @bdunogier and @lolautruche about maybe rather putting this option on the Query object (avoid having to add it to function signature all around). A couple of options where thrown around, ->options bit field or a array has so it can be extended by search engine, we ended up slightly leaning towards last option for the Search Engine flexibility, however on the downside of course not a strongly typed or hinted alternative (so no IDE autocomplete).

**Comment by pspanja** [comment]
Bitmask would be too limiting for stuff that don't fit in switch-like control (for example ES scroll/scan or Solr cursor). So for me it is either object or hash. Object can still provide for extensibility -- engine specific options class could inherit from the base one. I think I'm leaning a bit towards the object option, if only for hinting it would provide.

**Comment by pspanja** [comment]
Thinking about REST, hash would better fit there.

**Comment by bdunogier** [comment]
Hmmm...

I'm "really" (won't keep me awake) bothered by the lack of self-documentation of a hash. I was actually thinking of Option objects of some sort. It's a bit more to type, but easily extensible. And as a bonus, we can make options a bit more complex if applicable.

**Comment by pspanja** [comment]
@bdunogier Fine with me, we will just have to make sure it can serialize to a hash.

**Comment by andrerom** [comment]
@bdunogier but as the options are engine specific, you won't really get any autocomplete options by typing `$query->(searchEngineOptions|options)->`.

To make matters worse this will kind of force the developer to init a options class from specific engine (currently from the 'private' Core namespace) to get autocomplete, and then he will only be able to hint for one engine at a time :(

**Comment by andrerom** [comment]
@pspanja / @bdunogier Instead went for flag on Query as it looks better, gives autocomplete doc and could not remember any specific search engine stuff we want to expose directly on Query in the first place.

So open for review, but test adjustments missing.

**Comment by bdunogier** [comment]
There is a risk that it will look messy if we need more options. But since we don't need anything else now, let's not overengineer.

+1 on the approach.

**Comment by pspanja** [comment]
Looks good, +1.

**Pull request merged**
