### PR TITLE
EZP-25792: Fix index sub-items after main location delete

### PR DESCRIPTION
**Pull request by galileo**
Integration test that are required for a solar bundle which you can find here:

https://github.com/ezsystems/ezplatform-solr-search-engine/pull/46

### CODE REVIEW

**Comment by bdunogier** [comment]
Do you expect the test to pass, or does it have requirements on external packages ?

**Comment by galileo** [comment]
Trully said I don't know why this tests are not passing, I just added some integration tests in this PR and there are not passing test with reference passing in php 7 and now I got some date issues.

Still don't know how this is connect to my changes. The fail appear in my new created test for solar engine for all others should be fine. 

Any idea about this @bdunogier ?

**Comment by bdunogier** [comment]
The failures are fixed by #1662 are they not ?

**Comment by galileo** [comment]
Yes they are but still I need to have those fixes in repo and then check if this solves all things.

**Comment by bdunogier** [comment]
#1662 merged to 6.3 and master. You can merge the fix into this one and go ahead.

**Comment by galileo** [comment]
Test should fail in this place where they are failing currently, we need the new version of solr bundle that is placed in here, what is the approach to handle such cases in our stack ?

https://github.com/ezsystems/ezplatform-solr-search-engine/pull/46

ping @bdunogier @andrerom

**Comment by andrerom** [comment]
1. regarding question in tests and creating data, be aware there are helper methods in BaseContentServiceTest that we could consider reusing here, and/or adapt to make reusable.

2. regarding cross repo testing, in this case we need to fix ES, as i it in this repo. As for cross repo testing, best practice is to temporary modify composer to point to branch and alias it to version we expect. And one both sides are green and passed review, merger should merge manually w/o that commit on both sides and re start tests jobs once both are merged to verify all is green.

**Comment by andrerom** [comment]
For ES, see: https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Search/Elasticsearch/Content/Handler.php#L285

Seems the `2. Update (reindex)..` part might need update to it's algorithm, or one of the others might by mistake delete it, for how to test and debug maybe @pspanja has some pointers.

**Comment by galileo** [comment]
I fixed the ES instance but I don't have idea how to point this kernel to the solr engine that is improved here https://github.com/ezsystems/ezplatform-solr-search-engine/pull/46

@andrerom you wrote:

> As for Sorl, best practice is to temporary modify composer.json (remember to update lock file on this repo in same commit) to point to branch and alias it to version we expect.  

But which composer.json and .lock file should I update, In the kernel there is no information about solr bundle. I can not find how this repo know something about the solr bundle. Can you explain this to me? Because now just the test for solr are not passing.

**Comment by galileo** [comment]
Ok this is ready to review

ping @pspanja @andrerom

**Comment by andrerom** [comment]
+1, congrats @galileo  ;)

**Pull request closed without merging**
