### PR TITLE
EZP-28663: Cannot swap location when viewing item from non-main location

### PR DESCRIPTION
**Pull request by alongosz**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-28663](https://jira.ez.no/browse/EZP-28663)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `6.7`, `6.13`, `7.2`, `7.3`, `7.4`, `master`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

This PR fixes the issue with swapping non-main Location of Content items.

The root cause of this issue was forcing joining Content Info data by main Location w/o taking into the account that a Location might not be the main one.

The second issue is the state of Main Location. In the case of swapping of main Location with non-main Location, that state needs to be swapped as well.

### Simplest case - swapping two main Locations

Note: Content Id is in the square brackets:

#### Before swap:

```
Root
└── [50] Content1
└── [51] Content2
```
content_id | main_node_id | node_id | parent
--- | --- | --- | ---
50 | 60 | 60 | 0
51 | 61 | 61 | 0

#### After swap:

```
Root
└── [51] Content2
└── [50] Content1
```
content_id | main_node_id | node_id | parent
--- | --- | --- | ---
**51** | 60 | 60 | 0
**50** | 61 | 61 | 0

#### Before swap:
```
Root
└── [50] MainArticle (main Location)
└── [51] TestFolder
|         └── [50] MainArticle (secondary Location)
└── [52] FolderSecond
|         └── [53] FolderSecond2 (main Location)
```

content_id | main_node_id | node_id | parent
--- | --- | --- | ---
50 | 60 | 60 | 0
51 | 61 | 61 | 0
50 | 60 | 62 | 61
52 | 63 | 63 | 0
53 | 64 | 64 | 63

#### After swap:
```
Root
└── [50] MainArticle (main Location)
└── [51] TestFolder
|         └── [53] FolderSecond2 (main Location)
└── [52] FolderSecond
|         └── [50] MainArticle (secondary Location)
```
content_id | main_node_id | node_id | parent
--- | --- | --- | ---
50 | 60 | 60 | 0
51 | 61 | 61 | 0
**53** | **62** | 62 | 61
52 | 63 | 63 | 0
**50** | **60** | 64 | 63

Please notice that `main_node_id` in this case needs to change as well.

#### Before swap:

```
Root
└── [50] Article01 (main Location)
└── [51] Article02 (main Location)
└── [52] TestFolder
|         └── [50] Article01 (secondary Location)
└── [53] FolderSecond
|         └── [51] Article02 (secondary Location)
```

content_id | main_node_id | node_id | parent
--- | --- | --- | ---
50 | 60 | 60 | 0
51 | 61 | 61 | 0
52 | 62 | 62 | 0
50 | 60 | 63 | 62
53 | 64 | 64 | 0
51 | 61 | 65 | 65

#### After swap:
```
Root
└── [50] Article01 (main Location)
└── [51] Article02 (main Location)
└── [52] TestFolder (main Location)
|         └── [51] Article02 (secondary Location)
└── [53] FolderSecond (main Location)
|         └── [50] Article01 (secondary Location)
```

content_id | main_node_id | node_id | parent
--- | --- | --- | ---
50 | 60 | 60 | 0
51 | 61 | 61 | 0
52 | 62 | 62 | 0
**51** | **61** | 63 | 62
53 | 64 | 64 | 0
**50** | **60** | 65 | 65

**TODO**:
- [x] Drop forcing Main Location when loading Content Info by Location Id (`Content\Gateway::loadContentInfoByLocationId`)
- [x] Drop forcing Main Location when loading Content item Main Language by its Location Id (`Content\UrlAlias\Gateway::getLocationContentMainLanguageId`)
- [x] Refactor `Content\UrlAlias\Gateway\DoctrineDatabase::getLocationContentMainLanguageId` to use Doctrine Query Builder.
- [x] Swap main Location association for non-main Location swap
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by alongosz** [comment]
@mnocon unfortunately this is javascript error which doesn't tell anything except that something is missing. No idea how to proceed...

**Comment by alongosz** [comment]
Just tested on v2. It seems to affect only v1 PlatformUI (js) application. I'll try to reach out to someone who can help with that (that js error tells me absolutely nothing :stuck_out_tongue_winking_eye:), but we're also considering fixing it for v2 only (depending on severity of the issue on v1).

**Comment by lserwatka** [comment]
@andrerom do we really need to fix for 1.x? The CR was affecting 2.x only. What is your take on this one? Give we want to make 2.4.1 tomorrow, we would have to make a decision now.

**Comment by alongosz** [comment]
@lserwatka @andrerom bad news... root cause of the issue exists in swap location after all, it's directly exposed in Search results (thus directly seen in v1), however it's quite severe:

Main location is always updated when swapping, which shouldn't happen for secondary location. Integration tests for swap didn't show this, because when fetching Main Location to build SPI object, probably only first result is taken into account. My bad :(

I'll try to fix it ASAP before `2.4.1`.

Good catch @mnocon :trophy:

**Comment by lserwatka** [comment]
@alongosz thank you for digging into real issue. Good to have insight!

**Comment by alongosz** [comment]
Updates:
- tests: e4131ce
- re-implemented Gateway for swap: 6b50371

Please see the PR description for identified use cases.

**Comment by lserwatka** [comment]
Could you merge it up?

**Comment by alongosz** [comment]
Merged up to `6.13`, `7.3`, `7.4` and `master`.

**Pull request merged**
