### PR TITLE
EZP-24454: Added common base for ContentTypeGroupCreateStruct / ContentTypeGroupUpdateStruct

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24454

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @bdunogier @pspanja @glye @yannickroger

**Comment by lolautruche** [comment]
> You'll want the same for Role, I expect ;)

Nope, since we have a draft mechanism this is not necessary for role.

**Comment by pspanja** [comment]
What is this needed for, hinting?

**Comment by lolautruche** [comment]
@pspanja see https://github.com/ezsystems/ezpublish-kernel/pull/1398 (same for section)

**Comment by lolautruche** [comment]
@pspanja : https://github.com/ezsystems/repository-forms/pull/45

**Comment by pspanja** [comment]
Thanks, +1.

**Comment by andrerom** [comment]
> Travis seems to be drunk again

It's not, it's the issue @lolautruche mentioned this morning.

**Pull request merged**
