### PR TITLE
EZP-20057: Merge Service tests into integration tests

### PR DESCRIPTION
**Pull request by alongosz**
> Status: **Ready for a review**
> Fixes: [EZP-20057](https://jira.ez.no/browse/EZP-20057)

**TODO**:
- [x] Remove obsolete Service integration tests (6ddfddc).
- [x] Fix found bugs in related integration tests (af01f8b).
- [x] Add missing `TrashItem::$path` property (1e5528b).
- [x] Check integration tests coverage for `ContentTest`*.
- [x] Check integration tests coverage for `ContentTypeTest`*.
- [x] Check integration tests coverage for `LanguageTest`*.
- [x] Check integration tests coverage for `LocationTest`*.
- [x] Check integration tests coverage for `NameSchemaTest`*.
- [x] Check integration tests coverage for `ObjectStateTest`*.
- [x] Check integration tests coverage for `RepositoryTest`*.
- [x] Check integration tests coverage for `RoleTest`*.
- [x] Check integration tests coverage for `SearchTest`*.
- [x] Check integration tests coverage for `SectionTest`*.
- [x] Check integration tests coverage for `TrashTest`*.
- [x] Check integration tests coverage for `UserTest`*.

`*` from the removed namespace `\eZ\Publish\Core\Repository\Tests\Service\Integration`.

### CODE REVIEW

**Comment by alongosz** [comment]
We need to be more careful when testing occurrences of exceptions :-)
For instance, if we test for `InvalidArgumentException` we should also use `@expectedExceptionMessage` to ensure checking for the proper exception. 

An example: in 18118bd there are fixes for bugs related to this - test cases had `mainLanguageCode` and `names` struct fields missing, which also resulted in the `InvalidArgumentException`, but unrelated to what should actually be tested.

// cc @andrerom @pspanja @Nattfarinn

**Comment by alongosz** [comment]
I looked over all the tests in `\eZ\Publish\Core\Repository\Tests\Service\Integration` namespace, improved proper integration tests and added some unit tests :)

Review ping @andrerom @Nattfarinn @pspanja

**Comment by yannickroger** [comment]
Impressive diff!

**Comment by andrerom** [comment]
yeah, this was a long overdue _(issue was created 12/Nov/12 4:47 PM..)_ cleanup to move integration tests that was part of unit tests into the actual integration tests. Small step to make it easier to work on repository :)

There is one thing here which is not test, but was uncovered here and that is: 1e5528b6d732867051cf234fe8d7a0aa7565a717

**Comment by andrerom** [comment]
As this thing is a needed cleanup, passing, not introducing new skips, and difficult to review I'm merging it. Thanks @alongosz

**Pull request merged**
