### PR TITLE
EZP-25880: Fix update sql for Postgres

### PR DESCRIPTION
**Pull request by andrerom**

### CODE REVIEW

**Comment by wizhippo** [comment]
Looks good.  Perhaps we should add an unstable/dbupdate-6.2.0rc1-to-6.4.0.sql that drops the login_normalized column that was added in 6.2.0rc1?

**Comment by andrerom** [comment]
> Perhaps we should add an unstable/dbupdate-6.2.0rc1-to-6.4.0.sql that drops the login_normalized column that was added in 6.2.0rc1?

That should be covered by data/update/postgres/dbupdate-6.3.0-to-6.4.0.sql, it was forgotten.

**Comment by wizhippo** [comment]
Yes thanks.

**Comment by andrerom** [comment]
Thansk

**Pull request merged**
