### PR TITLE
Fix EZP-25280: ParentDepth Limitation fails on content creation

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-25280

As described in the comment on the issue, the problem comes from missing Location on publishing the first Content draft. Solution is similar to what was already done for [`LocationLimitationType`](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Limitation/LocationLimitationType.php#L142).

Added failing/fixed integration test and missing unit tests.

### CODE REVIEW

**Comment by andrerom** [comment]
With fix for CS +1

However should be reopened against 6.4 branch once @bdunogier has tagged final.

**Comment by pspanja** [comment]
Ok, fixed and amended.

**Comment by andrerom** [comment]
_6.4 branch up ;)_

**Comment by pspanja** [comment]
Closing in favor of https://github.com/ezsystems/ezpublish-kernel/pull/1706.

**Pull request closed without merging**
