### PR TITLE
CodeClimate configuration

### PR DESCRIPTION
**Pull request by MarioBlazek**
This PR resolves:
* introduces explicit CodeClimate configuration in `.codeclimate.yml`
* excludes all tests from score
* displays CodeClimate badge in `Readme.md`

CodeClimate for this repo can be found [here](https://codeclimate.com/github/ezsystems/ezpublish-kernel).

### CODE REVIEW

**Comment by MarioBlazek** [comment]
@andrerom CodeClimate is already enabled https://codeclimate.com/github/ezsystems/ezpublish-kernel

**Comment by andrerom** [comment]
Partly, I have tried to enable it fully now.

**Comment by andrerom** [comment]
@MarioBlazek  could you try pushing to this PR again?

**Comment by MarioBlazek** [comment]
Build is passing on this one https://codeclimate.com/github/ezsystems/ezpublish-kernel/builds/190

**Comment by MarioBlazek** [comment]
Problem is with other build without code climate configuration. phpmd needs to analyse to many files.

**Comment by andrerom** [comment]
> Problem is with other build without code climate configuration. phpmd needs to analyse to many files.


but why does builds of this PR fail then? config is here.

**Comment by MarioBlazek** [comment]
Because other builds are in queue. Change trigger code climate builds.

**Comment by MarioBlazek** [comment]
Basically this should be merged, so that every new PR can be analyised with this configuration and CodeClimate would run without problems.

**Comment by andrerom** [comment]
@MarioBlazek Ok, 6.12 branched of and tagged, should we perhaps target 6.7 with this so PR's there won't error out?

**Comment by MarioBlazek** [comment]
@andrerom I can try :)

**Comment by MarioBlazek** [comment]
@andrerom I've screwed something with my branch, I will do new PR with codeclimate configuration.

**Pull request closed without merging**
