### PR TITLE
Fix EZP-23970: Configure dynamic storage dependencies for search engine services

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-23970, sub-task of https://jira.ez.no/browse/EZP-23940

The PR is based on https://github.com/ezsystems/ezpublish-kernel/pull/1162 and will be rebased on master when that is merged.

Followup: https://jira.ez.no/browse/EZP-23969

### CODE REVIEW

**Comment by pspanja** [comment]
Ping @andrerom, @bdunogier, @lolautruche, ref. naming added in https://github.com/ezsystems/ezpublish-kernel/commit/bb79496d1f869e3849b6ec4e8ba227ce02bc0b2f.

**Comment by bdunogier** [comment]
I'd have appreciated a more elaborated description, either here on in the issue (I did check) ;-)

Let's see.

**Comment by bdunogier** [comment]
Not sure how this makes something really dynamic, but no reason not to +1 it :-)

**Comment by lolautruche** [comment]
+1

**Comment by pspanja** [comment]
Closing in favour of https://github.com/ezsystems/ezpublish-kernel/pull/1181.

**Pull request closed without merging**
