### PR TITLE
EZP-28135: Removed @internal tag from SignalSlot classes

### PR DESCRIPTION
**Pull request by emodric**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-28135](https://jira.ez.no/browse/EZP-28135)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `7.5`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

This class has been used by other packages for ages so this removes some deprecation notices from the logs.

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by wizhippo** [comment]
Should eZ\Publish\Core\SignalSlot\Signal also be updated?

**Comment by alongosz** [comment]
> Should eZ\Publish\Core\SignalSlot\Signal also be updated as it is used by Slot?

Yes, it should because it is also used in custom code.

@emodric I'm not sure why it was internal, to me it never should as it is documented extension point. It's a bug since `6.7`. Could you rebase?

**Comment by emodric** [comment]
@alongosz Pushed the rebased commit.

**Comment by andrerom** [comment]
> @emodric I'm not sure why it was internal, to me it never should as it is documented extension point. It's a bug since 6.7. Could you rebase?

The intention was to move it to API/ namespace, and change these to extend those.
Can't we still do that? Even for 6.7 and up?

**Comment by emodric** [comment]
If you wish, but it doesn't really make much sense to have empty classes in `Core` that only extend `API` ones.

**Comment by andrerom** [comment]
> If you wish, but it doesn't really make much sense to have empty classes in Core that only extend API ones.

we need that for BC, if only for being deprecated

However question was more for @alongosz and team to decide ;)

**Comment by alongosz** [comment]
> The intention was to move it* to API/ namespace, and change these to extend those in API.
> Can't we still do that? Even for 6.7 and up?

Well... We don't know how to tell you this Guys... In Kernel 8.0 we plan to drop Signal Slots in favor of Symfony events which are commonly understood in Symfony ecosystem and provide what Signal Slots "reinvent" plus some more.

This is the reason that right now I don't mind it belonging to the Core namespace.

**Comment by andrerom** [comment]
> Well... We don't know how to tell you this Guys... In Kernel 8.0 we plan to drop Signal Slots in favor of Symfony events which are commonly understood in Symfony ecosystem and provide what Signal Slots "reinvent" plus some more.

That is fine by me, and a good argument for not moving it.
SIDE: When you do such a change, make sure we can natively be able to listen to repo events lazyly over message bus as well 👍

**Comment by alongosz** [comment]
Merged into `6.7` and up to `6.13`, `7.4`, `7.5` and `master`.

Thank you @emodric

**Pull request merged**
