### PR TITLE
REST: Implemented SortClause in Query Parser

### PR DESCRIPTION
**Pull request by bdunogier**
> Story: https://jira.ez.no/browse/EZP-24315
> Status: work in progress

This adds support for SortClause in queries from REST views.

It has only been manually tested on the `ContentName` clause.

Example curl call (REST auth in basic): 
```
curl -v -X POST http://admin:publish@localhost/api/ezp/v2/views --data @/tmp/ViewInput.xml -H 'Content-Type: application/vnd.ez.api.ViewInput+xml; version=1.1'
```

with `/tmp/ViewInput.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<ViewInput>
  <identifier>ArticleTitleView</identifier>
  <ContentQuery>
    <Criteria>
      <AND>
        <ContentTypeIdentifierCriterion>article</ContentTypeIdentifierCriterion>
      </AND>
    </Criteria>
    <limit>10</limit>
    <offset>0</offset>
    <SortClauses>
      <SortClause>
        <SortField>NAME</SortField>
      </SortClause>
    </SortClauses>
  </ContentQuery>
</ViewInput>
```

## TODO
- [ ] Unit test the Query Input Parser, including SortClause parsing
- [ ] Specify direction support (not in the specs right now, currently uses `SortDirection` next to `SortField`

### CODE REVIEW

**Comment by andrerom** [comment]
```
    <SortClauses>
      <SortClause>
        <SortField>NAME</SortField>
      </SortClause>
    </SortClauses>
```


Given this has never been implemented, would it be better if modeled closer to how criterions are done? Asking since it is strange one uses concept of custom xml tags per type, while here there is a generic structure where we won't be able to express rules around for instance `SortClause/MapLocationDistance` arguments should be xsd validated.

**Comment by bdunogier** [comment]
> Given this has never been implemented, would it be better if modeled closer to how criterions are done? 

True. 

Something like that ?

```xml
<SortClauses>
  <ContentName direction="descending" />
  <MapLocationDistance from="lat,lon" />
</SortClauses>
```

**Comment by andrerom** [comment]
Yes, something like that. WDYT @pspanja @lolautruche @emodric ?

**Comment by dpobel** [comment]
Just one note, for consistency we should use `order` instead of `direction` as this is what is used almost everywhere else.

**Comment by pspanja** [comment]
Sounds good, +1 on that.

**Comment by emodric** [comment]
Looks good to me too. +1 and +1 on @dpobel's remark.

**Comment by lolautruche** [comment]
+1

**Comment by bdunogier** [comment]
It is direction in the the `SortClause` API object. But I could go with order.

**Comment by bdunogier** [comment]
I'll create a PR with the spec change soon, and link it here.

**Comment by bdunogier** [comment]
Needs to be reconsidered irt specs.

**Pull request closed without merging**
