### PR TITLE
EZP-29592, fixing spaces in image urls

### PR DESCRIPTION
**Pull request by pbek**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-29592](https://jira.ez.no/browse/EZP-29592)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | master
| **BC breaks**      | ?
| **Tests pass**     | ?
| **Doc needed**     | no

This is a small fix for spaces in image urls.

**TODO**:
- [ ] Implement feature / fix a bug.
- [ ] Implement tests.
- [ ] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

### CODE REVIEW

**Comment by andrerom** [comment]
Something we want to deal with here or other places @kmadejski @bdunogier ?

**Review by kmadejski — CHANGES_REQUESTED** [review]
@pbek thank you for the contribution! Of course, I agree that it's a good idea to remove or replace spaces (and other invisible characters) in image URLs, but unfortunately, I think that it should not be done in Twig template. 

As for me, it should be done during the image creation/saving since these values with spaces are in `ezimagefile` table as well.

**Comment by pbek** [comment]
@kmadejski I also think that my "fix" is just a "hotfix"

**Comment by crevillo** [comment]
hello, @kmadejski has just pointed me to this ticket in the slack. i'm also agree that it should not be done on twig and try to do it while image is saved. 

i doubt if this should be a default setting or something that users could configure... thoughts?

**Comment by andrerom** [comment]
@crevillo I don't see a need for config on this, more of a path normalization to do on creation + updates or? (How did legacy deal with this?)

**Pull request closed without merging**
