### PR TITLE
Fix 25568 Cannot edit user class

### PR DESCRIPTION
**Pull request by crevillo**
Fixes: https://jira.ez.no/browse/EZP-25568

At least if first the part where you cannot edit the user class. Problem is some the user fields are marked in the databate as searchable. This is the case for `user_account (ezuser)` and `signature (eztext)`
As `is_searchable` columns for those are set to `1`, in platform ui edition searchable checkbox is checked and so validation occurs cause these fieldtypes are not searchable. 

The ezuser part i think is solved until we plan to make ezuser searchable. The eztext part needs some more insights though. 
actually this pr make this field not searchable https://github.com/ezsystems/ezpublish-kernel/pull/1229/commits/1106a6c02e4e7d10974c023098f8dabd0357e64e#diff-ed6cbe3216a163fb8b8810f8008cd58aR171
But if is this is defined not searchable here, how can make it searchable only for Solr Search Engine?

ping @andrerom @pspanja @bdunogier 

P.s. Pr goes againts 6.2 branch following @bdunogier advice

### CODE REVIEW

**Comment by crevillo** [comment]
ops, sorry. let me rebase...

**Comment by crevillo** [comment]
rebased.

**Comment by bdunogier** [comment]
Already discussed, I'm +1.

We will have to confirm how we handle 6.3 (master) update (separate file in unstable for the time being ?)

**Comment by pspanja** [comment]
@crevillo 
> But if is this is defined not searchable here, how can make it searchable only for Solr Search Engine?
You will need to override the field type implementation, for example see what I did for tests:
https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/API/Repository/Tests/FieldType/SearchableFloat.php

+1 otherwise

**Comment by bdunogier** [comment]
Does that mean that the solr bundle should redefine all FieldTypes + services when it adds search support to them ?

**Comment by pspanja** [comment]
That would be one option, we could also make `$isSearchable` a parameter and override it from Solr repo, or just make the field types searchable and handle Legacy engine in Legacy engine.

**Comment by crevillo** [comment]
but if so, we should determine which search engine is being used from platform ui, right? Even if we made it searchable with solr, users should can decide if that field will be searchable or not... where will we store that setting then?

AFAIK, if field is not searchable then the related checkbox is readonly. But what determines if that checkbox is checked or unchecked is that field on the database, right?

**Comment by andrerom** [comment]
+1

**Comment by gggeek** [comment]
Tbh, I long for how 'searchable' fields worked in ez4, as it seemed a sensible default:
- for 'filtering' (query criteria), all fields are always available
- the 'field is searchable' flag only applied to 'full text searches'

Not sure how to best reproduce this going forward though :-)

**Comment by bdunogier** [comment]
I can't say that I disagree, @gggeek. But there will be other major versions :-)

**Comment by pspanja** [comment]
@gggeek the idea to have something like availableInFulltextSearch on the field definition was already discussed, it was not implemented because of data compatibility with Legacy stack. But that should not be a constraint anymore :)

**Comment by bdunogier** [comment]
And merged, thank you @crevillo.

**Comment by gggeek** [comment]
@pspanja that might be one way to tackle the issue.

Otoh
- I see not a lot of avlue in allowing the 'content admins' to use the backoffice to set which fields are available for fetches ('old indexing flag')
- the default should be to have all fields available for fetches, not the opposite

**Comment by pspanja** [comment]
I agree that it should be the default. About the value of such control, maybe not too common a case, but I'm thinking for example avoiding indexing big text fields that would unnecessarily inflate the index.

**Pull request merged**
