### PR TITLE
Fixing  error on Platform.sh

### PR DESCRIPTION
**Pull request by SerheyDolgushev**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-XXXXX](https://jira.ez.no/browse/EZP-XXXXX)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `7.x`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

Without this fix, it is impossible to run `composer ezplatform-install` on platform.sh. As it leads to
```
SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. 
```

**TODO**:
- [ ] Ask for Code Review.

### CODE REVIEW

**Comment by gggeek** [comment]
Is the fix not to rather limit the size of the index ? This is how it is done on all other cols/tables afaik

**Comment by SerheyDolgushev** [comment]
You mean something like
`KEY `ezcontentobject_tree_contentobject_id_path_string` (`path_string`(191), `contentobject_id`)`
?

**Comment by gggeek** [comment]
exactly

**Comment by SerheyDolgushev** [comment]
Done

**Comment by andrerom** [comment]
This don't really have anything to do with platfrom.sh does it?
_(ps: you can rebase on latests master branch, which has fix for what ezrobot complains about)_

Aslo, guess we need update SQL for this, see previous once for how.


/cc @glye

**Comment by glye** [comment]
@SerheyDolgushev Example of the update SQL we need: https://github.com/ezsystems/ezpublish-kernel/commit/0f82a088ebe7949970f9cf1acb687b21b42a0779#diff-26fc7e315e295d960f9075fbe265cec0
Let me know if you'd like help with the PR.

**Comment by SerheyDolgushev** [comment]
@glye was not sure which SQL file should be used for update, please check https://github.com/ezsystems/ezpublish-kernel/pull/2495/commits/245d2142983062a55fdbab515390c52dcce15420

@andrerom did rebase with latest master branch:
```
git fetch upstream
git rebase upstream/master
```

**Comment by andrerom** [comment]
@SerheyDolgushev the rebase seems to havge been wrong, you can see it on the commits and changes here. Maybe just create new branch based on latests master, cherry pick your changes and force push to overwrite this branch.

**Comment by glye** [comment]
> @glye was not sure which SQL file should be used for update, please check 245d214

@SerheyDolgushev This looks good.

**Comment by SerheyDolgushev** [comment]
@andrerom @glye @alongosz sorry, is there something preventing this to be merged?

**Comment by andrerom** [comment]
There is 94 commits on this PR 😉

**Comment by alongosz** [comment]
> sorry, is there something preventing this to be merged?

@SerheyDolgushev I don't know where to start ;)
1. This needs rebase, see the number of changed files and the diff.
2. As of eZ Platform 2.5 `schema.sql` is no longer maintained, `eZ/Bundle/EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml` needs an update.
3. SQL upgrade scripts are still in use, however the one you've modified is not for master
4. If this bug existed in v1.7 LTS, you rather need to target branch `6.7` and rebase against it. Otherwise you'll get your bugfix in 2.5 LTS only (unless this is what you want).
5. Missing JIRA issue. Please register on [jira.ez.no](https://jira.ez.no) and create bug report. Bug should describe the actual issue, it's not really related to Platform.sh. Could be something like `Db index ezcontentobject_tree_contentobject_id_path_string has missing length for path_string column`.
6. The PR title is irrelevant to the fix, once you get your JIRA issue, you could title it: `EZP-<ISSUE_NO>: Added length to ezcontentobject_tree_contentobject_id_path_string db index`.

^ Huh, that's a lot. Proper rebase would be a good first step. Ping me on eZ Community slack if you need help :)

**Comment by SerheyDolgushev** [comment]
Made https://github.com/ezsystems/ezpublish-kernel/pull/2574 which fixes both `schema.sql` and `schema.yaml`

**Comment by andrerom** [comment]
Closing in favour of #2574

**Pull request closed without merging**
