### PR TITLE
Implement EZP-24314: Indexable BinaryFile field type

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-24314

A subtask of https://jira.ez.no/browse/EZP-24232

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by pspanja** [comment]
Review ping @bdunogier @lolautruche @glye

**Comment by crevillo** [comment]
a question here: is the binary content indexing related to this? i mean, if you have a pdf and want to index its contents could we do it? or it's another layer/story?

**Comment by pspanja** [comment]
@crevillo It's a another story for the future, not handled here

**Comment by crevillo** [comment]
ok! thanks.

**Comment by bdunogier** [comment]
+1

**Pull request merged**
