### PR TITLE
Get tests to pass on PHPv7

### PR DESCRIPTION
**Pull request by andrerom**
Fix issues for PHP 7.0 to be able to do performance testing on it once alpha1 is out in a few weeks.

Changes:
- Renamed all legacy converters consistently as they had unsafe names like Float, Integer and Null
- Fix use of class aliases that used the protected keywords
- Bumped phpunit as I thought it was causing issues, however this was not related and it can be moved out to separate PR if preferred.
- Fixed an issue in regards to legacy storage engine doing sorting on object states when setting priority in a way was wrong
 - This should probably have a issue and be back ported actually, as it might also affect other versions suddenly, POV?

Might be a bit early to allow 7 to fail tests, however seems to have much less issues now so hopefully it will only further stabilize.

### CODE REVIEW

**Comment by andrerom** [comment]
ping @bdunogier @lolautruche @pspanja

**Comment by pspanja** [comment]
> See also open question on making issue out of the object state sorting bug.

+1 on the PR and separate issue + backport.

**Comment by lolautruche** [comment]
> Fixed an issue in regards to legacy storage engine doing sorting on object states when setting priority in a way was wrong

Is this related to PHP 7?
Anyway, I think this should indeed be reported as separate issue. As for backport, it depends on the answer to my question above.

**Comment by andrerom** [comment]
> Is this related to PHP 7?

yes, however see the commit description for details, it is updated now.
Also moved phpunit update to separate PR.

**Comment by lolautruche** [comment]
+1

**Pull request merged**
