### PR TITLE
Fix EZP-23967: Refactor Repository and its services for main Search Handler implementation

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-23967, a sub-task for https://jira.ez.no/browse/EZP-23940

Followup: https://jira.ez.no/browse/EZP-23968

### CODE REVIEW

**Comment by pspanja** [comment]
This is https://github.com/ezsystems/ezpublish-kernel/pull/1157 reopened against `master` and has @lolautruche's +1 from there.

One review missing, ping @andrerom, @bdunogier, @glye, @yannickroger.

**Comment by pspanja** [comment]
Re-triggered Travis for https://github.com/padraic/mockery/pull/422 fix.

**Comment by bdunogier** [comment]
Looks good.

One naming note: I wouldn't use the term "configure" when it comes to services definitions updates. It might be in a configuration file, it's not really Configuration as we usually intend it. Maybe Container configuration, but we have both parameters and configuration there.

**Comment by pspanja** [comment]
Ok, but for future commits... I need to get rid of this fast, otherwise I'll get PTSD :)
Thanks for the review!

**Pull request merged**
