### PR TITLE
EZP-30316: Changed default password quality settings

### PR DESCRIPTION
**Pull request by glye**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-30316](https://jira.ez.no/browse/EZP-30316)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | master
| **BC breaks**      | no-ish
| **Tests pass**     | yes
| **Doc needed**     | yes

Set stricter default password requirements for the standard User content type, and for new User fields. The features for this are introduced in 7.4, so it can't be backported further.

I didn't make this configurable, as these are not hardcoded setting values, they are defaults, and can be changed by editing the User content type. Configurable defaults would be meta-configuration, kind-of :)

Existing lower quality passwords are not affected, the change affects only new passwords.

- [x] Require 10 characters minimum.
- [x] Require upper and lower alphabetic characters, and digits. Do not require other characters.
- [x] Ensure that this applies both to the standard User content type (default DB content, for new installs), and to any new User field types created.
- [x] ~Add new tests to verify the change.~ This seems to be well enough covered [here](https://github.com/ezsystems/ezpublish-kernel/blob/ca35b890be6dc61e242a180d2fc9d33b9a8bfa1e/eZ/Publish/Core/Repository/Tests/Service/Mock/UserPasswordValidatorTest.php#L29)

The same in legacy: https://github.com/ezsystems/ezpublish-legacy/pull/1423

### CODE REVIEW

**Comment by glye** [comment]
@alongosz Ah, good news that we have it. Added.

**Comment by glye** [comment]
Added BC doc.

**Comment by glye** [comment]
@ezsystems/qa-team Please test. @lserwatka has OK'ed this for 2.5 release.

**Comment by DominikaK** [comment]
Added to 2.5 release notes in https://github.com/ezsystems/developer-documentation/pull/540/commits/572ca9fb386205feca66828326f25ed80a2cfde8

**Comment by DominikaK** [comment]
To clarify: does this mean that the default admin password in new installations will be `PassWord42`?

**Comment by glye** [comment]
@DominikaK Nope, the default password(s) are unchanged and will keep working as before.

**Pull request merged**
