### PR TITLE
Fix EZP-24476: Refactor CSRF token generation in Security login form

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24476

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @bdunogier @yannickroger @glye @pspanja

**Comment by andrerom** [comment]
+1

**Comment by bdunogier** [comment]
+1

**Comment by glye** [comment]
+1, but Travis..?

**Comment by andrerom** [comment]
some changes need on unit tests it seems

**Comment by lolautruche** [comment]
Yes just updated `CsrfListenerTest`. However it seems to have unexpected consequences on PlatformUI authentication.

**Pull request merged**
