### PR TITLE
Reverted #1618 (searchable eztext and content type edit)

### PR DESCRIPTION
**Pull request by bdunogier**
> Reverts #1618 (https://jira.ez.no/browse/EZP-25568)

See discussion at https://github.com/ezsystems/ezpublish-kernel/commit/c1511a37cf46329bfb96a60b2baef291a27c1f80#commitcomment-16829444. Forcing searchable to false on all `eztext` isn't really what we want.

_Hint: `git revert -m 1 <merge sha1>` to revert a merge commit_

### CODE REVIEW

**Comment by crevillo** [comment]
+1.
I'd add we need better understanding on what `is_searchable` column and `isSearchable` method are for...
If the db column determines that you can do content queries filtering by this kind of fields, maybe we could rename `isSearchable` to `isIndexable` or something... but now i feel i miss part of the whole picture.

**Comment by emodric** [comment]
+1

@crevillo Additional problem with `is_searchable` in the new stack is that it is used by search engine for filtering too (i.e., not full text search, which is IMHO also kinda wrong). So for example if you want to fetch and display some content which is tagged with some tag (for example, fetch all cars which have 8 cylinder motor), but you don't want full text search of that tag (since the tag name could be just `4`, `8`, `12` and it doesn't make sense to search for that), you're out of luck.

**Comment by andrerom** [comment]
+1

**Comment by andrerom** [comment]
+1

It seems in legacy, even user is searchable:
```
    function metaData( $contentObjectAttribute )
    {
        $metaString = "";
        $user = $contentObjectAttribute->content();
        if ( $user instanceof eZUser )
        {
            // create a default user account
            $metaString .= $user->attribute( 'login' ) . " ";
            $metaString .= $user->attribute( 'email' ) . " ";
        }
        return $metaString;
    }
```

**Comment by emodric** [comment]
@andrerom Seems so. I overlooked that.

Also from `ezusertype.php`

```php
function isIndexable()
{
    return true;
}
```

**Comment by crevillo** [comment]
@andrerom i try to remember an issue we worked on even before git and jira times. it was in the old tracker and it was quite similar. it was a problem modifying this ezuser_type and the problem, as in this case, was because the initial dump... 
i gonna try to find it to refresh what and why do it there...

**Pull request merged**
