### PR TITLE
EZP-25777 UserMetadata criterion handling in REST Views

### PR DESCRIPTION
**Pull request by glye**
> Implements https://jira.ez.no/browse/EZP-25777
> Based on https://github.com/ezsystems/ezpublish-kernel/pull/1650 by @Nattfarinn
> Status: Ready for review

Adds a unit test to @Nattfarinn's criterion handler.

### CODE REVIEW

**Comment by glye** [comment]
Review ping @Nattfarinn @andrerom @bdunogier @pspanja - Ref https://github.com/ezsystems/ezpublish-kernel/pull/1650

**Comment by andrerom** [comment]
+1

**Comment by bdunogier** [comment]
Looks good to me.

A functional test would (probably) not kill any 🐰, though.

**Comment by Nattfarinn** [comment]
Wow, thanks a lot! I'm sorry I didn't do it myself :(, I've been on a sick leave for over a week.

**Comment by glye** [comment]
@bdunogier That's feature creep, you bastard ;) Can add a functional test, but that will probably not pass before freeze. OTOH, the "My Content" feature ( https://jira.ez.no/browse/EZP-25769 ) which is blocked by this may not pass today anyway.

@Nattfarinn You're welcome. Thanks for the contribution, and get well!

**Comment by bdunogier** [comment]
@glye tests are not features ;-)

I would feel safer if we had something that actually _runs_ the feature, using the entire stack. But it doesn't have to block the PR.

**Comment by andrerom** [comment]
@glye Scope creep is the word you are looking for, but please 🚢  this and take functional rest tests in followup PR.

**Comment by glye** [comment]
Some sort of creepiness, anyway. :grumpy_cat:
Ack. Tested manually in rest client, FWIW.

**Pull request merged**
