### PR TITLE
Add light Behat testing to kernel repo

### PR DESCRIPTION
**Pull request by andrerom**

### CODE REVIEW

**Comment by andrerom** [comment]
review ping @bdunogier @lolautruche @pspanja @yannickroger 

Moved setup scripts to separate files to avoid all lines having conditional if's.

**Comment by pspanja** [comment]
Awesome :) +1

**Comment by lolautruche** [comment]
+1

**Comment by andrerom** [comment]
Thanks :)

**Comment by bdunogier** [comment]
That's a lot of tests for one repo... but +1 in retrospect :-)

**Comment by andrerom** [comment]
... but I don't see how we can avoid that unless we ourselves setup testing with dependency trees on jenkins.

**Pull request merged**
