### PR TITLE
EZP-30478: delete FieldTypeTools class as does not seem to be needed anymore

### PR DESCRIPTION
**Pull request by crevillo**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     |[EZP-30748](https://jira.ez.no/browse/EZP-XXXXX)
| **Bug/Improvement**|  no/yes
| **New feature**    |mp
| **Target version** | 7.5
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

This class does not seem to be needed anymore. it is also implementing an unexisting interface. 

ping @andrerom @glye

### CODE REVIEW

**Comment by glye** [comment]
So this passed in master but failed in 7.5, interesting. Could the class be in use there still?

**Comment by andrerom** [comment]
> So this passed in master but failed in 7.5, interesting. Could the class be in use there still?

might be because branch was swapped after push, new force push can verify that.

**Comment by crevillo** [comment]
i've just repushed it.

**Comment by crevillo** [comment]
it's the failing test related to my pr?

**Comment by glye** [comment]
I don't see any direct relation, but since it keeps failing... Did it rerun the tests when you repushed? The currently failing test is on master branch, not 7.5, so there seems to be something wrong with the PR there.

**Comment by mnocon** [comment]
@crevillo it looks to me like the build has not been triggered after you switched base branch, you can see it in the log here:
```
@crevillo crevillo force-pushed the crevillo:EZP-30748--fieldtypetools-class branch from aa4d742 to 9f31f49 27 days ago
@crevillo crevillo changed the base branch from master to 7.5 27 days ago
@crevillo crevillo changed the title EZP-30478: delete FieldTypeTools class as does not seem to be needed … EZP-30478: delete FieldTypeTools class as does not seem to be needed anymore 27 days ago
```

The push happened before that, so the latest build is still against master.
If you could push again (I usually do something like `git commit --amend & git push -f`) then I believe it will run correctly.

**Comment by crevillo** [comment]
Hi, thanks. I will do this next Monday. On holidays and no laptop here :)

**Comment by mnocon** [comment]
Sure, no pressure - enjoy your holidays 😄 🌴

**Comment by crevillo** [comment]
@mnocon it looks green now. thank you!

**Comment by andrerom** [comment]
Thanks @crevillo !

**Pull request merged**
