### PR TITLE
[Behat] Fix deprecation warning causing behat test failures

### PR DESCRIPTION
**Pull request by miguelcleverti**
Removes the Deprecation warning notices from behat output.

### CODE REVIEW

**Comment by bdunogier** [comment]
What bothers me a bit with this is that it needs to be applied to *each* context. On the other hand, given that these contexts use deprecated code, maybe it is okay.

**Comment by bdunogier** [comment]
Actually, let's say it is okay: *+1* with CS fixed. Let's merge ASAP.

**Comment by andrerom** [comment]
+1

**Comment by bdunogier** [comment]
After thinking, it would also work to have that in a dedicated Context's ctor. We could add this context to features that require it.

**Comment by andrerom** [comment]
@miguelcleverti Status here, is this needed or is the issue somewhat fixed by change in meta repo?

**Comment by miguelcleverti** [comment]
@bdunogier I moved the code into a dedicated trait so that it can be included easily in any context that it is needed.

**Comment by andrerom** [comment]
I guess ideally we should set error level back to previous value in after scenario step of there is such a thing.

**Comment by miguelcleverti** [comment]
@andrerom, updated, now it restores the value to the original one

**Pull request merged**
