### PR TITLE
[Travis] (Re-)Add testing for Symfony 2.8

### PR DESCRIPTION
**Pull request by andrerom**
Will adjust for beta tags once they are out before this is merged.

### CODE REVIEW

**Comment by emodric** [comment]
@andrerom 2.8-BETA1 is out ;)

**Comment by andrerom** [comment]
Thanks, it's passing it seems, will need to run one of the behat tests with it also.

**Comment by emodric** [comment]
This issue is still present though: https://jira.ez.no/browse/EZP-25098

**Comment by andrerom** [comment]
> This issue is still present though: https://jira.ez.no/browse/EZP-25098

Sure, as soon as this is passing, it will be easier for you to do a test / fix for that ;)

**Comment by lolautruche** [comment]
+1

**Pull request merged**
