### PR TITLE
Remove redundant setting of locationId attribute

### PR DESCRIPTION
**Pull request by wizhippo**
As the location is already set in the parameters the routerlistener will add the location to the request attributes

### CODE REVIEW

**Comment by bdunogier** [comment]
Hmm, this still means that the `locationId` attribute isn't set anymore, does it not ? I'm a bit concerned about side effects.

**Comment by wizhippo** [comment]
According to the tests there are no side effects.  They all pass.

The questions I have is should a matcher be modifying the request? That goes beyond matching.

The request is later updated with the parameters that matchRequest returns to the [RouterListener](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php#L115). The exception in UrlAliasRouter are attributes used to forward and redirect the request, though thinking about it they too should be changed and returned with the parameters.

Thoughts?

**Comment by joaoinacio** [comment]
The `locationId` parameter was used by the ViewControllerListener, now ContentViewBuilder.php (see [ContentViewBuilder.php#L90](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php#L90) ), though i'm not sure if it's fully covered by tests.

Also the message for the original commit @[cdffa53b62d470f9](https://github.com/ezsystems/ezpublish-kernel/commit/cdffa53b62d470f912a45f95f882844d65f46c14) was: ```
UrlAliasRouter : Added locationId as request attribute for further use when checking authorization with the repository```
This was way back in 5.0, not sure if still relevant.

**Comment by wizhippo** [comment]
These are still set by the RouterListener so should not be an issue.  The RouterListener takes the return value of matchRequest and adds them to the request attributes.

For the case of locationId it is being set twice as an request attribute.  Once in the UrlAliasRouter directly where it adds is as a request attribute, it also returns it as part of the parameters, where the RouterListener sets it again when it take the return value of matchRequest and adds them the the request attributes.

**Comment by joaoinacio** [comment]
Thanks @wizhippo! I agree in principle, however still slightly concerned as well about possible side effects here (IIRC content preview had some related issues).
@bdunogier : perhaps sanities from QA? A JIRA ticket would need to be created for it.

**Comment by lolautruche** [comment]
I agree with @wizhippo. This should not be a problem and those attributes are actually duplicates.

As @wizhippo mentioned, returned `$params` hash is actually added to the request attributes, so adding `locationId` (which was already the case) and other attributes to `$params` will have the exact same effect than `$request->attributes->set()`.

**Comment by lolautruche** [comment]
So, to illustrate:
* `$params` is returned to [CMF `ChainRouter`](https://github.com/symfony-cmf/routing/blob/1.3/ChainRouter.php#L185)
* `$params` is then added to the main request attributes by [`RouterListener`](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php#L166)
* `$request->attributes` is a `ParameterBag`: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpFoundation/ParameterBag.php#L68-L76

So +1 from me 😃

**Comment by wizhippo** [comment]
Squashed

**Comment by bdunogier** [comment]
And merged. Thank you very much @wizhippo.

**Pull request merged**
