### PR TITLE
EZP-24227: Missing Translation Helper in Content Download service definition

### PR DESCRIPTION
**Pull request by crevillo**
https://jira.ez.no/browse/EZP-24427

Constructor for the controller needs a third param

ping @bdunogier @andrerom @lolautruche

### CODE REVIEW

**Comment by lolautruche** [comment]
Woops, something has been forgotten :smile:

+1

**Comment by andrerom** [comment]
+1

**Comment by bdunogier** [comment]
+1 :innocent:

**Comment by bdunogier** [comment]
Thank you Carlos.

**Pull request merged**
