### PR TITLE
EZP-24065: Fixed a wrong usage of the repository/section service

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-24065

See https://github.com/ezsystems/PlatformUIBundle/pull/210

### CODE REVIEW

**Comment by andrerom** [comment]
+1  (Label: *tests for REST...*)

**Comment by pspanja** [comment]
@andrerom IMHO the proper way to do it would be finishing PHP REST client and restoring the setup to push existing integration tests over it. But that would be quite an effort :)

+1

**Comment by andrerom** [comment]
@pspanja I know :)

**Comment by dpobel** [comment]
Indeed, this kind of bug would have been spotted way earlier with an automatic test strategy...

**Pull request merged**
