### PR TITLE
Update REST-API-V2.rst

### PR DESCRIPTION
**Pull request by gbentley**
Various grammatical improvements

### CODE REVIEW

**Comment by lolautruche** [comment]
I guess it still needs to be rebased?

**Comment by yannickroger** [comment]
@gbentley can you squash the 2 commits into one and ping me, I'll merge it asap

**Comment by gbentley** [comment]
@yannickroger I made a few attempts to move the commit further along the tree, but my rebase failed miserably (plus the merge commit didn't appear in the rebase).  Any suggestions?

**Comment by andrerom** [comment]
Many ways, but this is maybe the safest to avoid issues:
- save diff for the original patch
- pull in latest changes on master
- checkout your branch and reset it to be same as master `git reset --hard origin/master`
- re apply your patch and fix conflicts if there is any
- force push

**Comment by yannickroger** [comment]
@gbentley I took care of it.
Thanks for your contribution.

**Comment by andrerom** [comment]
Thanks @gbentley and @yannickroger ! :)

**Pull request closed without merging**
