### PR TITLE
EZP-25623: Wrong content object URL path after content update

### PR DESCRIPTION
**Pull request by clash82**
Link to Jira task: https://jira.ez.no/browse/EZP-25623

References on Slack
https://ezcommunity.slack.com/archives/ezpublish5-use/p1459323229000166

### CODE REVIEW

**Comment by clash82** [comment]
ping @bdunogier @andrerom @SylvainGuittard

**Comment by arnebratt** [comment]
Thank you, @clash82 . A problem I noticed, now the comma is filtered out by SlugConverter::cleanupText(). You need to add a comma in the string at line 256 as well to fix this.

**Comment by bdunogier** [comment]
Does this have a BC impact ? Some urls will be different before and after this patch, won't they ?

**Comment by arnebratt** [comment]
@bdunogier : Well, I have only experienced it on eZ 5.4. Since it's not a problem on legacy, the admin interface sets urls correctly. When I used the Symfony based library from a command line script to set custom url aliases I lost the commas though. I guess for the new admin interface on eZ Platform, the urls will all be without commas.

However, would it be a problem? The urls are generated differently on publish, but are otherwise handled correctly, as far as I can understand. If the same content is republished after applying this patch, the url history should handle it correctly with a redirect? Not tested btw.

**Comment by clash82** [comment]
It's worth to mention two things:

- it was working like this on the legacy (no dots, no commas),
- it affects API and REST, so it will not work on PlatformUI as well.

We've tested this patch on very large amount of content objects (>1000) without unexpected issues.

@arnebratt commas should be omitted when generating new url aliases... at least it was working like that in the previous version.

imo, way how it is working now is a BC break :smiling_imp:

**Comment by arnebratt** [comment]
I just added a url alias with comma and dot in an eZ 5.4.4 version, and they are kept there and working correctly. So the legacy code does not filter out commas or dots (the exception is trailing dots).

**Comment by bdunogier** [comment]
Remember that there are two settings for url alias generation in legacy. The one that keeps dots & commas is probably `urlalias_iri`, is it not @arnebratt ?

**Comment by arnebratt** [comment]
Right, sorry, my mistake. I didn't realise that we are using `urlalias_iri` on legacy. And `urlalias` is the default on Symfony. I didn't find a way to change the SlugConverter defaults though, is this documented somewhere?

**Comment by andrerom** [comment]
afaik no, you got reply on this on slack or?

**Comment by arnebratt** [comment]
Yes, thank you. Just to summarize for anyone interested, I solved it by simply overriding the following service definition, adding the second argument to get 'urlalias_iri'.

services:
    ezpublish.persistence.slug_converter:
        class: %ezpublish.persistence.slug_converter.class%
        arguments:
            - @ezpublish.api.storage_engine.transformation_processor
            - transformation: 'urlalias_iri'

@bdunogier think a Compiler Pass solution would be better. I also tried this, but couldn't make it work on my limited knowledge. It would also be a more complex solution.

And just to get back to topic, I approve of the pull request. :)

**Comment by bdunogier** [comment]
> imo, way how it is working now is a BC break :smiling_imp:

Yes, you're right. But the fact is that there are uris that were generated so far on platform with this issue. It means that for those updating from an existing platform version, uris may change without them doing anything. That's where it breaks some kind of BC.

But I can live with that.

+1, but with a review from @andrerom or @glye as well.

**Comment by bdunogier** [comment]
Ping @pspanja. Anything we need to know about this ?

**Comment by andrerom** [comment]
Open:
- `urlalias_compat` still uses it
- And I'd also like to know what the intention was on this @pspanja

**Comment by pspanja** [comment]
> And I'd also like to know what the intention was behind punctuation_normalize

That makes two of us, TBH it looks like search normalization rules should not be there.

**Comment by glye** [comment]
This needs testing, for sure. Interestingly, I've been trying to break `SlugConverterTest` by messing with the input/output strings, but it passes no matter what I do :confused:

**Comment by glye** [comment]
@clash82 I can add tests and fix ´urlalias_compat´.

**Comment by clash82** [comment]
> I can add tests and fix ´urlalias_compat´.

@glye cool, thank you :)

**Comment by bdunogier** [comment]
:+1: @glye

**Comment by glye** [comment]
New PR with tests: https://github.com/ezsystems/ezpublish-kernel/pull/1638

**Pull request closed without merging**
