### PR TITLE
EZP-30459: Autoregister Nameable on Field Type definition

### PR DESCRIPTION
**Pull request by mikadamczyk**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-30459](https://jira.ez.no/browse/EZP-30459)
| **Improvement**|no
| **New feature**    |no
| **Target version** | `master`
| **BC breaks**      |no
| **Tests pass**     | yes
| **Doc needed**     | yes

**TODO**:
- [ ] Implement feature / fix a bug.
- [ ] Implement tests.
- [ ] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

### CODE REVIEW

**Comment by adamwojs** [comment]
> This needs to be done by auto-tagging and $container->registerForAutoconfiguration.

**No.**  Tags with mandatory attributes cannot be auto-tagged or autoconfigured. Excerpt from the Symfony documentation:

> This does not work for all tags. Many tags have required attributes, like event listeners, where you also need to specify the event name and method in your tag. Autoconfigure works only for tags without any required tag attributes, and as you read the docs for a feature, it'll tell you whether or not the tag is needed. You can also look at the extension classes (e.g. FrameworkExtension for 3.3.0) to see what it autoconfigures.

https://symfony.com/doc/current/service_container/3.3-di-changes.html#auto-tagging-with-autoconfigure

**Comment by alongosz** [comment]
> > This needs to be done by auto-tagging and $container->registerForAutoconfiguration.
> 
> @alongosz **No.** Tags with mandatory attributes cannot be auto-tagged or autoconfigured. Excerpt from the Symfony documentation:

Then we have bigger design issue. Current implementation of compiler pass is not acceptable to me.

**Comment by adamwojs** [comment]
> Then we have bigger design issue. Current implementation of compiler pass is not acceptable to me.

Could you please elaborate your concerns?

**Comment by mikadamczyk** [comment]
Can we proceed with this task? @alongosz @ViniTou @pawbuj @Nattfarinn @webhdx

**Comment by alongosz** [comment]
Guys... the entire implementation of `FieldTypeNameableCollectionFactory` is broken, this is why it is so confusing.

First and foremost all Field Types need to have Nameable implementation. Right now if a FT doesn't implement it, `NameableFieldTypeFallback` is used which relies on `FieldType::getName` which is deprecated and is going to be removed. So relying on that behavior is pointless.

I can't give you exact solution without digging into it deeper myself. 
Auto-configuration indeed might not be possible because of `alias` parameter. 

Trying a few things now, if they fail we'll go back to this solution for now and attempt to handle it properly when solving [EZP-30529](https://jira.ez.no/browse/EZP-30529).

**Comment by mikadamczyk** [comment]
Closed in favor of [https://github.com/ezsystems/ezpublish-kernel/pull/2661](https://github.com/ezsystems/ezpublish-kernel/pull/2661)

**Pull request closed without merging**
