### PR TITLE
EZP-23471: Refactored Search engines DIC factories to avoid fake services injection

### PR DESCRIPTION
**Pull request by lolautruche**

### CODE REVIEW

**Comment by lolautruche** [comment]
I think we could even get rid of the factory and do everything in the DIC extension.

**Comment by andrerom** [comment]
> I think we could even get rid of the factory and do everything in the DIC extension.

cool, less is more :)

**Comment by lolautruche** [comment]
Adapted Solr config as well.

Review ping @andrerom @bdunogier @pspanja

**Comment by andrerom** [comment]
Nice, but anything needed for LegacySearchEngine?

**Comment by pspanja** [comment]
@andrerom not for the subject here, I'll test everything again when this is merged to https://github.com/ezsystems/ezpublish-kernel/pull/1210.

**Comment by andrerom** [comment]
ok, +1 then :)

**Comment by lolautruche** [comment]
I found nothing relevant for legacy search engine.

**Comment by lolautruche** [comment]
OK to merge @pspanja?

**Comment by pspanja** [comment]
@lolautruche +1, go ahead :)

**Comment by pspanja** [comment]
This is now included in https://github.com/ezsystems/ezpublish-kernel/pull/1224, closing.

**Pull request closed without merging**
