### PR TITLE
EZP-28972: RichText Custom Tag align attribute is not present in Tag template

### PR DESCRIPTION
**Pull request by alongosz**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-28972](https://jira.ez.no/browse/EZP-28972)
| **Required by**     | ezsystems/ezplatform-demo#75
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `7.1`
| **BC breaks**      | no
| **Tests pass**     | TBD
| **Doc needed**     | no

The HTML5 output converter responsible for rendering RichText Custom Tag frontend template tried to get align attribute from `xlink` namespace. The correct one is `ezxhtml`.

**TODO**:
- [x] Fixed incorrect XML namespace for align attribute of RichText Custom tag template Renderer.
- [x] Identify if and what tests can be implemented for this.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by alongosz** [comment]
> Sounds good to me. It didn't make sense that it used xlink ?

Yep, I've investigated this yesterday to check if I didn't break anything here, but indeed I don't see a reason to use `xlink` there.

Any POV @andrerom @adamwojs ?

**Comment by adamwojs** [comment]
I don't see `align` attribute in xlink specyfication*, so indeed correct namespace should be `ezxhtml`. 

* _checked before first coffee_

**Comment by alongosz** [comment]
@andrerom @adamwojs @bdunogier I've updated unit test for Custom Tag to check for `align` attribute. It wasn't tested at all
The PR is complete now :)

**Comment by alongosz** [comment]
Merging, decided with QA that it will be tested when ezsystems/ezplatform-demo#75 gets tested.

**Pull request merged**
