### PR TITLE
EZP-24673: Implement languageFilter for Location Legacy Search Engine

### PR DESCRIPTION
**Pull request by blankse**
JIRA: https://jira.ez.no/browse/EZP-24673

### CODE REVIEW

**Comment by blankse** [comment]
I see the fieldFilters will be renamed to languageFilter. I will change this.

**Comment by blankse** [comment]
review ping @andrerom @bdunogier @pspanja

**Comment by blankse** [comment]
Rebased because of https://github.com/ezsystems/ezpublish-kernel/pull/1369

**Comment by blankse** [comment]
@andrerom I rename also fieldFilters to languageFilter and correct PHPDocs. This was lost in the last commits.

**Comment by andrerom** [comment]
+1, ping @pspanja

**Comment by pspanja** [comment]
Looks good to me, +1

**Comment by pspanja** [comment]
Thank you @blankse!

**Pull request merged**
