### PR TITLE
EZP-30698: Replaced multiline parameter doctypes with oneliners

### PR DESCRIPTION
**Pull request by Nattfarinn**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-30698](https://jira.ez.no/browse/EZP-30698)
| **Improvement**| yes
| **New feature**    | no
| **Target version** | `7.5`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

**TODO**:
- [x] Implement feature / fix a bug.
- [x] ~Implement tests.~
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by alongosz** [comment]
Guys, do you think it's worth to target this to 7.5 for maintenance reasons?

**Comment by ViniTou** [comment]
@alongosz 
From my POV, yes, you did it for short array syntax and this is similar (if not identical) case to it.

**Comment by Nattfarinn** [comment]
@alongosz Target is now `7.5`

**Comment by alongosz** [comment]
Thank you @Nattfarinn :tada:

**Pull request merged**
