### PR TITLE
IBX-610: Implemented InMemory cache for remaining LocationHandler methods

### PR DESCRIPTION
**Pull request by mateuszbieniek**
JIRA: https://issues.ibexa.co/browse/IBX-610

This PR implements InMemory cache for remaining methods in LocationHandler to further reduce the number of calls made to Redis.

### CODE REVIEW

**Review by alongosz — APPROVED** [review]

**Review by Steveb-p — APPROVED** [review]

**Review by ViniTou — APPROVED** [review]

**Review by micszo — APPROVED** [review]
QA Approved on eZ Platform EE v2.5.20 with diff.
Tested with tagaware.filesystem and redis cache pool.

**Comment by adamwojs** [comment]
Could you please merge up changes @mateuszbieniek ?

**Comment by mateuszbieniek** [comment]
merge up PR:
https://github.com/ezsystems/ezplatform-kernel/pull/203

**Comment by mateuszbieniek** [comment]
1.2: https://github.com/ezsystems/ezplatform-kernel/commit/0d0bff056dde1fcffc30583faa22f70b0d6fcf1b
1.3: https://github.com/ezsystems/ezplatform-kernel/commit/04cd5cafb5ebac48889d1165441168f930ec7d89
master: https://github.com/ezsystems/ezplatform-kernel/commit/1c17a8f55aa8231f0ff3070f37ff6c665a2b89bb

**Pull request merged**
