### PR TITLE
EZP-28269: Fixed inconsistent creating of eztime fromTimestamp

### PR DESCRIPTION
**Pull request by alongosz**
| Q | A |
|---|---|
| **Issue** | [EZP-28269](https://jira.ez.no/browse/EZP-28269) |
| **Type** | Bug |
| **BC break** | hope not => maybe => yes |
| **Target branch** | `6.7` |

We've discovered inconsistent behavior of `Time\Value::fromTimestamp` with respect to `DateAndTime\Value::fromTimestamp`. The former one creates Time Value relying on PHP server timezone setting, while the latter - creates Value w/o timezone (or using UTC).

See [`Time::fromTimestamp`](https://github.com/ezsystems/ezpublish-kernel/blob/v6.7.6/eZ/Publish/Core/FieldType/Time/Value.php#L89-L90) and [`DateAndTime::fromTimestamp`](https://github.com/ezsystems/ezpublish-kernel/blob/v6.7.6/eZ/Publish/Core/FieldType/DateAndTime/Value.php#L71).

There is [a difference](http://php.net/manual/en/datetime.settimestamp.php#117238) in setting `\DateTime` value using constructor `"@{$timestamp}"` time string and calling `setTimezone`. The latter one takes into account server timezone.

AFAICS Time Value should be an absolute number of seconds elapsed since midnight, thus cannot be timezone-dependent. This PR provides the fix for that. If you take a look at the original [unit tests](https://github.com/ezsystems/ezpublish-kernel/blob/v6.7.6/eZ/Publish/Core/FieldType/Tests/TimeTest.php#L149-L171) there's also an inconsistency. First three tests shows that this should be timezone-independent, however the other tests provide a fix for changing timezone. I'm assuming the latter behavior is incorrect, thus fixed here, but I need some confirmation.

**TODO**:
- [ ] Get feedback on correct behavior
- [x] See if Travis agrees.
- [x] Fix `Time\Value::fromTimestamp` to be timezone-independent
- [x] Fix unit tests.
- [x] Fix integration tests.

### CODE REVIEW

**Comment by gggeek** [comment]
"BC break" => most likely yes :-P

I all for consistency, but I am keenly aware that this is a subject where previous work was already done to fix bugs (or perceived bugs) reported by customers...

**Comment by alongosz** [comment]
Thanks @gggeek for your feedback! The question is - should we consider fixing buggy behavior a BC break? ;)
We have a good opportunity to fix it on `7.0` only, so we need to decide what to do with this.
POV ping @lserwatka @andrerom @bdunogier @adamwojs @kmadejski @natanael89 @Nattfarinn @webhdx

**Comment by glye** [comment]
I am sure there are valid use cases either way, so it's a matter of choosing the most common and/or "correct" case, and documenting it well. Or supporting both. There's a logical disconnect: Unix timestamps are UTC-based, while Time can be used in a timezone-less way, but not necessarily.

Let's say I have an event calendar, and I create an online event that happens every day at 13:37 my time. That's a fixed time, and should be displayed with a different value for users in Mongolia and in Micronesia. (Not sure if `fromTimestamp()` would be relevant for that, though.)

However if my international news site displays todays day of the week based on when midnight is, that's a relative time and the changeover must happen at 00:00 local time wherever you are.

**Comment by alongosz** [comment]
Ok, so clearly change for now for `7.0`. See #2159.

**Comment by alongosz** [comment]
> Let's say I have an event calendar, and I create an online event that happens every day at 13:37 my time. That's a fixed time, and should be displayed with a different value for users in Mongolia and in Micronesia. (Not sure if fromTimestamp() would be relevant for that, though.)

Hmm, so that's for the code handling value to decide. Current behavior didn't work like that either, it depended on server timezone, not local one.

We've decided internally that for `7.0` the correct behavior is to set and display timezone-independent value time.

Fixed in `7.0` by #2159 via 9ab2e6e

**Pull request closed without merging**
