### PR TITLE
[Travis] Bumped dist to Xenial to use MySQL 5.7

### PR DESCRIPTION
**Pull request by alongosz**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | n/a
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `7.5` and `master (8.0)`
| **BC breaks**      | no
| **Tests pass**     | TBD
| **Doc needed**     | no

According to the doc [we require at least MySQL 5.7](https://doc.ezplatform.com/en/2.5/getting_started/requirements/#recommended-setups) in version 2.5, so we should align that on Travis as well.

The background reason for this change is faulty default configuration of MySQL 5.6 which leads to unsolvable otherwise false negative test results in #2621.

`Xenial` supports MySQL 5.7 out of the box, so we've decided to bump entire dist. `Trusty` is quite old, so it's the highest time.

**TODO**:
- [x] Wait for Travis to confirm.
- [x] Do a TMP cherry-pick into #2621 to see if that solves the issue
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by ViniTou** [comment]
I think we just found out why we are still on mysql5.6 on travis.

```
E: Unable to locate package mysql-server-5.7
E: Couldn't find any package by glob 'mysql-server-5.7'
E: Couldn't find any package by regex 'mysql-server-5.7'
E: Unable to locate package mysql-client-core-5.7
E: Couldn't find any package by glob 'mysql-client-core-5.7'
E: Couldn't find any package by regex 'mysql-client-core-5.7'
E: Unable to locate package mysql-client-5.7
E: Couldn't find any package by glob 'mysql-client-5.7'
E: Couldn't find any package by regex 'mysql-client-5.7'
```

**Comment by ViniTou** [comment]
@alongosz 

image

**Comment by alongosz** [comment]
Great work @ViniTou :tada:

**Comment by alongosz** [comment]
Merging to unblock #2621. If anyone has further remarks please ping us, we'll do a follow-up.

**Pull request merged**
