### PR TITLE
Alternative QueryController approach

### PR DESCRIPTION
**Pull request by bdunogier**
> Story: http://jira.ez.no/browse/EZP-24624
> DemoBundle implementation : https://github.com/ezsystems/DemoBundle/pull/189

This is an alternative approach to what was done in #1460.

The goal is still to facilitate viewing of a list of content / locations. #1460 was based on a new "view" (as in content view or block view), where a QueryType got executed, and the results assigned to a template. But upon implementation, it appeared to be tedious, on simple use cases like a list of children.

In this approach, a built-in `QueryController` is added. It can be used in any `content_view` config to add the results of a `QueryType` to the view:

```yaml
system:
    default:
        content_view:
            full:
                blog:
                    match:
                        Identifier\ContentType: [blog]
                    controller: 'ez_query:contentAction'
                    template: 'eZDemoBundle:full:blog.html.twig'
                    params:
                        query: 'DemoBundle:BlogPosts'
                        queryParameters:
                            blogPathString: @=location.pathString
                        variable: blog_posts_list
                        enablePager: true
```

The view is configured to use `ez_query:contentAction`. The controller action runs the QueryType specified as `query`, and sets the results to the variable specified as `variable`.

The elements from `queryParameters` are passed to the QueryType's `getQuery()` method.
The expression language can be used in any queryParameter by prefixing the value with `@=`. The expression is given the `view`, the `location` and the `content`. This makes it easy to pass any property from those value objects to generate the query.

The `enable_pager` parameter (not implemented yet) will pass the search results as a PagerFanta pager object. If set to false, an array will be passed instead.

### TODO
- [ ] BDD
- [ ] Pager support
- [ ] Extract to another package/bundle
- [ ] Convert to a listener based approach, with the query parameters interpreted from the content_view level

### CODE REVIEW

**Comment by joaoinacio** [comment]
Nitpick: Doesn't look like it has anything to do with https://jira.ez.no/browse/EZP-24264 : LDAP authentication ;)

**Comment by bdunogier** [comment]
Thank you @joaoinacio :)

**Comment by andrerom** [comment]
I think this is right direction, even if there are some things that don't appear clear, like how queryParameters is translated to a query, and how the convention is. Also would like to see how this might look with a built in children query type to make sure this can be used as opposed to creating a specific one per type. Sane defaults would also be great to avoid having to specify everything, for instance variable being "list" by default

**Comment by bdunogier** [comment]
Added an example in the last commit, @andrerom.

**Comment by andrerom** [comment]
thanks, and great to see it handling sorting based on the location transparently, a developer itch with the Search API from several.

**Comment by bdunogier** [comment]
> a developer itch

"itch" is a good choice of words :-)

**Comment by andrerom** [comment]
*Side: On that topic I still think Location Search API should have taken Location as an argument somehow as well to either do list *(children)* or tree searches, if so it could take sorting into account even down there. This was a longer discussion on this back when it was added.*

**Comment by bdunogier** [comment]
Will reopen with a cleaned up version.

**Pull request closed without merging**
