### PR TITLE
Fixed: EZP-23896: ezimage rendered with absolute URL

### PR DESCRIPTION
**Pull request by patrickallaert**
Fixes: https://jira.ez.no/browse/EZP-23896

Originally [discussed on share.ez.no](http://share.ez.no/forums/ez-publish-5-platform/how-to-instruct-ez-publish-5-to-work-with-relative-url-on-ezimage-rendered-images).

### CODE REVIEW

**Comment by lolautruche** [comment]
+1

@lsmith77 @makasim Is it ok to return an URL not having the base URL?

**Comment by lolautruche** [comment]
Tests need to be updated though :wink:

**Comment by makasim** [comment]
It is done on purpose, by design imagine bundle always returns absolute url. You can add a [proxy decorator resolver](https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Cache/Resolver/ProxyResolver.php). Which replaces the host with proxy one. I used it to replace s3 url to cloud front one for example

**Comment by lolautruche** [comment]
@makasim *on purpose* is fine, but can you please describe what is the purpose? :-)

**Comment by makasim** [comment]
it was a year ago. I will try to recall what was it.

**Comment by lolautruche** [comment]
Thanks :)

**Comment by lolautruche** [comment]
Did you manage to remember @makasim ?

Ping @patrickallaert for tests :)

**Comment by peterkeung** [comment]
Ping @dfritschy

**Comment by dfritschy** [comment]
Thanks @patrickallaert for this PR which is strongly support. IMHO the current behaviour is false by design. @lolautruche any support fort his?

**Comment by lolautruche** [comment]
Ping @andrerom @bdunogier

**Comment by andrerom** [comment]
+1 (also for backport), but @bdunogier would be the one to know how this mixes with other assumptions other places (REST, and other recent changes).

**Comment by peterkeung** [comment]
Any progress on this?

**Comment by emodric** [comment]
Also +1 :)

@peterkeung You can just override the IO repository for now and make the `getBaseUrl` return empty value :)

**Comment by tharkun** [comment]
@patrickallaert @lolautruche @andrerom : Is there any news about this issue ?

Current behavior forbids any use of CDN to deliver image alias.

**Comment by bdunogier** [comment]
Hi there. It's been a while since this has been discussed, but I'm back after some analysis.

I don't really agree with this change. If I'm not mistaken, it fixes the CDN issue by allowing a page with a different URL (akamai for instance) to load an image from the same rewritten host without changing the source.

What bothers me is that as said by @makasim, Imagine's Resolvers are _meant_ to return absolute image urls. I have on my side tested a ProxyResolver, as discussed above, and it did get the job donc, _to some extent_. The main problem is that it won't work by default, as platform's repository resolver is passed as is in our services, meaning that we can't cleanly override it with the proxy.

I'd rather fix this _through_ imagine, since we use it, rather than _against_ it. What we could do:
- add configuration to ezplatform that leverages the proxy resolver
  - boolean to include or not the host in images URL. Not including them can be done using a ProxyResolver configured with an empty URL (`http://site.com/var/storage/images...` is resolver to `/var/storage/images/...`)
  - allow to define a host / list of hosts that randomly replace the original one (base feature of the ProxyResolver)
- by means of container extension, dynamically change the cache resolver to the proxy if applicable (strip or replace host).

**Comment by dfritschy** [comment]
Maybe we should get back to the root of this issue, as outlined by @patrickallaert in http://share.ez.no/forums/ez-publish-5-platform/how-to-instruct-ez-publish-5-to-work-with-relative-url-on-ezimage-rendered-images:

> The web servers are serving content via HTTP and in front of them, a dedicated Cisco Ace load balancer is in charge of (1) load balancing across servers, (2) encrypt the content between the load balancer and the browser via HTTPS.

> If relative URLs were used exclusively, we wouldn't have the "mixed content" issue we are facing on https://www.lescheminsdeferengagent.be/.

To my knowledge `imagine` is the only component used by eZ Platform that uses absolute URLs including hosts, causing all kind of problems. IMHO the current behaviour is false by design.

**Comment by makasim** [comment]
It is possible to get relative ursl by adding an event listener on post resolve event. The listener is responsible for converting absolute urls to relative.

**Comment by bdunogier** [comment]
@makasim if we chose not to use the ProxyResolver, we have plenty of options.

Another one would be to remove the host we add ourselves (this PR), and use io URL decorators. The feature's already here, even though it does duplicate stuff Imagine does :(

**Comment by rudzboy** [comment]
Hello guys ;)
Any reason why this PR has not been merged ?

**Comment by tharkun** [comment]
we are highly encouraged to migrate websites from http to https. This is a huge issue.

**Comment by andrerom** [comment]
@bdunogier Maybe you can make sure this ends up in next sprint so it's handled from PM perspective at least, and we can see if anyone form thridline might be able to do the implementation once spec is done.

**Comment by crevillo** [comment]
Sorry to enter here, but let me add something:

We experienced the same issue and even another similar one. 

First issue:
  - we were in https but images url were built with http
Second issue
 - in the platformui, translations js were loaded via http and not https. 

In both cases our solution was more symfony oriented. basically we followed this http://symfony.com/doc/2.8/request/load_balancer_reverse_proxy.html

Our situation was exactly the same as @patrickallaert explains in the share.ez.no topic. 
`The web servers are serving content via HTTP and in front of them, a dedicated Cisco Ace load balancer is in charge of (1) load balancing across servers, (2) encrypt the content between the load balancer and the browser via HTTPS.`

In our case, was amazon elb. frontend servers behind was http and elb with the job of the encription. 

So, yes, returning relative urls for images can be an idea that will solve this, but i don't know if we could still have other places that won't be covered here. 

In our case, we were getting `http://`  like urls in this line, and this was implying also having mixing https and http content. 
https://github.com/ezsystems/PlatformUIBundle/blob/master/Resources/views/PlatformUI/shell.html.twig#L65

So, i'd say this could fix part of the problem but not all the problems...

**Comment by andrerom** [comment]
@crevillo To clarify: So what you are saying making sure the right http headers are taking into account form proxy / load balancer / .. solves this issue and the other cases where url's are rendered absolute?

If so I suggest we close this and open issue to document how ez Platform is configured behind load balancer / SSL, separate page for this to reflect this.  I was planning to handle this with support team anyway as a lot of partners gets into issues on this.

**Comment by crevillo** [comment]
@andrerom yes. that's it. at least that worked for us, not only in a ez platform project but also in a sylius project.

**Comment by andrerom** [comment]
@tharkun / @dfritschy / @emodric / @rudzboy This works for you also? If so that is the proper way to do it from what I can see.

**Comment by gggeek** [comment]
Can we have both? :-P
1. make sure that all urls which are generated "by ez" are relative
2. more docs about making sure that absolute urls take into account proxies in front of ez

Given the move to a 100% https web that is happening this very days, 2 becomes more important, but it still is much more involved than 1, which would solve a lot of cases.

In order for 2 to work good, you have to, as a non-inclusive example:
- have rev. proxy tell sf what was original port
- have rev. proxy tell sf what was original protocol
- have rev. proxy tell sf what was original customer IP
- make sure that none of this info can be injected by customer, ie. reverse proxy strips it before adding it (common case: sf obeys 2 distinct headers telling it which was user source IP... easy to set up the rp to only handle one and forget the other)

**Comment by crevillo** [comment]
> make sure that all urls which are generated "by ez" are relative

depending on what you consider generated "by ez". :P in this case is not ez which is generating the url, but liip library. we are trying here to twek that,
in the case of platform ui, link is coming from an external bundle... 

To have everything solved in one way, other way could be extend the way symfony deals with the `url`...

**Comment by andrerom** [comment]
As @crevillo says, most of the parts generating absolute urls are not made by eZ. So option 1 is not an option in the short term, as it would need a serious amount of convincing across several packages used by eZ, by someone who has the time and energy for that.

**Comment by gggeek** [comment]
Well your devs, you do prioritization and time allocation.

But I have a slightly different POV: to me the urls generated for images are part of the 'ez core' functionality, and should not expose directly the ez developer to the api/warts of the lib used to implement that. So that if in the future a different package is adopted to implement that, the api used by the ez developer does not change.

I am not sure how many 'other bundles' are used by eZ to generate urls in other places.

**Comment by dfritschy** [comment]
@andrerom I would agree with @gggeek that we need both. In MHO generating absolute URLs is not a feature, but a bug.

**Comment by crevillo** [comment]
I am not agree that all urls should be relative by default. In fact i would like that when i have multisite, host mapping and i add a link to other siteaccess, the domain for that siteaccess will be returned in that url too...

**Comment by crevillo** [comment]
I'm not agree this being a bug either. Probaly a nice to have, but not a bug. 
Further more, you could have your images in other server, and in those cases, you will need absolute in any case.

**Comment by dfritschy** [comment]
@crevillo Cross-domain routing is another topic, certainly valid, but not related to this. Having images on a different server, however,  is certainly a common use case, and can be handled by Liip Imagine Bundle, see https://symfony.com/doc/master/bundles/LiipImagineBundle/cache-resolver/aws_s3.html. This ability is most certainly the cause of our grief with absolute URLs within an eZ Platform installation...

**Comment by andrerom** [comment]
Ok, I see that there is definitely a clear pain point here. But realistically we will need to think in two tracks here:
- short term: doc _(better surface how to configure symfony behind proxy / load balancer)_
- mid / long term once PM priorities it*: Epic** for handling this better


\* _And once there is Engineering capacity to do so, currently there is not._
\*\* _This is a collection of several stories and tasks across eZ and potently third party packages, that together form a missing relative url feature in Platform._ 

Ok?

**Comment by crevillo** [comment]
sounds good, @andrerom .

**Comment by gggeek** [comment]
@crevillo sorry by I agree with Donat on this:
- having ability to have multi-domain / separate domain added to the links to images is good, but it is a separate story
- defaulting to relative urls should not hamper the possibility to easily configure the system for the more complex scenarios

**Comment by tharkun** [comment]
In fact, there is already something in Symfony that handle urls for asset. If we want to keep Symfony way of thinking, I think url with DNS for image should not be handle by eZ.

eZ Publish Core should stop itself at relative url for picture. Right now, my client is using AWS, and we're using CDN with a single DNS for all websites.
As in Symfony, we implement the twig operator asset to use the CDN. But without this patch, it does not work because the url already has a host.


This said, it is true that there is an big issue also when Varnish call the backend that can generate url without https (in case you have incoming trafic handled by apache/nginx, then calling Varnish, which use apache/nginx as backend).
We need to verify that the configuration and documentation is clear about that.

**Comment by emodric** [comment]
I definitely agree that relative path should be a default. We've been running a patched version `IORepositoryResolver::getBaseUrl` for ages to return the relative path for the images. In my opinion, it is not eZ Platform's job to deal with scheme for assets, when Symfony can do the same job for us.

Symfony Asset component allows defining various CDN configurations for use by `asset` Twig function, maybe we should just use that.

**Comment by crevillo** [comment]
Sorry @emodric , i don't get you here... you say
`In my opinion, it is not eZ Platform's job to deal with scheme for assets, when Symfony can do the same job for us.`
show, why we should solve it in the ez platform part?

**Comment by emodric** [comment]
> why we should solve it in the ez platform part?

Why we should solve what? eZ Platform should just return the relative URL for the images and files by default and be done with it and that will cover 95% of usecases.

Anything else (configuring assets for different domains and CDNs) is optional and as already mentioned a separate issue. BUT, since Symfony can already do that for us with Asset component, there's no reason to deal with it directly in eZ Platform, at least not immediately.

**Comment by crevillo** [comment]
well, the creator of the liip imagine bundle thinks in other way. 
https://github.com/liip/LiipImagineBundle/issues/625#issuecomment-125976400

Further more, you're saying here that everything from ez platform should be relative links, and this can lead to other issues. For example, seo ones...

http://www.dirigodev.com/blog/seo-web-best-practices/relative-vs-absolute-urls-seo/

```
Image search can also benefit from specifying absolute image URLs by asserting ownership in the image search results, thereby reducing duplicates from competing sites, particularly in cases where they're hotlinking to original image content on your site.```

**Comment by emodric** [comment]
So it's better to force absolute URIs because someone said so, without the possibility to use relative URIs, than to default to relative and let anyone configure absolute URI as they see fit?

Maksim from Liip Imagine doesn't support the relative URLs because in current state of Liip Imagine bundle it's not easy to do so. That doesn't mean it's wrong and I have to agree with @dfritschy and @gggeek here.

**Comment by crevillo** [comment]
No, but is not better to use relative urls because you said so either :). 

My point is at that time we're relying on liip imagine bundle to build those urls, right? if we don't like it, then let's switch to other library. 

If we like it, then, as liip is now retuning absolute urls, keep ezplatform returning absolute urls and if you want, extend it to have it relative urls. 

The idea of having symfony here is also give the ability to add more bundles to a ezplatfor install, right? this bundles could also be using liip as dep and then in your app you could reach a situation where you could have relative and absolute url even for the same image.

**Comment by emodric** [comment]
> No, but is not better to use relative urls because you said so either :).

It's not, but my point is that 95% of usecases will actually benefit from relative URIs because otherwise by default they need to go through convoluted process of setting up the correct support for reverse proxies and so on just to have https. The need for relative URLs is obviously there, hence this PR and a number of people commenting.

> My point is at that time we're relying on liip imagine bundle to build those urls, right? if we don't like it, then let's switch to other library.

Getting relative URIs takes one line of code in `IORepositoryResolver`, so Liip Imagine Bundle does not force us to do anything.

> The idea of having symfony here is also give the ability to add more bundles to a ezplatfor install, right? this bundles could also be using liip as dep and then in your app you could reach a situation where you could have relative and absolute url even for the same image.

Yes, and that's where you'd use Symfony Asset component, which will not be possible if eZ returns absolute URIs. If anything, using abosolute URIs will hinder the possibility to manipulate URLs as you see fit.

**Comment by crevillo** [comment]
Convoluted process? Is only a line of code in the app.php or, even, you can do it at nginx level. i don't see that a big deal as is well documented by symfony. 

Ok, let's return relative urls for images. Now, another question. If my, as dev, want to use `url` in my twigs, are you sayin also that eZ Platform should return me a relative url in this case? 

If you say yes, to me is a bad idea, as every symfony dev in the world knows url is for absolute. 
If you say no, then, again, modifying ez platform to have relative urls for images won't fix the real problem here. The problem is we are having non secure urls mixed with https. and to solve this you will need to deal with proxy before or later...

**Comment by emodric** [comment]
> Ok, let's return relative urls for images. Now, another question. If my, as dev, want to use url in my twigs, are you sayin also that eZ Platform should return me a relative url in this case?

eZ Platform should have relative URI as a path in an image field value, so you use `{{ absolute_url(asset(...)) }}` in your Twig templates, so that call can generate the correct absolute URI. If eZ Platform were to return absolute URIs, you're loosing the possibility to use `path()`.

And if you use `url` or `absolute_url` in your Twig templates, you are willingly generating absolute URIs and you should know how to make them generated with HTTPS.

The point of this PR is to have sensible defaults that work in majority of usecases, and generating absolute URIs by default does not.

**Comment by andrerom** [comment]
Guys, you are both right here:
- ideally url should be relative so we can all pass it to standard symfony features
- however as images can be served from other systems like s3 they where most likely designed to always be absolute to avoid mixing forms
- on top of that we can't really deal with this right now, if someone wants to start process of starting discussion on our upstream packages or suggest others we can migrate to in the future, you are more then welcome, it will lower the barrier for us to get this prioritized in the future.
- and as said before there are ways to fix the http / https mixed content issues by making sure the http heads from load balancer / proxy is safely taken into account, and we need to better document that. 

So for now locking this discussion for a bit of cool down. As it's somewhat of an bikeshedding, we all more or less agree on the house. And I suggest relevant PM (@bdunogier) takes the torch here and start to define a epic that could make sense, optionally reaches out to you if something is still unclear, and gets back to this thread when there is something to review.

**Pull request closed without merging**
