### PR TITLE
Implement: EZP-24434: separate core for indexing always available languages

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-24434

Depends on https://github.com/ezsystems/ezpublish-kernel/pull/1287

This adds the option to configure separate Solr index to index translations that are always available.

Motivation: in multicore setup, in order to support always available fallback, since always available flag is defined on the Content level, search query must be distributed towards **all** configured cores. This has obvious performance penalties. Having single core holding all always available translations, we can limit the number of cores that are targeted for a specific language configuration.

Always available core is configured like this:

```yml
ez_search_engine_solr:
    ...
    connections:
        connection1:
            ...
            cluster:
                content:
                    translations:
                        *: endpoint1
                        eng-GB: endpoint2
                    always_available: endpoint2
                location:
                    translations:
                        cro-HR: endpoint3
                        eng-GB: endpoint4
                    always_available: endpoint2
```

It is possible to index always available translations in the core that is also mapped for translation(s), for Location and Content type documents.

#### TODOs

- [x] move asterisk wildcard configuration to the separate key (from https://github.com/ezsystems/ezpublish-kernel/pull/1287)
- [x] change indexing always available translations to indexing main translations

### CODE REVIEW

**Comment by pspanja** [comment]
This implements the feature, but it seems that it would be better if we had *main language* index instead of *always available* index. When no language configuration is passed, we target main language translations. That is an usual case for using search with filtering on internal data structure only (so not fulltext and field criteria/sort). For that, again, targeting all indexes is required, since we don't have everything available on the single index. Having main language translations in a single index would enable both targeting single additional index for always available fallback, and single index when using search without language configuration.

Opinions on the above?

Review ping @andrerom @paulborgermans @bdunogier @lolautruche

**Comment by pspanja** [comment]
I'm going to continue on the remaining todos. Main language index seems acceptable since it would also be optionally configured, and one would use it with a setup with multiple cores, where resources will probably be a secondary concern.

**Comment by andrerom** [comment]
looks like a sensible direction

**Comment by pspanja** [comment]
Closing in favor of https://github.com/ezsystems/ezpublish-kernel/pull/1305.

**Pull request closed without merging**
