### PR TITLE
Fix [EZP-25183] eZ Logo looks weird in symfony 2.8 debug toolbar

### PR DESCRIPTION
**Pull request by crevillo**
Fixes https://jira.ez.no/browse/EZP-25183

Tests
------
Manual test. 
Here's a screenshoot before this patch... 
ez-logo-before-patch
Here's another one with this patch applied
ez-logo-after-patch

### CODE REVIEW

**Comment by crevillo** [comment]
ping @bdunogier @dpobel @yannickroger @andrerom

**Comment by andrerom** [comment]
How does it now look in 2.7? *(We have a bug with 2.8 as reported by Edi, so currently we are limiting it to ~2.7.0)*

**Comment by crevillo** [comment]
gonna try it @andrerom and i'll be back with the screenshoots.

**Comment by crevillo** [comment]
@andrerom, looked better with sf 2.7. here are the screenshoots. 
before-patch
after-patch

But still i think patch is valid. Thing is the original image is 17 px width but in the twig template we're forcing it to have 28...

**Comment by crevillo** [comment]
The reason why it looked better with sf 2.7 is there was a css rule setting width:auto to our image.
```css
.sf-toolbarreset img {
    width: auto; 
    display: inline;
}
``` 
if disabling that rule the logo gets ugly.
without-widt-auto

**Comment by andrerom** [comment]
Ok, Lets do this then ;)

**Pull request merged**
