### PR TITLE
EZP-26742 with fix: add forgotten USE statement

### PR DESCRIPTION
**Pull request by gggeek**

### CODE REVIEW

**Comment by gggeek** [comment]
Follow up to https://github.com/ezsystems/ezpublish-kernel/pull/1853

**Comment by yannickroger** [comment]
Please let's not merge this without QA testing (like it was done for the other one).

**Comment by andrerom** [comment]
@gggeek path does something else then description here, can you update title and desc what you are actually fixing?

If it was just the use statement we would have merged a month ago.

**Comment by gggeek** [comment]
@andrerom  it is a bit weird, tbh: given the fact that PR #1853 was merged, I would have expected that the only diff left in this PR would be the one line with the use statement.

I have had a similar thing happening to me this week on another project: the symptoms are 'git does not seem to pick up any more changes which are pushed to the two branches involved in a PR, after the PR has been created'.

Anyway: the Jira comment ( https://jira.ez.no/browse/EZP-26742?focusedCommentId=205710&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-205710 ) also mentions a problem with merging this.
Regardless of whether the cause of the problem is in Github or in Git snafus on my side, I'll try to clean this PR or create a new one.

**Comment by pcardiga** [comment]
@gggeek when QA tested this PR, it seems that only the "use" statement part of the PR was missing from latest master of ezpublish-kernel. The rest was already there, thus the failure to apply the fix in a cleanly way.
Nevertheless, the good news is that the inclusion on the "use" statement seems to have solved the problem previously found by QA a couple of months ago. It seems to be solved both in master of ezpublish 5.4 as in master of ezplatform.

**Comment by gggeek** [comment]
Thx @pcardiga for the confirmation. Closing in favor of https://github.com/ezsystems/ezpublish-kernel/pull/1903

**Pull request closed without merging**
