### PR TITLE
Fix EZP-23974: Move Elasticsearch Search Engine implementation to new namespace

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-23974, a sub-task for https://jira.ez.no/browse/EZP-23940

The PR is based on #1161 and will be reopened against master when #1161 is merged.

Followup: https://jira.ez.no/browse/EZP-23970

Note: dynamic storage engine dependencies will be implemented in a sub-task when all search engines are moved.

### CODE REVIEW

**Comment by pspanja** [comment]
This misses update for the ElasticsearchBundle extension, will be added when reopened against master.

**Comment by bdunogier** [comment]
I'd have appreciated a more thorough description, either here on in the issue (I did check) ;-)

Let's see.

**Comment by lolautruche** [comment]
+1

**Comment by pspanja** [comment]
Closing in favour of https://github.com/ezsystems/ezpublish-kernel/pull/1179.

**Pull request closed without merging**
