### PR TITLE
[Travis] Remove composer.lock

### PR DESCRIPTION
**Pull request by andrerom**
Testing

### CODE REVIEW

**Comment by andrerom** [comment]
What's your POV @bdunogier? Are we better of with composer.lock for faster checkouts, or is the merge conflicts not worth it, and so on?

**Comment by bdunogier** [comment]
So far, `composer.lock` has seldom been an issue.
But if Travis passes without taking too much time, we can safely remove it.

**Comment by andrerom** [comment]
> But if Travis passes without taking too much time, we can safely remove it.

I'll try to see how much time it takes, from composer side they clearly recommend using lock, but I suspect it might have often ignored ours as checksum for composer.json has been wrong often _(missing update of lock on json changes)_.

**Comment by andrerom** [comment]
Seems to have a noticeable impact still, resolve time is some 20-40 seconds depending on PHP version if there is no lock. Ok if we keep it @emodric ?

**Comment by emodric** [comment]
@andrerom Sure, it was just weird to see it, nothing else :)

**Pull request closed without merging**
