### PR TITLE
Fix EZP-24315: Add support for sorting in REST Views

### PR DESCRIPTION
**Pull request by glye**
> Implements https://jira.ez.no/browse/EZP-24315
> Status: Work in progress

Continues on the work from @Nattfarinn in https://github.com/ezsystems/ezpublish-kernel/pull/1651 - Thank you!

- [x] Renamed `GenericDataKey` class to `DataKeyValueObjectClass`
- [x] Added missing docblock param types
- [x] Fixed exception message parameter
- [x] Check if the data key exists before using it, throw if it doesn't
- [ ] Docblock description for `$dataKey` and `$valueObjectClass`
- [x] Unit test for the DataKey parser
- [ ] Update REST spec

### CODE REVIEW

**Comment by glye** [comment]
Update: Adds a unit test for the parser, throws an exception if the value object class doesn't exist.

**Comment by glye** [comment]
@bdunogier @andrerom I hope this is headed in the right direction.

**Comment by bdunogier** [comment]
You could have reused @Nattfarinn's commit :-)

**Comment by andrerom** [comment]
> You could have reused @Nattfarinn's commit :-)

same, please rebase on top of that to include it.

**Comment by bdunogier** [comment]
Actually, the first commit is the same than @Nattfarinn's if I am not mistaken (same code at least).

The easiest would be to rebase & run `commit --author` on the commit.

**Comment by glye** [comment]
@andrerom @bdunogier Yes, the first commit is the same code. Will do as you suggest when I figure out how :/

**Comment by bdunogier** [comment]
@glye:

```
git rebase -i master
# change the commit discussed above to "edit"
# when editing this commit:
run git commit --amend --author <new_author_email>
git rebase --continue
````

**Comment by glye** [comment]
Couldn't get it to work, closing in favour of https://github.com/ezsystems/ezpublish-kernel/pull/1677

**Pull request closed without merging**
