### PR TITLE
Implement EZP-23993: Clarify and document how security issues should be reported

### PR DESCRIPTION
**Pull request by glye**
https://jira.ez.no/browse/EZP-23993

If approved, this should be added to other repos too: ezpublish-legacy at the very least, but possibly all of them?

### CODE REVIEW

**Comment by crevillo** [comment]
+1. and +1 for the other repos, i would include extension repos too...

**Comment by yannickroger** [comment]
+1

**Comment by andrerom** [comment]
+1

**Comment by glye** [comment]
Appended dots as suggested in other PR.

**Pull request merged**
