### PR TITLE
Fix EZP-25452: UTF-8 issue in ContentObject name generation

### PR DESCRIPTION
**Pull request by gabriperego**
Link: https://jira.ez.no/browse/EZP-25452

## Description
Name string with trailing UTF-8 characters are now properly handled with `mb_substr` and explicit `UTF-8` encoding

### CODE REVIEW

**Comment by andrerom** [comment]
+1

*But Integration test would be good of course*

**Comment by yannickroger** [comment]
+1
@gabriperego up to write an integration test ? :smile:

**Comment by yannickroger** [comment]
Also your patch will have to be in a single commit with the issue number in the commit message: `Fix EZP-25452: UTF-8 issue in ContentObject name generation`

**Comment by andrerom** [comment]
@gabriperego no time? or opening new PR?

**Comment by gabriperego** [comment]
Opening new PR this weekend with the test!

**Comment by andrerom** [comment]
Ok, cool :)

**Pull request closed without merging**
