### PR TITLE
EZP-29373: [CS] Switched codebase to use short array syntax

### PR DESCRIPTION
**Pull request by alongosz**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-29373](https://jira.ez.no/browse/EZP-29373)
| **Improvement**| yes
| **New feature**    | no
| **Target version** | `6.7`, `6.13`, `7.4`, `7.5`, `master`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

This PR switches long array syntax to the short one.
Due to maintenance issues we need to do it on all supported branches.

**TODO**:
- [x] Switch codebase to short array syntax.
- [x] Configure php-cs-fixer to enforce short array syntax.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Confirm Travis agrees.
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by andrerom** [comment]
LIKE! But I then assume we aim to do this as on PR, and then a follower to upgrade CS fixer so we can fully support PHP 7.3 and up?

If so, these smaller adjustment to CS works pretty well:
https://github.com/ezsystems/LegacyBridge/commit/13c75de00fda1e5dcfe032182ce9d69b7b56d5f9

**Comment by alongosz** [comment]
> LIKE! But I then assume we aim to do this as on PR, and then a follower to upgrade CS fixer so we can fully support PHP 7.3 and up?
> If so, these smaller adjustment to CS works pretty well:
ezsystems/LegacyBridge@13c75de

I tried to do everything at once, though by different rule-set (I can try the one from LegacyBridge), but after looking at the diff, it seemed too much. I plan to move to fixer v2.14 as a follow-up.

> Side: I have hidden the comment by ezrobot as we have as beginning last week disabled CS check jobs on ci.ez.no (or at least should have done)
> This means we should probably add a job here to check CS + composer validate while at it.

Good point :)

**Comment by gggeek** [comment]
Not really convinced that this is a net benefit to end users :-( Rationale explained in the Jira ticket.

**Comment by alongosz** [comment]
@gggeek foremost this is to benefit eZ Engineering and Support Teams as an internal change. We're the ones maintaining it and working the most on the codebase. We've been postponing this for over 2 years and now it's time to do it. Symfony recently did the same thing and it was also done for 3.x and 4.x, which clearly shows that they see maintenance issues here as well.

Maintenance outweighs necessity to go through one more commit when checking diff.
Answered also in JIRA ticket.

**Pull request merged**
