### PR TITLE
Implement EZP-24732: RichText field does not accept xhtml5edit input with HTML entities

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-24732

RichText was initially intentionally implemented without support for custom named XML entities. CKEditor supports outputting proper XML and converting named HTML entities into numeric entities, so the idea was to handle that on the client side. Unfortunately this does not work with Alloy Editor.

This adds `LIBXML_NOENT` parameter when creating `DOMDocument` from `xhtml5edit` input.
That enables defining entities in DTD of `xhtml5edit` input and keeping them in converted internal format.

Note that named entities will be converted and not kept in the internal format. This only enables named entities from `xhtml5edit` input. Supporting named entities in RelaxNG schema which we use (and which is normative) is not possible. Therefore supporting entities in RichText's internal format would require we store DTD containing entities with each document. I did not go for that here as it is not particularly practical and we never explicitly said we what to have that behavior, but it does remain an option.

So this approach obviously requires that definition of entities is passed from the client side.
It would be possible to implement *sniffing* of input string and injecting definition of entities (or converting them by replacing strings) before DOMDocument is created, which would shift this responsibility from client to server side. That would of course mean that we would accept input string which is not valid XML, but that's an option as well.

### CODE REVIEW

**Comment by pspanja** [comment]
Ping @andrerom @bdunogier @dpobel @lolautruche.
I would like your POV on what to do regarding supporting named entities in the internal format and how to handle DTD in input (see description).

**Comment by andrerom** [comment]
> RichText was initially intentionally implemented without support for custom named XML entities. CKEditor supports outputting proper XML and converting named HTML entities into numeric entities, so the idea was to handle that on the client side. Unfortunately this does not work with Alloy Editor.

Actually this was to optimistic. Please from now on rather look at it like this: *xhtml5edit should actually be changed to be a "html5<something>" format that we support transforming to/from, so not necessarily xml dialect. Why?: In the past we adjusted the editor a lot to try to make it behave closer to our internal format, however this causes lots of issues, and makes it hard to jump from one editor to another or across version jumps. So it is better that the input/output handler here is html5 centric, implied: making it less strict, and allowing it to work more reliable against the editor, and also as bonus makes it suitable for import use cases in the future. And yes this implies we should start to look to use something else then DOM for the initial parsing of input.*

So looks ok for now, we don't want to adjust internal format for this. Internal is internal, should nto complicate it because of external needs, this html5 parser however should support stuff like this.

BTW we should maybe consider adding the following flags also:
- LIBXML_PARSEHUGE *(would imply we should do that other places also over time, so might not make sense here at all yet)*
- LIBXML_NONET *(I assume we don't need net here, so added security on xml provided by user)*

However what I said above also implies we should start to think about moving to use some other initial parser for this format other then DOMDocument in the near future.

**Comment by pspanja** [comment]
> However what I said above also implies we should start to think about moving to use some other initial parser for this format other then DOMDocument in the near future.

OK, though it seems to me that for what we need, with few of these issues I do know about solved, we should be able to have editing format that is both XML and is fine with browser (is actually proper HTML as well), as editors are able to **ouput** proper XML now.
But maybe I don't see all possible problems there.

**Comment by dpobel** [comment]
Not sure to understand the last paragraph of the description nor the patch? With it, am I suppose to send the entities definitions integrated in the HTML5 code ?!? if so that completely breaks the purpose of the issue...

Also I agree with @andrerom, the internal format does not need to be changed to support named entities. (Reminder: the issue is just about being able to set a RichText field with a piece of xhtml5 containing named entities)

**Comment by pspanja** [comment]
> Not sure to understand the last paragraph of the description nor the patch? With it, am I suppose to send the entities definitions integrated in the HTML5 code ?!? if so that completely breaks the purpose of the issue...

XML is not well formed if named entities are referenced but not declared. So this is about the option I mentioned in the description and the question I asked.

> Reminder: the issue is just about being able to set a RichText field with a piece of xhtml5 containing named entities

Then this solves the issue or? :)

**Comment by dpobel** [comment]
so each time I want to save the content of a RichText field, I have to add the definition of the 253 HTML entities with it (the ones actually used) ? I'm sorry but no, that's not a solution the issue. Why can't this be defined once and for all in the xhtml5edit parser ?

**Comment by pspanja** [comment]
No reason, I have mentioned that as an option and asked to comment on it, so thanks I guess :)

**Comment by pspanja** [comment]
I discussed this a bit with @andrerom, we will need to properly implement parsing of HTML/XML-like input in a follow-up, at this point that is not just a fix but rather a change of approach.
So this fix is OK for the time being, as it simply enables named entities with XML input.

**Comment by andrerom** [comment]
+1

**Pull request merged**
