### PR TITLE
EZP-26511: Unable to publish content contains Umlaut-A as title

### PR DESCRIPTION
**Pull request by alongosz**
> Fixes [EZP-26511](https://jira.ez.no/browse/EZP-26511)

This PR fixes incorrect order of `TransformationProcessor` commands (rules) for Legacy/SQL `WordIndexer`.

`WordIndexer` indexes all words as lowercase. The `latin1_diacritical` rule transformed `Ä` to `A`, however `ascii_lowercase` which is needed to transform `A` to `a` was already performed.
For consistency's sake, I moved all the `*_lowercase` rules to the top.

**TODO**:
- [x] Move `TransformationProcessor` `*_lowercase` commands (rules) to the top (7c714de).
- [x] Add unit test testing if content with diacritics can be found (7c714de).

_Note: This will cause conflict with #1814, so I'll need to rebase this PR or the other one depending on which one is merged first_

### CODE REVIEW

**Comment by alongosz** [comment]
Review ping @andrerom @damianz5

@damianz5: does this fix the problem you've reported?

**Comment by alongosz** [comment]
// Backported to `6.5`

**Comment by damianz5** [comment]
@alongosz yes, I've applied this patch on kernel and it works both for publishing the content and search indexer

**Comment by andrerom** [comment]
@pspanja any objections?

**Comment by pspanja** [comment]
No objections, +1.

**Pull request merged**
