### PR TITLE
Fix EZP-24882: always available flag stored to all fields

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-24882

This fixes an old bug where always available flag was set on all fields, instead of only on fields in the main language. The problem occurs when using new stack for creating Content that is both always available and has multiple translations. Previously, this problem was not manifested in the new kernel, however it prevents implementation of Legacy Search Engine working with prioritized languages (this is a WIP).

Cleanup command is implemented. In the cleanup command only affected fields will be processed.

### CODE REVIEW

**Comment by pspanja** [comment]
Review ping @andrerom @bdunogier @glye @lolautruche @yannickroger

**Comment by andrerom** [comment]
+1, but would it be possible to add integration test?

**Comment by pspanja** [comment]
Not at the moment, this is not manifested in the new kernel.
With Legacy Search Engine working with prioritized languages this would manifest in multiple rows being joined when using sort, because of the always available being set on all languages.

**Comment by andrerom** [comment]
Ok

**Comment by lolautruche** [comment]
+1

**Pull request merged**
