### PR TITLE
EZP-29290: Author Field Type prefilled with empty value by default

### PR DESCRIPTION
**Pull request by konradoboza**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-29290](https://jira.ez.no/browse/EZP-29290)
| **Bug/Improvement**| no
| **New feature**    | yes
| **Target version** | `master`
| **BC breaks**      | yes
| **Tests pass**     | yes
| **Doc needed**     | yes

This is a change for https://github.com/ezsystems/ezpublish-kernel/pull/2392 - to avoid BC break Author Field Type won't be prefilled with the current user by default. The user can change it in Content Type edit view. Since version 2.3 this field will be prefilled with current user.

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by andrerom** [comment]
But there where talks of providing some SQL right for those that want to default with current author? But I guess that will be optional so better tackle that in Doc right?

**Comment by konradoboza** [comment]
@andrerom from v2.3 current author will be set by default. Until then we have it also prefilled but without any option to configure it, ref: https://github.com/ezsystems/repository-forms/pull/249. Do we also need a SQL script? ping @lserwatka

**Comment by lserwatka** [comment]
You have to update clean SQL for 2.3. So article type can set it properly

**Comment by konradoboza** [comment]
The clean SQL was already updated within the scope of this PR: https://github.com/ezsystems/ezpublish-kernel/pull/2417/commits/e18e874d14f373aa6aa751251efc3bc7d94c8583#diff-85e0cc75a36405e12f932569256d4daaR52 - Author FieldType is set to be prefilled by default, so article will use it properly. I think we are fine with those changes, or am I still missing something?

**Comment by lserwatka** [comment]
No, we are good. Well done! Thank you for working on this :)

**Pull request merged**
