### PR TITLE
EZP-26146 Location swap inconsistency

### PR DESCRIPTION
**Pull request by glye**
> Fixes https://jira.ez.no/browse/EZP-26146
> Status: Work in progress

Ensure that both `ezcontentobject_tree` and `ezurlalias_ml` are fully updated when swapping locations (technically, it's the content that is swapped).

- [x] Update `ezcontentobject_tree`: `contentobject_id`, `contentobject_version`, `contentobject_is_published`, `path_identification_string`
- [x] Update `ezurlalias_ml`: `text`, `text_md5`, `lang_mask`
- [x] Update tests
- [x] Fix: Studio returns 404 when editing.
- [x] ~~Should we swap `ezcontentobject_tree`: `remote_id`?~~ - No.
- [x] ~~Should we swap `ezurlalias_ml`: `alias_redirects`, `is_alias `, `is_original`?~~ - The current solution uses `UrlAlias/Handler::publishUrlAliasForLocation()`, which makes the choices for us. This does not let the editor decide, as @andrerom suggested.
- [x] ~~Update script~~ - Big job, separate issue I think. See https://jira.ez.no/browse/EZP-26187

### CODE REVIEW

**Comment by andrerom** [comment]
> Should we swap ezcontentobject_tree: remote_id?

I would say no, we swap the content, not the location, templates targeting the remote id should be treated just like templates targeted node id.

> Should we swap ezurlalias_ml: alias_redirects, is_alias, is_original?

now we are talking grey area, given it is connected to location it should not, but from a user perspective some of these should for sure be updated for the new location.

Sounds like we need some specification on this actually, from top of my head:
- system generated aliases should point to the new location
- user generated aliases should continue point to the old one, but we should aim to allow api calls to control this so we at some point can allow editor to be aware and decide himself.

**Comment by glye** [comment]
Fixed the remaining 404, by clearing content cache (for the 2 affected contents only). Works now, apart from todo tasks. Early review ping @yannickroger

**Comment by glye** [comment]
@andrerom This is where it gets complicated. Currently I don't even know if it works with multiple locations, or user generated aliases. Lots of things to test here, as well as spec.

**Comment by glye** [comment]
Fixed a bug when swapped locations are at different tree depths, and a namespace error.

Multiple locations seem to be unaffected by swapping - we are selecting by location ID, so any extra locations get ignored, as they should be.

**Comment by glye** [comment]
Maybe we should rewrite this logic (existing and PR) so that we use `UrlAlias/Handler::publishUrlAliasForLocation()` instead of all the manual doctrine code. There are too many edge cases and to much wheel reinvention going on now.

**Comment by glye** [comment]
Update: Squashed existing commits, added fixup which reverts all the urlalias code, replacing it with simple calls to `UrlAlias/Handler::publishUrlAliasForLocation()`. Looks good so far.

**Comment by glye** [comment]
Ping @andrerom @yannickroger - all green, and a much simpler approach now. Not too simple, I hope. Note: This does not let the editor decide as AR suggested; custom aliases are left untouched.

**Comment by glye** [comment]
Ping @bdunogier too. FYI, not a customer issue, but needed by Dominika, and involves data corruption.

**Comment by andrerom** [comment]
+1, looks better now

**Comment by bdunogier2** [comment]
Looks okay to me.

Could somebody from the repository team review this as well ?

**Comment by glye** [comment]
Ping @alongosz - see complete diff, I'll squash all before merging this / before QA, whichever comes first.

@bdunogier Yes, it should probably go into 6.3. Good we don't need to make a new PR for this now.

**Comment by bdunogier2** [comment]
@glye can you change the branch & rebase the pull-request ? You have the +1, we can bring QA in (it should be in 1.5 beta).

**Comment by andrerom** [comment]
> @glye can you change the branch & rebase the pull-request ? You have the +1, we can bring QA in (it should be in 1.5 beta).

If you want QA to test before merge, as part of 1.5 certification, then Pr should continue to point towards master for the time being. /cc @glye

**Comment by alongosz** [comment]
+1, looks good to me

**Comment by glye** [comment]
Thanks all, I have squashed and will send this to QA now, then.

**Comment by glye** [comment]
Trying out a new urlalias swap-method again. (Having some trouble with local testing.)

**Comment by glye** [comment]
Trying out a new urlalias swap-method again. The test failure is relevant and reproducible locally, but makes no sense to me - there's a UNIQUE constraint failure, but no existing entry with that key.

**Comment by glye** [comment]
@alongosz / repo team, are you able to help with this?

**Comment by alongosz** [comment]
I'll take a look :)

**Comment by pspanja** [comment]
@glye Primary key is composite of `parent` and `text_md5`, and Locations you are swapping are on the same level (top), hence the conflict.

**Comment by glye** [comment]
@pspanja I am doing the swap in 3 steps, one with temporary values, to avoid this collision. See https://github.com/ezsystems/ezpublish-kernel/pull/1752/files#diff-2cd10f853a8db9601020e6294b75fc07R358

**Comment by pspanja** [comment]
@glye Demo design Location (2nd, ID:56) has additional history alias, that's why it still conflicts.

**Comment by pspanja** [comment]
> The current solution uses UrlAlias/Handler::publishUrlAliasForLocation(), which makes the choices for us. This does not let the editor decide, as @andrerom suggested.

From the description, was that changed?
I think it would be a better approach, as this does not resolve the conflict with existing aliases on the same level.

**Comment by pspanja** [comment]
How should history aliases to be handled when swapping?

**Comment by glye** [comment]
> Demo design Location (2nd, ID:56) has additional history alias, that's why it still conflicts.

I guess you're right, though in my local tests I have been checking the DB for other instances of the same md5 and/or parent without seeing any conflicts.

The current commits 2 & 3 reverse the `publishUrlAliasForLocation()` approach, as that doesn't work either (QA found a failure case). It results in weird inconsistent behaviour, sometimes infinite redirect loops, it seems.

Hence, it would be great if the repo team gave it a try.

**Comment by pspanja** [comment]
I have another issue ATM with more priority, but will start on this when possible.

**Comment by pspanja** [comment]
Closing in favor of https://github.com/ezsystems/ezpublish-kernel/pull/1781.

**Pull request closed without merging**
