### PR TITLE
Add "viewParameters" handler for URL alias generator.

### PR DESCRIPTION
**Pull request by TOTOleHero**
exemple Usage : {{ pagerfanta( pagerNews, 'twitter_bootstrap_translated', {'routeName': location,'routeParams': {'viewParameters':{'maxPerPage':2 }}} ) }}
this exemple add (maxPerPage) view parameter in rendered url

### CODE REVIEW

**Comment by bdunogier** [comment]
Hi, and thank you for your contribution.

What would you say is the benefit of view parameters over query ones here ?

**Comment by TOTOleHero** [comment]
Just use beautiful URL with ezpublish philosophy and it's the twin of the listener SiteAccessListener which convert the viewParameters to expose data throw the Request.

from eZ\Bundle\EzPublishCoreBundle\Controller  in action function : 

        $request = $this->get('request');
        $viewParameters = $request->attributes->get('viewParameters');

**Comment by bdunogier** [comment]
I'm not sure I want to integrate viewParameters that way. They were very important in eZ Publish because of ViewCache. We've kept them in the 5.x generation because of BC with existing projects.

But since ViewCache is replaced with HTTP cache, and HTTP cache works with query parameters, I'm not sure it's that important now.

**Comment by alongosz** [comment]
Closing as obsolete.

**Pull request closed without merging**
