### PR TITLE
Fix EZP-25335: Use ContainerAwareTrait instead for sf 2.8+ support

### PR DESCRIPTION
**Pull request by wizhippo**
> Implements https://jira.ez.no/browse/EZP-25335

Replaces usage of abstract `ContainerAware` with the `ContainerAwareTrait`.

### CODE REVIEW

**Comment by emodric** [comment]
Is it required to implement `ContainerAwareInterface`?

**Comment by wizhippo** [comment]
@emodric I know the ioconfigurationpass uses the interface to check if it should inject the container.  Perhaps I can remove it on all classes except those in the EzPublishIOBundle. Any thoughts?

**Comment by wizhippo** [comment]
Looking closer it was the controller that would automatically get the container if it extended the interface.    Looks like for the container it has to be explicitly set.  So I'll remove it from all but the io bundle and see if the tests pass.

**Comment by andrerom** [comment]
+1

*so no use of ContainerAware class left?*

**Comment by wizhippo** [comment]
@andrerom Correct.  There is ContentAwareCommand and ContainerAwareEventDispatcher but I do not believe that they will be replaced by a traits yet.

**Comment by bdunogier** [comment]
Looks good to me !

+1

**Comment by bdunogier** [comment]
After thinking about it for a while, I would add `ContainerAwareInterface`. Removing it is a BC break, since `ContainerAware` _did_ implement `ContainerAwareInterface`. We end up with a bunch of classes that did implement an interface, and don't implement it anymore.

**Comment by wizhippo** [comment]
Master it fine.  It really doesn't need to be merged until sf2.8+ is supported.

**Comment by bdunogier** [comment]
Good. So what about the BC break on the interface ?

**Comment by wizhippo** [comment]
Maybe I misunderstood, I have reverted the removal of `implement the ContainerAwareInterface`.  Does that not put us back to as we were before in regards to BC?   Is there something else you were thinking?

**Comment by andrerom** [comment]
With the revert, it seems to be fine from my pov, wdt @bdunogier ?

**Comment by bdunogier** [comment]
Hmmm, I did miss that last change for some reason. Sorry about that.

+1, and thanks a lot !

**Comment by andrerom** [comment]
Thanks all, seems to be ready for merge :)

**Pull request merged**
