### PR TITLE
Fix EZP-24025: Make sure to clear cache on install

### PR DESCRIPTION
**Pull request by andrerom**
Issue: https://jira.ez.no/browse/EZP-24025

Is being tested here : https://github.com/ezsystems/ezpublish-community/pull/230

### CODE REVIEW

**Comment by andrerom** [comment]
Review ping @lolautruche @yannickroger @bdunogier

**Comment by crevillo** [comment]
I Have a question: realCacheDir here will the entire ezpublish/cache directory? Or it will be ezpublish/cache/prod?

**Comment by andrerom** [comment]
Search and you should see :)
<sub>_(it wil lbe the one with env in it)_ ;)</sub>

**Comment by crevillo** [comment]
Ok. Asked because i was Wondering if a composer update should trigger a cache clear of all your defined enviroments.

**Comment by andrerom** [comment]
I'm not sure to be honest, some expect to be able to do composer update on prod server directly so depends on you're use of composer I guess.

**Comment by lolautruche** [comment]
This command is actually a service. Please update the service definition/constructor instead of calling the container :wink:

**Comment by lolautruche** [comment]
Otherwise, +1 on the approach

**Comment by andrerom** [comment]
Good point!

@lolautruche btw took this from here, but skipped cache folder renaming as it looked a bit strange to do that _and_ folder clearing, but maybe I overlook something:
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php#L51

**Comment by bdunogier** [comment]
+1 if it works

**Comment by andrerom** [comment]
@lolautruche / @bdunogier updated now to inject services param instead.

**Comment by lolautruche** [comment]
+1

**Pull request merged**
