### PR TITLE
Fix some Insight issues

### PR DESCRIPTION
**Pull request by andrerom**
This just fixes some issues, there are still tons of issues by all of us*

\* myself, @pspanja, @yannickroger, @lolautruche, @bdunogier, @dpobel, @StephaneDiot, @glye: Please have a look [here](https://insight.sensiolabs.com/projects/0885c0ce-4b9f-4b89-aa9c-e8f9f7a315e0/analyses/122) to know what to avoid, so we don't keep on creating more of these issues.

(waiting for travis)

### CODE REVIEW

**Comment by bdunogier** [comment]
> Interfaces names should end with "Interface"

Do we really follow this one ?

**Comment by bdunogier** [comment]
And +1.

Still no possibility to get insight to comment on our pull requests ? It would really be more convenient. Of course, we should still follow the guidelines to begin with.

**Comment by andrerom** [comment]
>> Interfaces names should end with "Interface"
> Do we really follow this one ?

**Comment by bdunogier** [comment]
> and the rule is kind of stupid

+1 :-)

**Pull request merged**
