### PR TITLE
Fix EZP-23975: Move Solr Search Engine implementation to new namespace

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-23975, a sub-task for https://jira.ez.no/browse/EZP-23940

Followup: https://jira.ez.no/browse/EZP-23974

This moves Solr Search Engine implementation to eZ\Publish\Core\Search and updates container configuration.

MVC integration tested manually.

### CODE REVIEW

**Comment by pspanja** [comment]
This is https://github.com/ezsystems/ezpublish-kernel/pull/1161 reopened against `master`.

Ping @andrerom, @bdunogier, @glye, @lolautruche, @yannickroger.

**Comment by andrerom** [comment]
+1, but make sure you test that web application works ;)

**Comment by pspanja** [comment]
> MVC integration tested manually.

I did, it works :)

**Comment by yannickroger** [comment]
+1

**Comment by pspanja** [comment]
Travis config needed an update, now it passes. Thanks for the review!

**Pull request merged**
