### PR TITLE
[EZP-30590] Fix noLayout default value

### PR DESCRIPTION
**Pull request by lolautruche**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-30590](https://jira.ez.no/browse/EZP-30590)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | 6.7 / 6.13 / 7.5
| **BC breaks**      | no
| **Tests pass**     | 
| **Doc needed**     | 

Prior to v6.0, `ViewController::viewLocation()` and `ViewController::viewContent()` had parameter [`$layout` default value to `false`](https://github.com/ezsystems/ezpublish-kernel/blob/6.7/eZ/Publish/Core/MVC/Symfony/Controller/Content/ViewController.php#L143). The consequence was that [`noLayout` parameter, injected further
down in templates, had `true` as default value](https://github.com/ezsystems/ezpublish-kernel/blob/6.7/eZ/Publish/Core/MVC/Symfony/Controller/Content/ViewController.php#L436) (the exact opposite).

The goal of such parameter was to ensure that templates used in subrequests always had the information not to use the main pagelayout by default, [especially when rendering content from legacy](https://github.com/ezsystems/LegacyBridge/blob/master/mvc/View/TwigContentViewLayoutDecorator.php#L111-L122) (templates not migrated yet to Twig).

We could also do stuff like the following:

```jinja
{% extends noLayout == true ? viewbaseLayout : pagelayout %}
```

Problem with the value injected by `NoLayout` injector is that the default value of `noLayout` parameter changed. It currently checks if `layout` parameter is present (which is not the case by default with the new view system) and if not, defaults to `false`. 
Consequence is that when migrating an instance from eZ Publish 5 to Platform with legacy bridge, main layout is always used. This sounds like an undocumented BC break to me :wink:.

Before opening a Jira issue, I wanted to know is that could be an acceptable fix. I don't see any possible regression here since even using Symfony stack, `noLayout` variable will never have the expected value anyway without this fix.

**TODO**:
- [x] Open Jira issue
- [ ] Tests

### CODE REVIEW

**Comment by lolautruche** [comment]
Ping @bdunogier @andrerom

**Comment by andrerom** [comment]
Did you find git blame for this?

I remember there where a change that was discussed around this with @emodric, but that might have been in legacy bridge.

Anyway, maybe a bit late to change it now for 6.7, 6.13 and 7.5? As in I assume this is bc break for everyone on platform already.

**Comment by lolautruche** [comment]
I did git blame a lot, without finding anything relevant. 
@emodric : if you have more inputs, please shout out 😄 .

> Anyway, maybe a bit late to change it now for 6.7, 6.13 and 7.5? As in I assume this is bc break for everyone on platform already.

AFAICS it won't be a BC break since the default valeur for `layout` parameter (on which depends `noLayout` is always `false` (hence `noLayout` should always be true). 
Anyway, what I could do is to make this default value configurable, with a dynamic setting. 

This is really blocking (even if it doesn't happen so often), so we must be able to solve this IMHO.

**Comment by andrerom** [comment]
> Anyway, what I could do is to make this default value configurable, with a dynamic setting.

ehh, rather not 😅

**Comment by lolautruche** [comment]
> ehh, rather not 😅
Why not?

I'll open the Jira issue for sure. As for tests, I looked for existing tests and there was none, but I can sure create some.

Ping @bdunogier @StephaneDiot @lserwatka

**Comment by adamwojs** [comment]
Closing PR as obsolete. eZ Platform 2.5 has reached EOM, so please reopen PR in ezsystems/ezplatform-kernel (bug fixes) or ibexa/core (features/improvements) if issue is still valid for v3.3 / v4.x and you are willing to work on it.

**Pull request closed without merging**
