### PR TITLE
Fix EZP-25279: DefaultRouter tests incorrectly for ABSOLUTE_URL

### PR DESCRIPTION
**Pull request by wizhippo**
See https://jira.ez.no/browse/EZP-25279

### CODE REVIEW

**Comment by yannickroger** [comment]
There's a typo in your commit message (and title of the PR).
Also could you add steps to reproduce to the JIRA issue. Our QA will need it to validate the fix.

ping @bdunogier @lolautruche

**Comment by andrerom** [comment]
And if possible a unit test that would fail before this fix would be great.

**Comment by wizhippo** [comment]
This can test it.  Having a hard time turning into unit test https://gist.github.com/wizhippo/41a643c6b2002764b0f9

**Comment by wizhippo** [comment]
I cannot reproduce in a unit test using a mock of the DefaultGenerator for some reason. When it evaluates `$referenceType == self::ABSOLUTE_URL` in the debugger the constants values do not match the values from `UrlGeneratorInterface`.  Perhaps phpunit does not handle constants from an interface properly in a mock object properly?

**Comment by wizhippo** [comment]
It actually evaluates self::ABSOLUTE_URL as true in the mocked router which passes other tests when they actually should not.  If you add the constants from UrlGeneratorInterface directly to DefaultRouter and run phpunit for eZ\Bundle\EzPublishCoreBundle\Tests\Routing\DefaultRouterTest you will see there are failed tests now that I believe would have covered the unit test for this case.

**Comment by wizhippo** [comment]
This only happens with Symfony 2.8+ and is a by product of https://github.com/symfony/symfony/commit/912fc4de8fd6de1e5397be4a94d39091423e5188

**Comment by andrerom** [comment]
Ok, what about a test for invalid condition expecting to fail before the fix?
like a providerInvalidGenerateWithSiteAccess with a few entries.

**Comment by wizhippo** [comment]
@andrerom actually the current tests do detect the issue if you use symfony 2.8 instead of 2.7.  So no test is required.

**Comment by bdunogier** [comment]
The Sf 2.8 test matrix item ran by Travis is wrong, it uses 2.7.7: https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/97024054#L332. 

I've sent a PR that so that 2.8 is tested correctly: #1543

**Comment by andrerom** [comment]
Hi,

so what I suggest to fully verify this fix is the following:
1. re build this branch by first committing and _(force)_ pushing this to verify it failing:
```diff
diff --git a/.travis.yml b/.travis.yml
index 958305d..c36ee30 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -24,10 +24,11 @@ matrix:
     - php: 5.5
       env: TEST_CONFIG="phpunit-integration-legacy.xml" DB="mysql" DATABASE="mysql://root@localhost/$DB_NAME"
 # 5.6
+# Uses Symfony 2.7 until we move over completely to 2.8, after that we consider testing 3.0
     - php: 5.6
-      env: TEST_CONFIG="phpunit.xml" SYMFONY_VERSION="~2.8.0@beta as 2.8.0"
+      env: TEST_CONFIG="phpunit.xml" SYMFONY_VERSION="~2.7.0"
     - php: 5.6
-      env: TEST_CONFIG="phpunit-integration-legacy.xml" SYMFONY_VERSION="^2.8"
+      env: TEST_CONFIG="phpunit-integration-legacy.xml" SYMFONY_VERSION="~2.7.0"
     - php: 5.6
       env: BEHAT_OPTS="--profile=core --tags='~@broken'"
 # 7.0
diff --git a/composer.json b/composer.json
index 65fd444..4364ad3 100644
--- a/composer.json
+++ b/composer.json
@@ -17,7 +17,7 @@
         "ext-SPL": "*",
         "ext-xsl": "*",
         "zetacomponents/mail": "~1.8",
-        "symfony/symfony": "~2.7.0",
+        "symfony/symfony": "~2.7",
         "symfony-cmf/routing": "~1.1",
         "qafoo/rmf": "1.0.*",
         "kriswallsmith/buzz": ">=0.9",
```

2. After that, cherry pick your commit (currently 2e4eaad) and push again, this should now pass if you understood you correctly.

**Comment by wizhippo** [comment]
@andrerom As you can see this passes for both sf 2.7.0 and sf 2.8.0.  

My real concern is why does master pass on TEST_CONFIG="phpunit.xml" SYMFONY_VERSION="~2.8.0@beta as 2.8.0" when it does not locally.  Should running in this env not show the same errors in travis as it would locally using "symfony/symfony": "~2.7"

Sorry I'm not trying to make this difficult.  Just trying to understand why to different outcomes.  Maybe I am mistaken that SYMFONY_VERSION="~2.8.0@beta as 2.8.0" runs against sf 2.8
Attach files by dragging & dropping,  Choose Files selecting them, or pasting from the clipboard.

I'll run your code above and see if I get the failure I expect.

**Comment by andrerom** [comment]
> SYMFONY_VERSION="~2.8.0@beta as 2.8.0"

This is as @bdunogier tried to fix actually running on 2.7, because it is by mistake using tilde, while we have to use specific versions when using alias `as`, so it should have been `SYMFONY_VERSION="v2.8.0-beta1 as 2.8.0"`.


That said, are you also saying master *(without your bug fix changes)*, fails locally, but passes on travis with the fixes fixes to get tests to run on 2.8?

**Comment by bdunogier** [comment]
> That said, are you also saying master (without your bug fix changes), fails locally, but passes on travis with the fixes to get tests to run on 2.8?

I think your comments were simultaneous or close. Travis isn't done running the tests on 2.8 yet. I'm still expecting them to fail on 2.8, or else it's gonna get complicated :-)

**Comment by wizhippo** [comment]
@bdunogier I think I found out why the tests are not failing on sf 2.8 like when I run locally.  In `prepare_unittest.sh` the update for the symfony version occurs before `composer install`.  As there is a composer.lock this new required version is not used but the version in the lock the lock file.  In out case sf 2.7.7.  Instead should not the `composer require` happen after after `composer install`?  Also `composer require` needs to be run without `--no-update` as we need the symfony

**Comment by wizhippo** [comment]
@bdunogier I get the expected failure now that I added the fix to travis for requiring the correct symfony version

**Comment by andrerom** [comment]
+1 seems to be passing

*solr bundle needs adoption in composer.json to accept kernel 6.1 which is now master*

**Comment by andrerom** [comment]
Thanks @wizhippo !

**Pull request merged**
