### PR TITLE
EZP-31299: Added semicolon in dbupdate-7.5.6-to-7.5.7.sql

### PR DESCRIPTION
**Pull request by asellmeier**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-31299](https://jira.ez.no/browse/EZP-31299)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `7.5`, `master (8.0@dev)`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

DML statement closing semicolon was missing.

**TODO**:
- [x] Fix a bug.
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by adamwojs** [comment]
Hi @asellmeier! Could you please add a semicolon to `data/update/postgres/dbupdate-7.5.6-to-7.5.7.sql` as well (it also seems to be missing)?

**Comment by michal-myszka** [comment]
@asellmeier could you also add semicolon to `data/update/postgres/dbupdate-7.5.6-to-7.5.7.sql` ?

**Comment by asellmeier** [comment]
Good point, I'll do.

**Comment by adamwojs** [comment]
Pro tip: You don't need to close PR. Simply commit changes and push the branch to remote. Github will update PR ;-)

**Comment by asellmeier** [comment]
I know, but I only used the "GitHub fork - PL" feature and did not create a local hotfix. And couldn't figure out a way on how to edit the patch directly only in GitHub. Maybe there is one ;-)

**Comment by asellmeier** [comment]
Doing it the proper way now, need 2 mins.

**Comment by adamwojs** [comment]
Thank you for contribution @asellmeier!

**Pull request merged**
