### PR TITLE
Fix EZP-23837: Impossible to set the value of a Media field

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-23837 (discovered while implementing the Media field edit view in PlatformUI https://jira.ez.no/browse/EZP-23813)

# Description

It's impossible to update the value of a Media field using the REST API. It seems like it's because unlike for BinaryFile and Image, the Media field type processor does not extend the BinaryInputProcessor (which takes care of creating a file on the disk with the data provided in the REST update struct).

Note: for now, this is a very rough patch just to let me work on EZP-23813 and to see which tests it breaks :)

# Tests

manual for now

### CODE REVIEW

**Comment by bdunogier** [comment]
Looks legit, it probably should have been this way from day 1.

What hostname, André ?

**Comment by bdunogier** [comment]
Let's see if this fixes the failure.

**Comment by andrerom** [comment]
@bdunogier No need to handle any of the params the other binary types does?

**Comment by bdunogier** [comment]
Well, it won't work less than it did. I went quite quickly through this,
but i can test it a deep further.

**Comment by bdunogier** [comment]
> No need to handle any of the params the other binary types does?

Not that I can see, @andrerom. MediaType handles its own parameters via fromHash, and BinaryInputProcessor handles the base64 contents. It is similar to what other types do, unless I am missing something.

I'm +1 with the current code.

**Comment by andrerom** [comment]
+1

**Comment by dpobel** [comment]
+1 of course :)
And big +1 for a smarter temporary file handling (there are currently left in the temporary directory...)

**Comment by andrerom** [comment]
review ping @bdunogier

**Comment by bdunogier** [comment]
I did [+1 it 21 days ago](https://github.com/ezsystems/ezpublish-kernel/pull/1121#issuecomment-69164044).

**Comment by andrerom** [comment]
sorry, overlooked it when @dpobel said he was missing reviews, so @dpobel you are actually good to go here :)

**Comment by andrerom** [comment]
@dpobel / @bdunogier should probably be back ported to 5.4 / 5.3.

**Pull request merged**
