### PR TITLE
EZP-25915: Avoid RunTimeException on composer update/install

### PR DESCRIPTION
**Pull request by andrerom**
https://jira.ez.no/browse/EZP-25915

On bundle changes when switching branches, triggered when loading container when trying to clear cache.

This will need change in ezplatform `composer.json` to take advantage of this.

### CODE REVIEW

**Comment by andrerom** [comment]
review ping @bdunogier @crevillo

**Comment by bdunogier** [comment]
Bit brutal, but sometimes brutality is what you need.

Aaand +1.

**Comment by andrerom** [comment]
> Bit brutal, but sometimes brutality is what you need.

true, could have used filesystem component.

**Comment by bdunogier** [comment]
I guess you could. Not sure there's a real benefit though, given that you only remove files (as opposed to directories). `unlink()` will get the job done.

**Comment by crevillo** [comment]
+1.

**Comment by andrerom** [comment]
> edit. i would probably add some warning saying to not execute composer install or update as root :) as legacy said "with great power..."

that was for deleting folders, so if user fucked up and configured "/" as var folder and then ran some commands as root you would wipe your machine.

So I don't think we have risk for that here, but input on how I can further reduce risk on this command without having to force extra considerations to take into account for user is welcome :)

**Comment by crevillo** [comment]
don't worry. is just we still have some customers with their own hosting services and still we couldn't convince them to not use root for this kind of matters. I'm in panic and looking for help :)

**Comment by andrerom** [comment]
@crevillo hammer solution: place in VM's and make sure to have script to recreate VM's whenever something happens :P

**Comment by andrerom** [comment]
Ok, lets do this for now and open for improvements from whoever wants to do that :)

**Pull request merged**
