### PR TITLE
EZP-25831: Fix php 7 tests.

### PR DESCRIPTION
**Pull request by galileo**
Related to JIRA ticket: 

https://jira.ez.no/browse/EZP-25831

> Status: Ready for review

I think that this PR is some how urgent because wihtout this all of our pull request on travis for php version 7 are failing.

### CODE REVIEW

**Comment by galileo** [comment]
The problem was spotten after update the php version from `7.0.6` to `7.0.7` where there is an fix for 

> Function calls with values to a by-ref parameter don't always throw a notice

and this is crashing our test in those places that you can find in this pull request. 

For more information about this fix see:
 
https://bugs.php.net/bug.php?id=72038

ping @bdunogier @andrerom

**Comment by bdunogier** [comment]
+1

**Comment by bdunogier** [comment]
(waiting to see if tests pass before merging)

**Comment by galileo** [comment]
Sure, you should :+1:

**Comment by galileo** [comment]
Green ;)

**Comment by bdunogier** [comment]
Merged to master as well.

**Comment by galileo** [comment]
Fantastic! Thanks Bertrand.

**Pull request merged**
