### PR TITLE
EZP-25842: Added current version number to REST content info

### PR DESCRIPTION
**Pull request by bdunogier**
> Implements [EZP-25842](https://jira.ez.no/browse/EZP-25842)

Not much to add. Value object visitor unit test and specifications have been updated.

### CODE REVIEW

**Comment by bdunogier** [comment]
Ping @dpobel & @andrerom.

**Comment by dpobel** [comment]
+1

**Comment by andrerom** [comment]
+1

**Comment by andrerom** [comment]
Wait

we need this on ContentInfo like in PHP API.

**Comment by bdunogier** [comment]
> we need & want this on ContentInfo like in PHP API, or?

It is in ContentInfo. Both ContentInfo and Content use the same ValueObjectVisitor (both are more complex than their Public API counterpart, and needed extra data).

**Comment by andrerom** [comment]
Ok, +1

But we should update the XML Schema section in REST spec as well:

**Comment by bdunogier** [comment]
Spec updated.

**Pull request merged**
