### PR TITLE
Fix EZP-26903: ContentType::getDescription incorrect usage of isset() function

### PR DESCRIPTION
**Pull request by blankse**
JIRA: https://jira.ez.no/browse/EZP-26903

### CODE REVIEW

**Comment by andrerom** [comment]
Thanks @blankse, could you create an issue for this?

**Comment by blankse** [comment]
@andrerom I created an issue for this.

**Comment by andrerom** [comment]
Could you rebase it to 6.7 as well?

**Comment by blankse** [comment]
@andrerom I changed the base branch to 6.7

**Pull request merged**
