### PR TITLE
EZP-28470: Allow state limitation on manage_locations

### PR DESCRIPTION
**Pull request by wizhippo**
https://jira.ez.no/browse/EZP-28470

### CODE REVIEW

**Comment by andrerom** [comment]
@wizhippo Issue does not expand on this, does legacy allow this?

**Comment by wizhippo** [comment]
@andrerom I have corrected the jira link.   Yes legacy allows you to set state limitations on remove https://github.com/ezsystems/ezpublish-legacy/blob/f02208e873a9d7d20293a64d1fdaa9ba2c5b79ee/kernel/content/module.php#L680

**Comment by andrerom** [comment]
But this is manage_locations

**Comment by wizhippo** [comment]
Again you are correct. Sorry manage locations is a bit confusing as it also applies to trashing and item. So then no this was not in legacy, but this is needed as described to disallow trashing items based on state.

**Comment by wizhippo** [comment]
To add in my use case I also do not want the user to be able to move the item to another location either.

**Comment by andrerom** [comment]
Ok, then maybe open PR on this for legacy too so we don't end up in any issues for legacy bridge users.

**Comment by andrerom** [comment]
@wizhippo can you change target branch to 6.13?

**Pull request merged**
