### PR TITLE
EZP-25369: Remove configuration from installers

### PR DESCRIPTION
**Pull request by andrerom**
https://jira.ez.no/browse/EZP-25369

Depends on var_dir setting in base: https://github.com/ezsystems/ezplatform/pull/80

### CODE REVIEW

**Comment by bdunogier** [comment]
Note that this a BC break. What about deprecating it ?

**Comment by andrerom** [comment]
It's a soft one if we only consider installer as the place this interface is called, installers might still have the method, only difference is that it is not called anymore.

**Comment by andrerom** [comment]
But that said I can just deprecate if that is prefered, but then I won't be able to remove it from installer.

**Comment by andrerom** [comment]
Changed to deprecate instead, and added some doc while at it.

@bdunogier as far as I can see the remaining failures are bugs in the tests, see: 3de4339ddc5ab870a66ca306541d2c79e303a535

**Comment by bdunogier** [comment]
Better with BC kept, thank you :-)

About the errors, it seems that they're just because of an expected `var/` as the default vardir.
I'm wondering if this could be a BC issue... what if somebody has a setup that does NOT override the value of vardir, and relies on it ? It can easily be fixed with docs, but...

**Comment by andrerom** [comment]
> About the errors, it seems that they're just because of an expected var/ as the default vardir.
I'm wondering if this could be a BC issue... what if somebody has a setup that does NOT override the value of vardir, and relies on it ? It can easily be fixed with docs, but...

true, move it back to meta? If safer I think I prefer that *(and then I don't need to dig into why the tests fails here :sweat_smile: unless you or @lolautruche has any input on that)*

**Comment by bdunogier** [comment]
> I don't need to dig into why the tests fails here

If it is the main blocker, I can have a look, it shouldn't be complicated :-)

**Comment by andrerom** [comment]
yes it is, besides the bc topic you brought up witch I guess mainly affects upgrades.

**Comment by andrerom** [comment]
Updated, and fixed up https://github.com/ezsystems/ezplatform/pull/80 as well.

**Comment by bdunogier** [comment]
+1

**Pull request merged**
