### PR TITLE
EZP-23242: UserService uses Content search instead of Location search

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-23242

Blocks https://jira.ez.no/browse/EZP-24718

This replaces Content search with Location search in UserService.
Existing tests apply.

Additionally Travis parameters for Solr integration tests are updated.

### CODE REVIEW

**Comment by pspanja** [comment]
Ready for review, ping @andrerom @glye

**Comment by andrerom** [comment]
+1, but loading within loop is not really optimal.

**Comment by glye** [comment]
+1 AFAICT

**Comment by pspanja** [comment]
Thank you!

**Pull request merged**
