### PR TITLE
Fix EZP-26397: Force isSearchable::false on FieldDefinitions of a type that isn't searchable

### PR DESCRIPTION
**Pull request by bdunogier**
> Fixes https://jira.ez.no/browse/EZP-26397

If a field definition is marked as searchable in the database, it will be marked as such in ContentType drafts. This will make the ContentType impossible to edit unless you force that value off.

This adds a check during mapping that forces the value to `false` if the FieldType isn't searchable, thus preventing any error. In addition, it will transparently fix any wrong value upon save.

Fixing this in repository-forms instead would be much more complicated. 

### TODO
- [x] Make the mapper force `isSearchable` to `false` when the FieldType isn't searchabe
- [x] Mark {{user.user_account}} as not searchable in `cleandata.sql`
- [ ] Add dbupdate script (do we have dbupdates for minor versions ?)

### CODE REVIEW

**Comment by andrerom** [comment]
> Add dbupdate script (do we have dbupdates for minor versions ?)

we can, but then we would need to have both for 6.5.2 and 6.6.0, and ideally make sure the instructions can be executed safely several times.

**Comment by dpobel** [comment]
+1 (I guess the same SQL fix has to be made in ezplatform-demo and ezstudio-demo ?)

**Comment by andrerom** [comment]
> +1 (I guess the same SQL fix has to be made in ezplatform-demo and ezstudio-demo ?)

maybe, they tend to append to clean

**Comment by andrerom** [comment]
@clash82 Do you know if this needs further changes in demo / studio data?

**Comment by andrerom** [comment]
Merging for the beta

**Comment by clash82** [comment]
> Do you know if this needs further changes in demo / studio data?

@andrerom yes, we have to change it in demos:

ezplatform-demo: https://github.com/ezsystems/ezplatform-demo/blob/master/src/AppBundle/Resources/installer/sql/app_data.sql#L320

ezstudio-demo: https://github.com/ezsystems/ezstudio-demo-bundle/blob/master/Resources/installer/sql/demo_data.sql#L70

**Pull request merged**
