### PR TITLE
PHPUnit forward compatibility layer

### PR DESCRIPTION
**Pull request by MarioBlazek**

### CODE REVIEW

**Comment by andrerom** [comment]
Hi, it would be better if we split this problem up I think.

Cause we need to maintain 6.7 as well for a while, so would rather aim to just solve the failures for updating to PHPUnit 5.x in 6.7 and merge that up. Then as second step deal with the warnings, they can be dealt with in 6.7 and up on demand. As for PHPUnit 6 update we can keep that for 2.0 branch, as it does not support PHP 5.6.

this way we won't have to introduce any compatibility layer.
But there might of course be some benefits to that I might miss, even if it means yet another thing to deal with and refactor the whole code base for.

**Comment by emodric** [comment]
:+1: for rebase on `6.7`

@andrerom And yes, `composer.json` should be updated to allow `^5.4`, since now it's at `^4.7.0`

**Comment by MarioBlazek** [comment]
OK, I will rebase on 6.7 and update phpunit constraint to ^5.4. Should I deal with phpunit warnings on this PR ?

**Comment by andrerom** [comment]
> OK, I will rebase on 6.7 and update phpunit constraint to ^5.4. Should I deal with phpunit warnings on this PR ?

for our sanity lets not, but you / we will have to deal with errors to be able to merge it

**Comment by emodric** [comment]
@MarioBlazek Don't forget to switch the base branch in the PR :)

**Comment by MarioBlazek** [comment]
Base branch switched to 6.7

**Comment by MarioBlazek** [comment]
Just suggestion, what about creating a single `BaseTestCase` class that would extend from PHPunit's `TestCase` and then all other eZ test classes should extend this base class. Then in future we would have one class to change, rather than 400. WDYT @andrerom @emodric

**Comment by emodric** [comment]
What is there to change in the future? :)

**Comment by MarioBlazek** [comment]
There is nothing to change :)

**Comment by emodric** [comment]
Then what's the point of using an intermediate base class? Only complicates things.

**Comment by andrerom** [comment]
If PHPunit did not provide the name spaced forward compatible layer, that would be something to consider. but now only reason to do that would be to provide getMock when on 6.x if we want to support 5.x and 6.x in parallel

**Comment by emodric** [comment]
@andrerom `getMock` was deprecated in favor of `createMock` and `getMockBuilder` in 5.4.

Since `composer.json` now requires `^5.4`, there's no sense in providing a compatibility layer, when you can switch to using non deprecated methods, which will work both in 5.x and 6.x.

**Comment by emodric** [comment]
@MarioBlazek BTW, it would probably be a good idea to set `phpunit/phpunit` constraint to at least `^5.4.3`, since in versions `5.4.0` to `5.4.2`, namespaced variant of the `TestCase` class was lowercased (`phpunit\framework\TestCase`)

**Comment by MarioBlazek** [comment]
I think we should stay with `^4.7.0` phpunit constraint on this PR, and then do another one with updated constraint and tests to work with v5.

**Comment by emodric** [comment]
How can we stay on `^4.7.0` when 4.x does not provide namespaced `TestCase` ?

**Comment by MarioBlazek** [comment]
Ah, you are right. I will update broken tests with v5.

**Comment by MarioBlazek** [comment]
There are few broken tests and a lot of warning if we go with v5. My suggestion is to stay with latest v4 on this PR, btw v4 has forward compatibility layer https://github.com/sebastianbergmann/phpunit/commit/a55235c033c2dc18db631cc6b804844f6d37615a. Then I will do another PR with upgrade to v5 with warnings cleared.

**Comment by MarioBlazek** [comment]
@andrerom @emodric WDYT ?

**Comment by emodric** [comment]
@MarioBlazek Good catch!

Looks good to me!

**Pull request merged**
