### PR TITLE
EZP-25967: Changing object name does not redirect correctly after publish

### PR DESCRIPTION
**Pull request by Nattfarinn**
**JIRA ticket related**: https://jira.ez.no/browse/EZP-25967

### CODE REVIEW

**Comment by pspanja** [comment]
Good catch, it looks like we can cover this with integration test as well.

**Comment by andrerom** [comment]
Nice.

So adjustments to integration test, and adjustments to name update integration tests to verify url alias and we are there 😉

**Comment by lserwatka** [comment]
@Nattfarinn can you please add integration tests. This issue breaks our demo scenarios, we should try to make it in the final release.

**Comment by andrerom** [comment]
@pspanja would you be able to help here, @Nattfarinn has some issues getting relevant tests to run. afaik local setup, but in worst case could be skipped tests fuck up.

**Comment by pspanja** [comment]
[The test](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/API/Repository/Tests/ContentServiceTest.php#L4484) does not catch it because the SPI cache for URL aliases is empty when the aliases are loaded. I managed to reproduce it by simply calling `listLocationAliases()` before publishing Content.

But then, this does not fix it, it really needs to be fixed on publish and not on update.

**Comment by andrerom** [comment]
> Edit: I guess real question is why clearLocation() is not taking care of it.

as in not being used, or as in it does not work as intended?

**Comment by andrerom** [comment]
> The test does not catch it because the SPI cache for URL aliases is empty when the aliases are loaded. I managed to reproduce it by simply calling listLocationAliases() before publishing Content.

Ok, so we can assert the value of the url alias before the publish operation as well with a comment saying this needs to be done to warm up cache.

**Comment by pspanja** [comment]
> as in not being used, or as in it does not work as intended?

Not working. I found the problem, `else` block in [`clearLocation()`](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php#L301) is missing:

```
$this->cache->clear('urlAlias', 'location', $locationId);
```

> Ok, so we can assert the value of the url alias before the publish operation as well with a comment saying this needs to be done to warm up cache and verify urlalias is updated on update.

Yes, we miss that approach in integration tests, so invalidation is not well covered.
Would be easier if we didn't reset the fixtures for almost every test.

**Comment by andrerom** [comment]
Ok, @pspanja could you handle alternative PR for this in the morning so we unblock this?

**Comment by pspanja** [comment]
Sure, I'm on it.

**Comment by Nattfarinn** [comment]
This PR is obsolete. @pspanja made another PR with improved solution: https://github.com/ezsystems/ezpublish-kernel/pull/1702

**Comment by andrerom** [comment]
Thanks @Nattfarinn and @pspanja

**Pull request closed without merging**
