### PR TITLE
EZP-24379: Made ContentType listing ordered by identifier

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24379

See https://github.com/ezsystems/PlatformUIBundle/pull/236

Nothing critical, but definitely nicer than WTF sorting.
Would be better if configurable, but this one is a low hanging fruit, so...

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @pspanja @bdunogier @dpobel @yannickroger @glye

**Comment by lolautruche** [comment]
@ezrobot I hate you

**Comment by pspanja** [comment]
+1 (if Travis agrees :)

**Comment by dpobel** [comment]
+1, a hardcoded order is better than a wtf order :)

**Comment by andrerom** [comment]
+1 (but @pspanja we should ideally have integration coverage, API doc and SPI doc change for this as well)

**Pull request merged**
