### PR TITLE
EZP-26705: Keyword field type indexes full text data

### PR DESCRIPTION
**Pull request by pspanja**
This is additional fix for https://jira.ez.no/browse/EZP-26705

Adds indexing full text data (keywords) + integration tests.

### CODE REVIEW

**Comment by pspanja** [comment]
Ping @alongosz @andrerom

**Comment by andrerom** [comment]
@pspanja and the failure?

**Comment by pspanja** [comment]
This is the failed build: https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/181660183

Reason is it installed Solr engine v1.2.0-alpha1, which does not include this fix: https://github.com/ezsystems/ezplatform-solr-search-engine/commit/54b669c58a8b01d05172c633f6b654bbdd7ea285. It's not relevant for this issue, so I merged it.

**Comment by andrerom** [comment]
ok

**Comment by andrerom** [comment]
*but strange that it picked alpha1 over beta1..*

**Comment by andrerom** [comment]
or simpler would be to delete the alpha tag, ok with you?

**Pull request merged**
