### PR TITLE
Implement EZP-24925: Extract XmlText field type out of kernel into separate repository

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves `ezpublish-kernel` part of https://jira.ez.no/browse/EZP-24925

This completely removes XmlText field type from this repository and updates test fixtures by replacing XmlText fields with converted RichText fields.

New repository for XmlText can be found here (still WIP): https://github.com/ezsystems/ezplatform-xmltext-fieldtype

Since conversion of `ezxml` → `docbook` depends on converters in XmlText field type (`Expanding` and `EmbedLinking` converters), the tests for this conversion are skipped it required classes are not found and container configuration is removed.

#### Followup
* https://jira.ez.no/browse/EZP-24968: Faulty `ezxml` → `docbook` conversion 

#### TODOs
- [x] Update `data/cleandata.sql` fixture

### CODE REVIEW

**Comment by pspanja** [comment]
The diff is not viewable because of the fixture update, contained in the first commit.
The rest of the changes can be viewed commit by commit.

Review ping @andrerom @bdunogier @dpobel @glye  @lolautruche @yannickroger

**Comment by andrerom** [comment]
+1

**Comment by pspanja** [comment]
This misses ezxmltext→ezrichtext conversion on cleandata.sql, working on it.

**Comment by pspanja** [comment]
Updated `cleandata.sql` in https://github.com/ezsystems/ezpublish-kernel/commit/1a0bc4b7984085127d29c612eff11010dc116ad0.

I've found that it contained (same as other fixtures) some invalid data (from RichText perspective), probably converted from a different format (ODF Import???). I've also found that republishing such data fixes inconsistencies, after that the conversion to RichText went without problems. So we should probably include this step in the conversion we will eventually provide.

**Comment by andrerom** [comment]
> I've found that it contained (same as other fixtures) some invalid data (from RichText perspective), probably converted from a different format (ODF Import???). I've also found that republishing such data fixes inconsistencies, after that the conversion to RichText went without problems. So we should probably include this step in the conversion we will eventually provide.

ok

**Comment by pspanja** [comment]
@andrerom @bdunogier AFAICS this needs an ezxmltext→ezrichtext update on [DemoBundle fixtures](https://github.com/ezsystems/DemoBundle/tree/master/Resources/installer/sql).
While I'm on that, is there anything else that needs to be converted as well?

**Comment by andrerom** [comment]
> While I'm on that, is there anything else that needs to be converted as well?

like in? well you should as mentioned check with Studio team, but I think they are already handling it there.

**Comment by pspanja** [comment]
I already checked with @lserwatka, they are covered there as the new DemoBundle that is in progress already uses RichText, so AFAIK current DemoBundle fixtures should be the last of it.

**Comment by pspanja** [comment]
And it finally passes :relieved:

**Comment by andrerom** [comment]
congrats, +1 still stands ;)

**Comment by pspanja** [comment]
Ping @andrerom @bdunogier @lolautruche 

This PR is mostly about XmlText removal, but last two commits add some new API required by the extracted field type.

In https://github.com/ezsystems/ezpublish-kernel/commit/eb9e946e51b902c557fee227c1fbed7ecea10fc8 I've implemented configuration of config parser from external bundle, that will define semantic configuration under `ezpublish` configuration key.

In https://github.com/ezsystems/ezpublish-kernel/commit/dbb1e368d5afa94bec9a11c727763361a58d8b42 I've added the possibility to add default settings from the external bundle, that will be available for resolving under `ezpublish` key. The same could probably be achieved by importing default settings to the main `ezpublish.yml`, however this approach does not require manual configuration.

**Comment by pspanja** [comment]
Added possibility to customize setup factory container from external repo in https://github.com/ezsystems/ezpublish-kernel/commit/d40e3faf9e5bcf6aab78eeaea4409dc07e0564ef.

**Comment by bdunogier** [comment]
I've looked at the changes to the CoreBundle, and they look good.

But if you don't mind, I'd really like it if you could use a distinct issue & PR for those. They're important enough for that, I think.

**Comment by pspanja** [comment]
@bdunogier Thanks, I'll open a new issue and extract the changes.

**Comment by pspanja** [comment]
@bdunogier FYI: https://jira.ez.no/browse/EZP-24999 and https://github.com/ezsystems/ezpublish-kernel/pull/1477

**Pull request merged**
