### PR TITLE
URLs updated

### PR DESCRIPTION
**Pull request by DavidLiedle**
Changed default link URLs to point to our new documentation.

### CODE REVIEW

**Comment by andrerom** [comment]
+1

@SylvainGuittard looks ok in regards to the other dumps as well?

**Comment by glye** [comment]
+1

**Comment by SylvainGuittard** [comment]
+1
@andrerom: it's ok.

**Comment by andrerom** [comment]
Thanks :)

**Comment by emodric** [comment]
Shouldn't `original_url_md5` also be updated? :)

**Comment by andrerom** [comment]
@emodric you are right, aware if that is just a simple md5 of the url, or something else?

**Comment by emodric** [comment]
Looks like it is: https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/LegacyStorage.php#L152-L154

**Comment by andrerom** [comment]
fixed in dd81708f2e7d94030f255e26d0d7b30c9f040847

**Pull request merged**
