### PR TITLE
EZP-24924: Extract Page field type out of kernel into separate repository

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-24924
#### Should be merged after https://github.com/ezsystems/ezplatform-page-fieldtype/pull/1 + release

Note that some parts of the field type still remain in kernel:
1. A set of global layouts and block is registered [here](https://github.com/ezsystems/ezpublish-kernel/blob/impl-EZP-24924-extract-page-fieldtype/eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php#L51).
   Moving that out to the field type's repository would require implementing an API that would handle that case in general. I did not go for that here as it should be discussed first.
2. [View manager](https://github.com/ezsystems/ezpublish-kernel/blob/impl-EZP-24924-extract-page-fieldtype/eZ/Publish/Core/MVC/Symfony/View/Manager.php) still contains methods handling block view providers and rendering. It is awkward to make this service extensible, but it would also mean breaking the interface and user implementations based on it. Furthermore, in https://github.com/ezsystems/ezpublish-kernel/commit/8ba42aef4899fcc5e19ca5351fe1b81480310e58 it is hinted that the service is actually deprecated/kept for BC reasons, so that angle is also something to consider.

Related to point 1, the field type also registers some parameters merging global and default layout and block data. This part was extracted, using [new API method](https://github.com/ezsystems/ezpublish-kernel/blob/impl-EZP-24924-extract-page-fieldtype/eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php#L564). IMHO this should be handled together with point 1, meaning we either create API for the case or keep it contained in Core bundle.

Aside from this, the extraction is tested and is functional.

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by pspanja** [comment]
@andrerom updated the description, there are some open questions.

**Comment by emodric** [comment]
https://github.com/ezsystems/ezpublish-kernel/pull/1496 & https://github.com/ezsystems/ezpublish-kernel/pull/1510 modified some behaviour that touches the block rendering, so this will probably need updating to match.

**Comment by bdunogier** [comment]
Updated to the latest changes from master.

Some of the changes will have to be adapted on the extracted repository, but we should manage. The most urgent thing is that the kernel is clean.

**Comment by bdunogier** [comment]
About point 1 in the description:

> A set of global layouts and block is registered here. Moving that out to the field type's repository would require implementing an API that would handle that case in general. I did not go for that here as it should be discussed first.

Unless I'm misunderstanding, semantic configuration can now be added to `ezpublish` by 3rd party bundles: https://github.com/ezsystems/ezpublish-kernel/pull/1477. We should probably use that here.

**Comment by bdunogier** [comment]
About the `ViewManager`, we are really annoyed here...

Yes it is deprecated, but it is referring to classes that don't exist anymore. Is that okay from php's perspective ? From phpunit's, it's not, [according to the tests](https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/92967741).

I'm really not sure how we can fix this cleanly. The PSR-4 mapping also constrains us here, since the `Block` class referenced by the ViewManager is in the same namespace than the FieldType.

**Comment by andrerom** [comment]
Can we adapt it?

**Comment by andrerom** [comment]
fyi @alongosz _(I assume we want to do this in 8.0)_

**Pull request closed without merging**
