### PR TITLE
EZP-30664: Skipped indexing erroneous Content and logged all exceptions

### PR DESCRIPTION
**Pull request by SerheyDolgushev**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-30664](https://jira.ez.no/browse/EZP-30664)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `6.7`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

Similar to https://github.com/ezsystems/ezplatform-solr-search-engine/pull/139, but it is done for legacy search engine.

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by SerheyDolgushev** [comment]
@alongosz @andrerom

**Comment by alongosz** [comment]
Indeed it might be worth to fix it on all LTS-es.

**Comment by andrerom** [comment]
Ok, seems all is clear then. So @SerheyDolgushev, change branch to 6.7 here and 1.5 on solr. And also add something like the following on `IncrementalIndexer::updateSearchIndex()`:

```diff
      * Then item is removed from index, if not it is added/updated.
+     *
+     * If generic unhandled exception is thrown, then item is skipped and warning is logged.
      *
      * @param int[] $contentIds
```

**Comment by SerheyDolgushev** [comment]
@andrerom done.

**Comment by alongosz** [comment]
> Unsure, I think we rather should put some focus on finishing #2221 as it does this more cleanly.

Indeed that one provides much more improved solution... but probably won't solve the issue at hand. Please notice that for #2221 to work, custom 3rd party FT implementation must handle exceptions by throwing `InvalidIndexDataException`. So this implies much more work including convincing maintainers to upgrade their code ;)
But not saying no, just stating some context info.

**Comment by kmadejski** [comment]
> custom 3rd party FT implementation must handle exceptions by throwing InvalidIndexDataException.

@alongosz not really, there is nothing against to catch generic `\Exception` in the indexer and pass the message into the collector as well. This way you don't have to convince anyone to anything. Anyway, let's move this discussion to the right place 🙂

**Comment by andrerom** [comment]
@alongosz Aslo, I believe @SerheyDolgushev had the more or less exact same issue @kmadejski solves in the other PR: invalid xml in RichText **and/or** XmlText.

@SerheyDolgushev could you please provide the info on that in the ticket?

**Comment by SerheyDolgushev** [comment]
@andrerom 
Copy pasting possible error scenarios from https://github.com/ezsystems/ezplatform-solr-search-engine/pull/139:

Few strange scenarios:
1. Trying to index a field type without `indexable`:
```
[2019-06-10 22:13:29] console.ERROR: Error thrown while running command "ezplatform:reindex --content-ids='35617,35618,35619,35620,35622,35624,35625,35627,35629,35630,35631,35632,35633,35634,35635,35637,35638,35639,35640,35641,35642,35643,35644,35645,35646,35648,35650,35655,35660,35664,35665,35667,35669,35676,35677,35680,35681,35684,35686,35688,35691,35692,35693,35694,35695,35696,35697,35700,35701,35702' --env=dev". Message: "No type registered for ezbotrvideo." {"exception":"[object] (OutOfBoundsException(code: 0): No type registered for ezbotrvideo. at /Users/sd/Projects/XXX/platform/vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/Search/Common/FieldRegistry.php:58)","command":"ezplatform:reindex --content-ids='35617,35618,35619,35620,35622,35624,35625,35627,35629,35630,35631,35632,35633,35634,35635,35637,35638,35639,35640,35641,35642,35643,35644,35645,35646,35648,35650,35655,35660,35664,35665,35667,35669,35676,35677,35680,35681,35684,35686,35688,35691,35692,35693,35694,35695,35696,35697,35700,35701,35702' --env=dev","message":"No type registered for ezbotrvideo."} []
```
2. Trying to index the content with invalid RichText field:
```
[2019-06-10 21:53:51] console.ERROR: Error thrown while running command "ezplatform:reindex --content-ids='4,10,11,12,13,14,41,42,45,49,50,51,52,54,56,57,104,105,506,507,508,509,514,518,519,520,523,524,525,526,527,528,529,530,531,533,534,535,536,539,541,543,545,547,548,551,553,555,557,558' --env=dev". Message: "Warning: DOMDocument::loadXML(): Entity 'nbsp' not defined in Entity, line: 1" {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: DOMDocument::loadXML(): Entity 'nbsp' not defined in Entity, line: 1 at /Users/sd/Projects/XXX/platform/vendor/ezsystems/ezplatform-richtext/src/lib/eZ/FieldType/RichText/RichTextStorage.php:131)","command":"ezplatform:reindex --content-ids='4,10,11,12,13,14,41,42,45,49,50,51,52,54,56,57,104,105,506,507,508,509,514,518,519,520,523,524,525,526,527,528,529,530,531,533,534,535,536,539,541,543,545,547,548,551,553,555,557,558' --env=dev","message":"Warning: DOMDocument::loadXML(): Entity 'nbsp' not defined in Entity, line: 1"} []
```
And there might be more strange cases

**Comment by SerheyDolgushev** [comment]
@andrerom sorry, does this PR (and https://github.com/ezsystems/ezplatform-solr-search-engine/pull/139) should be closed in the flavor of PRs submitted by @kmadejski)?

**Comment by micszo** [comment]
@andrerom @alongosz Should this still go to 6.7 when we don't support 1.7 since January? :)

**Comment by lserwatka** [comment]
@micszo no, it should start from 6.13 if relevant.

**Comment by micszo** [comment]
@SerheyDolgushev could you please update base and rebase?

**Comment by andrerom** [comment]
@SerheyDolgushev remember to update base here first before you push (`git rebase -i 6.13`) rebased branch

**Comment by SerheyDolgushev** [comment]
@andrerom I did:
1. Synced my local 6.7 and 6.13 from the upstream
2. Made `git rebase --onto 6.13 6.7`
3. Change the base in PR
4. Pushed

**Comment by micszo** [comment]
Would it make sense - is it possible - to add a newline to improve the style of the output?
Screenshot 2020-02-20 at 09 06 18

**Comment by alongosz** [comment]
> Would it make sense - is it possible - to add a newline to improve the style of the output?

@micszo This is a monolog log, not an output, so not really. Adding it here is a bit artificial and would result in blank lines in log files as well. AFAICS we don't have control over output in this case, it's a side effect of `ProgressBar` handling output next to Monolog. It might be possible to tweak ProgressBar, but that needs to be investigated. Please check on 7.5, I have a feeling it might look better there on Symfony 3.4.

**Comment by micszo** [comment]
Indeed, looks better on 2.5.
Screenshot 2020-02-20 at 09 43 05

**Comment by lserwatka** [comment]
@alongosz could you merge it up?

**Comment by alongosz** [comment]
Merged up to `7.5` as 473879935160fc984dbe274479547ee409b82baa and `master` as a75c0a9cec5ef749910739ebc0161bbdcddea767.

Thank you @SerheyDolgushev :tada:

**Pull request merged**
