### PR TITLE
EZP-27324: Proper media/binary uri is now shown & generated for old content versions

### PR DESCRIPTION
**Pull request by ViniTou**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-27324](https://jira.ez.no/browse/EZP-27324)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `7.5`
| **BC breaks**      | no
| **Tests pass**     | no
| **Doc needed**     | no

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Review by alongosz — APPROVED** [review]

**Review by lserwatka — APPROVED** [review]

**Review by adamwojs — APPROVED** [review]

**Review by micszo — COMMENTED** [review]
On eZ Platform EE 2.5 there is a regression when creating a draft from the latest version.

**Steps**:
0. Start with a clean session after applying the changes.
1. Create a CT with ezmedia and ezbinaryfile fields.
2. Create a CI using that CT.
3. Upload a valid video and e.g. pdf file.
4. Publish.
5. Enter edit mode.
6. Examine media and file fields.

**Actual result**: On the media field there's a constant spinner. On the file field when trying to preview a redirect to login happens.

EZP-27324

**Comment by lserwatka** [comment]
@micszo Let's merge this one, and fill a new ticket. @ViniTou will have a look. This PR is blocking work in 3.1.

**Comment by micszo** [comment]
@lserwatka ok 😄 🙈 
I will create a ticket shortly.

**Comment by micszo** [comment]
Ticket for the above issue: https://jira.ez.no/browse/EZP-31639.

**Pull request merged**
