### PR TITLE
EZP-31351: Added a new argument to check the permissions for embedded…

### PR DESCRIPTION
**Pull request by mateuszdebinski**
… content

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-31351](https://jira.ez.no/browse/EZP-31351)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | 7.5
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

This problem has already occurred, [More information](https://github.com/ezsystems/ezpublish-kernel/commit/7e6c07803ed2d09c7a54d68cae663537fd479708#r34740938)

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by kmadejski** [comment]
Ref: https://github.com/ezsystems/ezpublish-kernel/pull/2419

**Comment by mateuszdebinski** [comment]
@micszo, For this problem, created a new ticket [EZP-31358](https://jira.ez.no/browse/EZP-31358)

**Comment by lserwatka** [comment]
@adamwojs could you merge it up?

**Comment by adamwojs** [comment]
Done.

**Pull request merged**
