### PR TITLE
Use namespaced MockObject

### PR DESCRIPTION
**Pull request by MarioBlazek**
PHPUnit 6.5 ships `phpunit-mock-object` v5, which has got updated with namespaces (https://github.com/sebastianbergmann/phpunit-mock-objects/pull/376). This PR updated tests with namespaced MockObject.

### CODE REVIEW

**Comment by MarioBlazek** [comment]
Failing test is fixed here https://github.com/ezsystems/ezpublish-kernel/pull/2242.

**Comment by MarioBlazek** [comment]
@alongosz please review.

**Comment by andrerom** [comment]
Can be rebased now

**Comment by MarioBlazek** [comment]
@andrerom PR rebased.

**Pull request merged**
