### PR TITLE
EZP-30316: Improve default password requirements for User fields

### PR DESCRIPTION
**Pull request by glye**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-30316](https://jira.ez.no/browse/EZP-30316)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | 7.4
| **BC breaks**      | no
| **Tests pass**     | TBD
| **Doc needed**     | yes

Set stricter default password requirements for the standard User content type, and for new User fields. The features for this are introduced in 7.4, so it can't be backported further.

I didn't make this configurable, as these are not hardcoded setting values, they are defaults, and can be changed by editing the User content type. Configurable defaults would be meta-configuration, kind-of :)

Existing lower quality passwords are not affected, the change affects only new passwords.

- [x] Require 10 characters minimum.
- [x] Require upper and lower alphabetic characters, and digits. Do not require other characters.
- [x] Ensure that this applies both to the standard User content type (default DB content, for new installs), and to any new User field types created.
- [x] Fix breaking tests.
- [x] ~Add new tests to verify the change.~ This seems to be well enough covered [here](https://github.com/ezsystems/ezpublish-kernel/blob/ca35b890be6dc61e242a180d2fc9d33b9a8bfa1e/eZ/Publish/Core/Repository/Tests/Service/Mock/UserPasswordValidatorTest.php#L29)

The same in legacy: https://github.com/ezsystems/ezpublish-legacy/pull/1423

### CODE REVIEW

**Comment by glye** [comment]
@alongosz It is marked as "improvement". Existing passwords are not affected. Login works fine, you won't notice it until you try to change password or create new users.

**Comment by alongosz** [comment]
> until you try to change password or create new users.

My point exactly. New behavior => BC break. This is indeed minor change and change for the best. So I'm fine with this, but for `master`.
I'd allow it for 7.4 if this was critical security issue, despite BC breaks. But it's not, it's a matter of configuration.

**Comment by glye** [comment]
@alongosz Self-correction: It won't affect you when you change your password or create new users either, since the setting is tied to the field type. It only comes into effect when you create new User *content types*, or make a new installation from scratch. Do you still feel the same way about it?

**Comment by alongosz** [comment]
> It only comes into effect when you create new User content types

When creating new Content-Type, does a user see the new default choices or does this happen implicitly?

**Comment by glye** [comment]
@alongosz Yes, the new defaults are shown in the UI when creating the new CT. Just verified.

@lserwatka Did you see my self-correction 5 min ago?

**Comment by glye** [comment]
I'm cool with moving this to master. I wouldn't rush it into 2.5 at the very last moment, unless you want it, @lserwatka. If master, we should do the same with the legacy PR, as it impacts users more directly than this Platform PR does. I'll add changelog doc too.

**Comment by lserwatka** [comment]
W can still merge it for 2.5. (master)

**Comment by alongosz** [comment]
Exactly, master is good for this. We should also let know @ezsystems/documentation-team that after merge we'll need a mention in release notes that this changed.

Of course having some QA tests before merging would be great.

**Comment by glye** [comment]
New PR, to cleanup the noise: https://github.com/ezsystems/ezpublish-kernel/pull/2570

**Pull request closed without merging**
