### PR TITLE
Implement EZP-24904: improve indexable for Country field type

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-24904

Complete country data is now indexed, including country names, IDC and Alpha2 and Alpha3 codes.

### CODE REVIEW

**Comment by pspanja** [comment]
Review ping @andrerom @bdunogier @glye @lolautruche @yannickroger

**Comment by andrerom** [comment]
+1

**Comment by glye** [comment]
+1, leaving the short array discussion to others :)

**Comment by lolautruche** [comment]
+1

**Pull request merged**
