### PR TITLE
Fix EZP-23973: Move Legacy Search Engine implementation to new namespace

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-23973, a sub-task for https://jira.ez.no/browse/EZP-23940

Followup: https://jira.ez.no/browse/EZP-23975

This moves Legacy Search Engine implementation to `eZ\Publish\Core\Search` and updates container configuration accordingly.

As mentioned in https://github.com/ezsystems/ezpublish-kernel/pull/1160, EzPublishCoreBundle extension is updated to load new Legacy Search Engine configuration file.

### CODE REVIEW

**Comment by pspanja** [comment]
This is #1160 reopened against `master`.

Review ping @andrerom, @bdunogier, @glye, @lolautruche, @yannickroger.

**Comment by bdunogier** [comment]
+1 "if it works" :-)

**Comment by pspanja** [comment]
Travis borked, let's try it again.

**Comment by andrerom** [comment]
+1 if it works and with some squashing ;)

**Comment by pspanja** [comment]
I intentionally made commits more granular to ease the backports, as this needs to go down to 5.3. So I planned to merge it as is. It should pass now, there were some unrelated failures.

**Comment by pspanja** [comment]
Well... it failed again. It will have to wait for that stuff to get fixed.

**Comment by andrerom** [comment]
Hmm, I'm not sure we want to backport the moving of the implementations, but maybe lets discuss that tomorrow.

**Comment by andrerom** [comment]
(but my +1 still stand, get this train moving)

**Pull request merged**
