### PR TITLE
EZP-25151: total count in REST search results

### PR DESCRIPTION
**Pull request by bdunogier**
> Implements https://jira.ez.no/browse/EZP-25151

Adds `count`, with the total results count, to the Result node.
Also adds `time`, `timedOut` and `maxScore`, as per [specs](https://github.com/ezsystems/ezpublish-kernel/blob/master/doc/specifications/rest/REST-API-V2.rst#L7464-L7467).

### CODE REVIEW

**Comment by dpobel** [comment]
that was quick :)
+1

**Comment by mhyndle** [comment]
+1

**Comment by andrerom** [comment]
+1

**Comment by bdunogier** [comment]
Thank you guys.

**Pull request merged**
