### PR TITLE
EZP-25380: REST Add ContentInfo to TrashItem

### PR DESCRIPTION
**Pull request by andrerom**
https://jira.ez.no/browse/EZP-25380

### CODE REVIEW

**Comment by yannickroger** [comment]
Seems travis is not happy about it  :confused:

**Comment by andrerom** [comment]
> Seems travis is not happy about it  :confused:

I was expecting that, should have mentioned with todo that I still needed to verify if everything passed.
Fixed now _(hopefully)_ ;)

**Comment by yannickroger** [comment]
I had to restart one of the jobs, but it's all green now

**Comment by yannickroger** [comment]
The REST API spec should also be updated.

**Comment by andrerom** [comment]
> The REST API spec should also be updated.

done

**Comment by bdunogier** [comment]
+1

**Comment by yannickroger** [comment]
+1

**Pull request merged**
