### PR TITLE
EZP-24499 : adding clauses to reduce number of results for contents w…

### PR DESCRIPTION
**Pull request by flovntp**
…ith multiple location and multiple translation

This is a try to solve https://jira.ez.no/browse/EZP-24499
by adding clauses 
 - on the join on ezcontentobject_name (if a list of languages is passed to the function) 
 - on the join on ezcontentobject_tree to get only the main location info.

### CODE REVIEW

**Comment by bdunogier** [comment]
Ping @pspanja @andrerom.

**Comment by pspanja** [comment]
I think we can do more here. The comment in the code says we can't join with Content name language, but that is not really true. Legacy SE will always store full set of fields for all Content translations, and we can use that to join with `ezcontentobject_name`. Here is what I came up with, and it passes aside from a single problem with incorrect fixture:

```diff
diff --git a/eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase/QueryBuilder.php b/eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase/QueryBuilder.php
index 9e4f6cc..0f47790 100644
--- a/eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase/QueryBuilder.php
+++ b/eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase/QueryBuilder.php
@@ -90,13 +90,13 @@ class QueryBuilder
             $this->dbHandler->aliasedColumn( $query, 'main_node_id', 'ezcontentobject_tree' )
         )->from(
             $this->dbHandler->quoteTable( 'ezcontentobject' )
-        )->leftJoin(
+        )->innerJoin(
             $this->dbHandler->quoteTable( 'ezcontentobject_version' ),
             $query->expr->eq(
                 $this->dbHandler->quoteColumn( 'contentobject_id', 'ezcontentobject_version' ),
                 $this->dbHandler->quoteColumn( 'id', 'ezcontentobject' )
             )
-        )->leftJoin(
+        )->innerJoin(
             $this->dbHandler->quoteTable( 'ezcontentobject_attribute' ),
             $query->expr->lAnd(
                 $query->expr->eq(
@@ -115,13 +115,9 @@ class QueryBuilder
                 $this->dbHandler->quoteColumn( 'contentobject_id', 'ezcontentobject_version' )
             )
         )
-        // @todo: Joining with ezcontentobject_name is probably a VERY bad way to gather that information
-        // since it creates an additional cartesian product with translations.
         ->leftJoin(
             $this->dbHandler->quoteTable( 'ezcontentobject_name' ),
             $query->expr->lAnd(
-                // ezcontentobject_name.content_translation is also part of the PK but can't be
-                // easily joined with something at this level
                 $query->expr->eq(
                     $this->dbHandler->quoteColumn( 'contentobject_id', 'ezcontentobject_name' ),
                     $this->dbHandler->quoteColumn( 'contentobject_id', 'ezcontentobject_version' )
@@ -129,6 +125,10 @@ class QueryBuilder
                 $query->expr->eq(
                     $this->dbHandler->quoteColumn( 'content_version', 'ezcontentobject_name' ),
                     $this->dbHandler->quoteColumn( 'version', 'ezcontentobject_version' )
+                ),
+                $query->expr->eq(
+                    $this->dbHandler->quoteColumn( 'content_translation', 'ezcontentobject_name' ),
+                    $this->dbHandler->quoteColumn( 'language_code', 'ezcontentobject_attribute' )
                 )
             )
         );
```

**Comment by andrerom** [comment]
@pspanja was that in addition or instead of this PR?

**Comment by pspanja** [comment]
> was that in addition or instead of this PR?

It is instead of it, basically joining with `ezcontentobject_name` over language in `ezcontentobject_attribute` will not expand result set, and the rest can remain the same. Language filtering then remains done by the `WHERE` clause.

This of course depends on Content having correct set of fields, and the failure is with fixture that was manually adjusted. I think we could use `INNER JOIN` as well, this adds more failed tests, but maybe it's about bad fixtures again. Should be investigated as it might bring performance improvements.

> we should btw probably add unit tests in legacy engine to verify this issue is fixed, and verify it stays that way.. :)

Yes I agree :)

@flovntp do you have time to take care of it? I can take over but not sure when :)

**Comment by andrerom** [comment]
ok

I don't think @flovntp has time, so added it to sprint but prioritized after the current sprint tasks so we can handle it soonish.

**Pull request closed without merging**
