### PR TITLE
EZP-26075: Keyword field type not indexed by Solr Search Engine

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-26705

this implements `Indexable` for the `Keyword` field type + integration tests.

### CODE REVIEW

**Comment by andrerom** [comment]
Seems to be missing indexing for legacy search engine, any issues there?

**Comment by pspanja** [comment]
Should be OK, I just forgot to implement it.

**Comment by pspanja** [comment]
Now added support for Legacy search engine. This is limited in the same way as is the case with other similar field types, for example RelationList. See https://github.com/ezsystems/ezpublish-kernel/blob/dce4e24052d3d3b5400d7a11798825e47d522138/eZ/Publish/API/Repository/Tests/FieldType/SearchMultivaluedBaseIntegrationTest.php#L99-L119

Also, using Legacy admin will destroy data that it used for sorting with Legacy engine, since it's not searchable (sortable) there.

**Comment by andrerom** [comment]
> Also, using Legacy admin will destroy data that it used for sorting with Legacy engine, since it's not searchable (sortable) there.

that is ok

**Comment by pspanja** [comment]
All passes now aside from Solr, which fails on resolving dependencies.

**Pull request merged**
