### PR TITLE
EZP-24092: Optimize queries to not perform count when not needed

### PR DESCRIPTION
**Pull request by andrerom**
https://jira.ez.no/browse/EZP-24092

Also see DemoBundle PR:
https://github.com/ezsystems/DemoBundle/pull/146

### CODE REVIEW

**Comment by pspanja** [comment]
I'm not clear why we set `$nbResults` in `getSlice()`, but it was not introduced here.
Aside from tests requiring an update it looks good to me, +1.

**Comment by andrerom** [comment]
It is a bit of pre optimization so it won't need to be fetched if we already got it.

I'll look at the test failure ;)

**Comment by crevillo** [comment]
+1

**Comment by yannickroger** [comment]
+1

**Pull request merged**
