### PR TITLE
Fix EZP-24568: Remove InvalidArgumentException when position of a FieldDefinition is 0

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24568

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @bdunogier @pspanja @glye

**Comment by glye** [comment]
+1

**Comment by pspanja** [comment]
The exception message should be updated as well, it is out of sync now.
It says strictly greater than 0 is required, is that still valid, or...?

**Comment by lolautruche** [comment]
@pspanja Woops you're right :-)

**Comment by lolautruche** [comment]
Fixed @pspanja

**Comment by pspanja** [comment]
What about the reason for validating it in the first place?
I can't remember why it was done, but maybe it is still valid for some reason (Legacy Stack?).

**Comment by lolautruche** [comment]
@pspanja Discussed with @andrerom. And we obviously need some computing when manipulating FieldDefinitions. Where this computing belongs to is subject to more discussion (let's talk about it next week).
The problem here is that we have a big inconsistency avoiding content type edition to work properly. AFAIR, it was done in the same way than legacy. But there is no blocker using `0`.

**Comment by pspanja** [comment]
Ok, in that case +1.

**Comment by lolautruche** [comment]
Tests with PHP 7 end up with a segfault... May I merge any way?

**Comment by joaoinacio** [comment]
What about -1?

**Comment by lolautruche** [comment]
Why @joaoinacio ?
PHP 7 is still unstable (but was removed from allowed failures for speed reasons), and it's the only version we have a segmentation fault in. And I'm pretty sure it will happen in other PRs

**Comment by joaoinacio** [comment]
The message states `an integer greater than or equal to 0` but `-1` is int, so it doesn't match the check exactly?

**Comment by lolautruche** [comment]
It seems to happen on all new builds (see #1333). So I'll blame PHP 7 beta

**Comment by lolautruche** [comment]
ah sorry @joaoinacio, I thought you were on the PHP 7 fail :smile: 
`-1` is still valid, you're right.

**Comment by lolautruche** [comment]
Message fixed @joaoinacio, thanks :+1:

**Comment by andrerom** [comment]
+1 if travis agrees, if php 7 disagrees and it is definitely php7's  fault then you need to also put PHP7 back in allow failure list.

**Comment by lolautruche** [comment]
@andrerom See #1333 from @pspanja . Same segmentation fault. So I'll put back PHP7 on allow failure list, directly on master and rebase this one.

**Comment by andrerom** [comment]
Passing, merging ;)

**Pull request merged**
