### PR TITLE
EZP-25854: Relation FieldType SQL INSERT error on Content Type editing

### PR DESCRIPTION
**Pull request by wizhippo**
Issue: Details: https://jira.ez.no/browse/EZP-25854

On editing the a content type with object relation, you'll get SQL insert error about wrong type _(if mysql is configured to error on type issues)_.

### CODE REVIEW

**Comment by crevillo** [comment]
well... depends... for which content type is this change being done? Please note there are some people that prefer to place their images under media root folder and then use objectrelation for relating a content (say an article) with the image. 
So +0.5 on my side :)

**Comment by andrerom** [comment]
Whats the context here?
On several content types we changed to relation intentionally, and this is part of a theme of changes that in the end will make relation(s) first class citizen when it comes to asset handling.

**Comment by wizhippo** [comment]
At the moment after a clean install if you try to edit the Article type you cannot.  An exception is thrown as it tries to store a "" in the data_int2 field.  I was trying to track it down and found this in the db.  It no longer throws an exception.  Maybe it is another issue here

**Comment by crevillo** [comment]
then maybe the fieldtype is trying to store a string instead an int there?

**Comment by wizhippo** [comment]
Missed this.  https://github.com/ezsystems/ezpublish-kernel/pull/1668 related issue.  Looks like https://github.com/ezsystems/ezpublish-kernel/blob/196bd047bd3d9e851e7a125d331c2e459f8792ce/eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/RelationConverter.php#L73 is trying to store a string where an it should be.

**Comment by andrerom** [comment]
Duplicates #1668, could one of you try the following patch instead? /cc @janit 


```diff
diff --git a/eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/RelationConverter.php b/eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/RelationConverter.php
index 428797a..fa56acd 100644
--- a/eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/RelationConverter.php
+++ b/eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/RelationConverter.php
@@ -67,10 +67,10 @@ class RelationConverter implements Converter
     public function toStorageFieldDefinition(FieldDefinition $fieldDef, StorageFieldDefinition $storageDef)
     {
         // Selection method, 0 = browse, 1 = dropdown
-        $storageDef->dataInt1 = $fieldDef->fieldTypeConstraints->fieldSettings['selectionMethod'];
+        $storageDef->dataInt1 = (int)$fieldDef->fieldTypeConstraints->fieldSettings['selectionMethod'];
 
         // Selection root, location ID
-        $storageDef->dataInt2 = $fieldDef->fieldTypeConstraints->fieldSettings['selectionRoot'];
+        $storageDef->dataInt2 = (int)$fieldDef->fieldTypeConstraints->fieldSettings['selectionRoot'];
     }
 
     /**
```

**Comment by wizhippo** [comment]
What should it be? I see in the type constraints this should be a string https://github.com/ezsystems/ezpublish-kernel/blob/196bd047bd3d9e851e7a125d331c2e459f8792ce/eZ/Publish/Core/FieldType/Relation/Type.php#L40

**Comment by andrerom** [comment]
In the database it has to be int, and in he field definition value it needs to be empty string if none is selected. See `toFieldDefinition` and it becomes clear.

**Comment by wizhippo** [comment]
@andrerom You patch works here.  Do you want me to update this PR with it?

**Comment by andrerom** [comment]
> @andrerom You patch works here. Do you want me to update this PR with it?

yes please :)

**Comment by wizhippo** [comment]
done.

**Comment by andrerom** [comment]
+1

ping @crevillo @bdunogier

**Comment by crevillo** [comment]
i'm +1. but wondering something maybe for another issue:
the `$storageDef->dataInt2` is meant to keep a location Id. If `$fieldDef->fieldTypeConstraints->fieldSettings['selectionRoot'];` is empty this patch will add a `0` in that field... But we don't have any location with  `id = 0`, do we? in other words, don't know if we could save the root location id there... 

But on the other side, if the 0 is enough and don't have any other implications, is of course fine.

**Comment by andrerom** [comment]
@crevillo see what I wrote to @wizhippo:

> See RelationConverter::toFieldDefinition and it becomes more clear.

**Pull request closed without merging**
