### PR TITLE
Fix EZP-24612: Switch CS to PSR-2

### PR DESCRIPTION
**Pull request by lolautruche**
Used [PHP-CS-Fixer](http://cs.sensiolabs.org) with `symfony` *level*, but deactivating the following fixers:

* `concat_without_spaces` (actually enforces `concat_with_spaces` from contrib level)
* `empty_return`
* `phpdoc_params`
* `spaces_cast`

### CODE REVIEW

**Comment by gggeek** [comment]
Go home ezrobot, you're obsolete :-D
Either that, or some configs have to be changed...

**Comment by lolautruche** [comment]
@gggeek Actually, that was helpful :wink: . It showed wherever things need to be fixed manually.

**Comment by lolautruche** [comment]
OK, let's try another round

**Comment by orlangur** [comment]
> Used PHP-CS-Fixer with only psr2 level.

**Comment by andrerom** [comment]
that could be an alternative, but the remaining issues here is in our opinion to strict, it is forcing multiline conditions to be placed on one line, often breaking the soft limit line length, and sometimes also the hard one potentially.

**Comment by lolautruche** [comment]
Ping @bdunogier @yannickroger @glye @pspanja 

Note that @ezrobot is pretty long (no cache yet for php-cs-fixer on Jenkins)

**Comment by pspanja** [comment]
+1 with last bits fixed.

**Comment by lolautruche** [comment]
Everything has passed now. Merging

**Comment by pspanja** [comment]
Goodbye ezcs, you were the pinnacle of readability... :sob:

**Pull request merged**
