### PR TITLE
[SearchService] Remove validateSortClauses() & deprecate SortClause $languageCode

### PR DESCRIPTION
**Pull request by andrerom**
https://jira.ez.no/browse/EZP-24602

### CODE REVIEW

**Comment by andrerom** [comment]
Ready for review @pspanja @glye 

Some background: As this is being deprecated, and as the validation here is rather heavy, it is here suggested to remove this behavior (the check).

**Comment by pspanja** [comment]
It looks like the Legacy engine will already take the main language if not specified on the sort clause, but I think we should still test this to avoid surprises.

**Comment by glye** [comment]
+1, but @pspanja may have a point about keeping tests, if applicable...?

**Comment by andrerom** [comment]
@pspanja I think what you are talking about (testing the cases where exception is *not* thrown) is already covered by testMultilingualFieldSort tests.

However is it so that you say we should still keep the check for cases where languageCode is specified?

If so behavior could be *(when we also have language priority in place)*:
- languageCode *not* specified
 - language filter **is** set: sort on the matched language field
 - language filter *not* set: sort on main language
- languageCode **is** specified: 
 - language filter **is** set: sort on matched language AND log deprecation notice informing languageCode is ignored
 - language filter *not* set:
  - field is non translatable: throw like now
  - field is translatable: **Use it or use main???** AND log deprecation notice

**Comment by pspanja** [comment]
> I think what you are talking about (testing the cases where exception is not thrown) is already covered by testMultilingualFieldSort tests.

Yes, there is no need to test it as it is already tested.

> However is it so that you say we should still keep the check for cases where languageCode is specified?
>
> If so behavior could be *(when we also have language priority in place)*:
>
> - languageCode is specified: 
>   - language filter *not* set:
>      - field *is non* translatable: throw like now
>      - field is translatable: *Use it or use main???* AND log deprecation notice

With language priority in place...

As things are right now if language filter is not set we search on main language. Otherwise if searching on all we said to forbid Field sort as it is ambiguous, so that would be a BC break.
Then for now, for translatable field we still have to use main language. So for now I would go for main language in both cases + deprecation notice.

So +1 for now and let's revisit when we have language priority and a an outcome on searching all translations.

**Comment by andrerom** [comment]
Closing, doc + deprecation log should be applies to 5.4 branch only.

**Pull request closed without merging**
