### PR TITLE
EZP-26000: Permissions lookup API

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-26000

Continuing on https://github.com/ezsystems/ezpublish-kernel/compare/repo_structure and as a first step of the issue, as a preparation for permission implementation of Repository this restructures existing code as follows:

- `eZ\Publish\Core\Repository` → `eZ\Publish\Core\Repository\DomainLogic`
- `eZ\Publish\Core\SignalSlot` → `eZ\Publish\Core\Repository\SignalSlot`

Namespace for the permission implementation of the Repository would be:

`eZ\Publish\Core\Repository\Permission`

### CODE REVIEW

**Comment by pspanja** [comment]
Review ping @bdunogier @alongosz @andrerom 

@bdunogier not sure if we can break stuff like this ATM, your call I guess :)

**Comment by gggeek** [comment]
@pspanja am I drunk, or you just aim to break 100% of end-user code which runs on EZPublish ?

**Comment by pspanja** [comment]
It's hardly more than 99%

**Comment by bdunogier** [comment]
Such a change would require a major version bump, indeed, as it does break BC with existing code.

Will look into it further tomorrow.

**Comment by andrerom** [comment]
@pspanja I think commenters probably have a point, the namespace changes in repo_structure belongs to 7.0 for instance. So until we get started on 7.0 kernel, we should identify what we may do in 6.x, like for instance introduction of decoupled permission service.

**Comment by gggeek** [comment]
@pspanja sorry, I am not sure I get the part "properly hinted stuff will not break". Is it because you are only changing the namespace of stuff in Core and not in Api ?

**Comment by gggeek** [comment]
PS: run a cursory grep for 'Core\Repository' on the codebase I am working on. 50 matches.
Plus, I am pretty sure that there was at least one case somewhere where API users *had* to typehint for a core class instead of an api class, maybe more... (I don't remember exactly where, must have been either related to content update structs or to Content vs. User)

**Comment by pspanja** [comment]
@andrerom, we can do Permission implementation, but place it as a sibling of SignalSlot, would that be ok with you?

@gggeek 
> Is it because you are only changing the namespace of stuff in Core and not in Api ?

Yes. Basically things can break if you incorrectly hinted on `Core\Repository` instead of `API\Repository`, or extended on stuff in `Core\Repository` (though it's pretty hard now with services hardocded in Repository implementation).

> run a cursory grep for 'Core\Repository' on the codebase I am working on. 50 matches.

I will have to check how our projects fare there, should be interesting :)

> I am pretty sure that there was at least one case somewhere where API users had to typehint for a core class instead of an api class, maybe more...

I would like to see that, because it would be a bug.
Does this ring a bell maybe: https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/142226400
(I didn't pin it yet)

**Comment by pspanja** [comment]
@gggeek `UserReference` maybe?

**Comment by andrerom** [comment]
> @andrerom, we can do Permission implementation, but place it as a sibling of SignalSlot, would that be ok with you?

unsure what you refer to, can't see full diff here and since it does not cherry pick to retain commits from repo_structure I'm not sure what you added.

**Comment by gggeek** [comment]
@pspanja I will have to investigate. One good starting point to look into is methods which have been added to interface/api classes in recent releases... (note that even if this was was fixed in 5.4.6, we still have code around which predates that version)

**Comment by pspanja** [comment]
Closing, thanks all for feedback.

**Pull request closed without merging**
