### PR TITLE
EZP-28148: Fix regression on loading all State (group) cache not getting update

### PR DESCRIPTION
**Pull request by andrerom**
> https://jira.ez.no/browse/EZP-28148

ping @gggeek 

### Review note

Yes the test fails without the fix ;)

### CODE REVIEW

**Comment by gggeek** [comment]
Thx for this :-) I will have to make Travis run a test against this PR, which will take me most likely a couple of days...

**Comment by andrerom** [comment]
@gggeek can you rerun tests against the latests micro tags please?

**Comment by gggeek** [comment]
Test started... kernel v6.7.6.1 downloaded...

**Comment by gggeek** [comment]
...and...

**Comment by gggeek** [comment]
GREEN!

https://travis-ci.org/kaliop-uk/ezmigrationbundle/jobs/301139088

Thanks for the quick turnaround!

**Pull request merged**
