### PR TITLE
EZP-27315: urls delivered with and without trailing slash

### PR DESCRIPTION
**Pull request by bernhard-roessler**
Ticket: https://jira.ez.no/browse/EZP-27315

### CODE REVIEW

**Comment by andrerom** [comment]
@bernhard-roessler could you add some more info on what the issue is? cause the patch seems more like a workaround from the first looks of it as it adds a second non described condition to a non relevant one. But if you add description on what you think behaves wrong that might help.

**Comment by siegfried-zach** [comment]
I try to provide more info:

- eZ generates URL's usually without trailing slash, e.g. a node can have this URL /sport
- eZ redirects if user enters wrong case, e.g. /Sport will be redirected to /sport
- eZ does not redirect when user enters trailing slash, so /sport/ will not be redirected to /sport (it delivers just the content)

So this PR would change the behaviour to redirect any url with trailing slash to the same url without trailing slash (and handling the special case for root url "/").

The request came from our client, as he has seen some URLs in GoogleAnalytics twice (with and without trailing slash). We did not further investigate, from where the trailing slash urls came from, just assumed to be good to deliver the content of a node just in "one" url variant.

**Comment by tharkun** [comment]
Great idea to solve this long time issue

**Comment by andrerom** [comment]
@lolautruche @pspanja Pov?  _(besides that it should probably be different if to clarify it is a different case, on top of possibility to do the check more efficiently)_

**Comment by lolautruche** [comment]
The use case seems legit to me.
Code change should go to `needsCaseRedirect()` method, which should be renamed then 😉

**Comment by andrerom** [comment]
@bernhard-roessler up for adjusting the code and target 6.7 branch?

**Pull request closed without merging**
