### PR TITLE
Fix EZP-26356: exception in rest parser exception handling

### PR DESCRIPTION
**Pull request by bdunogier**
> Fixes [EZP-26356](http://jira.ez.no/browse/EZP-26356)

### CODE REVIEW

**Comment by bdunogier** [comment]
Ping @glye.

**Comment by glye** [comment]
Not sure where that came from, but +1

in/ex-ception

**Comment by bdunogier** [comment]
I think it came from a copy paste from the service definition above :)

P.S. Remember that there's a review feature now, please approve.

**Comment by bdunogier** [comment]
yay

**Comment by bdunogier** [comment]
And sent to QA.

**Pull request merged**
