### PR TITLE
EZP-29322: As an editor I want to use translated Admin panel

### PR DESCRIPTION
**Pull request by mikadamczyk**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-29322](https://jira.ez.no/browse/EZP-29322)
| **Improvement**| no
| **New feature**    | yes
| **Target version** | `master`
| **BC breaks**      |no
| **Tests pass**     | yes
| **Doc needed**     |no

refers to https://github.com/ezsystems/ezplatform-admin-ui/pull/532

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by bdunogier** [comment]
By the way, I'd change the pull-request's title so that it describes what this particular PR does (instead of the story's title). A short description (2, 3 sentences) also helps reviewers and those who follow pull-requests.

**Comment by mikadamczyk** [comment]
First we must merge https://github.com/ezsystems/ezplatform-admin-ui/pull/532

**Comment by bdunogier** [comment]
It was reported in [EZP-29377](https://jira.ez.no/browse/EZP-29377) that in some cases, the english translation won't be picked up. I think it's because `available_translations` does not contain `en`, since this language isn't in `vendor/ezplatform-i18n/*`, but in the `Resources/translations` directory of each package.

I suggest that we fix it by always adding `en` to `available_translations`.

**Comment by damianz5** [comment]
+1 @bdunogier, also `'no_NO' => 'no',` is missing in `LOCATES_MAP`

**Pull request merged**
