### PR TITLE
EZP-23778: implement session-based auth support in BDD RestContext

### PR DESCRIPTION
**Pull request by joaoinacio**
JIRA: https://jira.ez.no/browse/EZP-23778

This adds support for session-based authentication in BDD's RestContext.
A new `authType` parameter may be added to behat.yml in REST suites to specify which method to use,
current default is "session" as per https://github.com/ezsystems/ezpublish-community/commit/8b1f227e1d84bc78

### CODE REVIEW

**Comment by bdunogier** [comment]
+1 with @andrerom's remarks fixed

**Comment by andrerom** [comment]
Fixed the comment during merge, thanks @joaoinacio ! :)

**Comment by andrerom** [comment]
@bdunogier / @joaoinacio  Note that we still have 3 failing tests (down from 10):
https://travis-ci.org/ezsystems/ezpublish-community/jobs/44625405

**Comment by joaoinacio** [comment]
@andrerom : seems there are differences in response status between both auth. mechanisms...
I'm not certain at this time which way to go regarding tests... (ie. making tests pass for session could break http basic and vice-versa).
In any case, separate issue IMHO. Will look deeper into it, but seems like a REST problem

**Pull request closed without merging**
