### PR TITLE
Fix EZP-24399: Cross-siteaccess links do not take tree_root into account

### PR DESCRIPTION
**Pull request by joaoinacio**
JIRA: https://jira.ez.no/browse/EZP-24399

When generating cross-siteaccess links, the destination root location should be taken into account (so the path prefix is removed from the url).

Note: 
This does NOT (yet) modify the variables on the "fallback" section as it may be reverted, see https://github.com/ezsystems/ezpublish-kernel/pull/1259

TODO: 
- [x] Add/update tests

### CODE REVIEW

**Comment by joaoinacio** [comment]
I knew I shouldn't have turned off ezcs :(

**Comment by andrerom** [comment]
+1, ping @lolautruche

**Comment by lolautruche** [comment]
+1 with CS fixed

**Comment by joaoinacio** [comment]
CS updated.
@andrerom, @lolautruche : should this wait for https://jira.ez.no/browse/EZP-23498 resolution before merging?

**Comment by pspanja** [comment]
I think this is separate from the discussion on https://jira.ez.no/browse/EZP-23498, so for me it is +1 on both the PR and merging now.

**Comment by andrerom** [comment]
I also think it is separate, you where afraid of reverts?

**Comment by joaoinacio** [comment]
In a way yes... the following is under discussion and may potentially need a revert.
Also, although tests are passing, it won't make much sense considering this fix:
```
         // Fallback to root location in language switcher
         else if ( $siteaccess !== null && $this->rootLocationId !== null && $this->rootLocationId !== $location->id )
         {
             $locationService = $this->repository->getLocationService();
             $location = $locationService->loadLocation( $this->rootLocationId );
             return $this->doGenerate( $location, array( 'siteaccess' => $siteaccess ) );
         }
```

I could update `$this->rootLocationId` to `$rootLocationId` as well, since a git revert may already not be possible after this patch due to conflicts?

**Comment by andrerom** [comment]
Then revert EZP-23498 (all branches), and move that issue back to InputQ, this one has higher pri and the other one needs discussion.

**Pull request merged**
