### PR TITLE
fix: call to /api/ezp/v2/content/locations/1 caused server error

### PR DESCRIPTION
**Pull request by Nattfarinn**
JIRA ticket related: https://jira.ez.no/browse/EZP-24750

Reason: missing ownerId for fake ContentInfo

BTW: nice hack and only 1.5yr old TODO

### CODE REVIEW

**Comment by andrerom** [comment]
+1

Side: the missing content for the absolute root has been the case for 10 years, it is not supposed to be edited, so it became this :)

**Comment by dpobel** [comment]
no test on that ?

**Comment by Nattfarinn** [comment]
Not sure what's the value of such test. It would work as kind of regression for values set already but it's not real coverage and could even be misleading.

Having covered this fake ContentInfo would not prevent problem we have now and it won't prevent possible problems with other missing values in future. In case of such problem it would look like problem appeared in test-covered piece of code (what leads to point where test itself makes little to no sense).

**Comment by andrerom** [comment]
Unit test on the property added itself is indeed not adding much value. But what could have value is an integration test, but then I would except it to make sure all properties on the object is set, so then you also need to make sure the others are set to.

Place it should be added is `eZ\Publish\API\Repository\Tests\ LocationServiceTest`, there is at least one method testing case around root location `testLoadLocationsThrowsBadStateExceptionLimitedSubtree` and what you'll want is to test the given location like in `testLoadLocationStructValues`, however you also would like to test the content info here.

So name the test something like `testLoadRootLocationStructValues`.

For how to run the integration tests, just specify `-c phpunit-integration-legacy.xml` with no path filter to run the tests against sqlite.

**Comment by Nattfarinn** [comment]
@andrerom +1 . It makes sense.

New test case created.

**Comment by dpobel** [comment]
+1

**Comment by andrerom** [comment]
Thanks @Nattfarinn, next time we touch this code it is when someone has issues because admin is not 14 or remoteId is expected, but for now this is more than good enough ;) :+1:

**Pull request merged**
