### PR TITLE
[Composer] Bump PHPUnit to 4.8 for better PHP7 support

### PR DESCRIPTION
**Pull request by andrerom**
4.8 gives proper error output on TypeError for instance with PHP7, and is still maintained for some time.

### CODE REVIEW

**Comment by andrerom** [comment]
Travis says yes, ok @bdunogier?

**Comment by bdunogier** [comment]
Not disagreeing with Travis. Do we want to merge this to earlier versions to be consistent (6.2 or 6.1) ?

**Comment by andrerom** [comment]
> Not disagreeing with Travis. Do we want to merge this to earlier versions to be consistent (6.2 or 6.1) ?

that could make sense

**Comment by andrerom** [comment]
Closing in favor of #1617

**Pull request closed without merging**
